### ISSUE TITLE
Source Map support fails?

### ISSUE THREAD

**Issue by ace-han** [mirumee/saleor-storefront#1001]
### What I'm trying to achieve
…  Get the source map from `Sources` tap from browser devtool

### Steps to reproduce the problem
1. git clone https://github.com/mirumee/saleor-storefront.git
2. cd saleor-storefront
3. npm i
4. npm start

### What I expected to happen
… See and debug on the original `ts` or `tsx` files

### Screenshots

![image](https://user-images.githubusercontent.com/1177332/110242642-ea21c800-7f91-11eb-9ad3-906bd5922338.png)

**System information**
Operating system: macOS Big Sur 11.2.1
Browser: Chrome Version 88.0.4324.192

**Comment by piotrgrundas** [comment]
It's fixed in https://github.com/mirumee/saleor-storefront/pull/988
