### ISSUE TITLE
Unable to set index page background image using "feature on home page" collection

### ISSUE THREAD

**Issue by keanesf** [mirumee/saleor-storefront#1012]
### What I'm trying to achieve

On 3.0.0-a.5 I am attempting to change the home-page__hero background image. On 2.11 I was able to achieve this by creating a "feature on home page" collection and setting a background image.

### Steps to reproduce the problem
1. Create a "feature on home page" collection. 
2.Set a background image on the collection.

### What I expected to happen
Image should be displayed on home-page__hero on the index page of the storefront. Perhaps this is no longer supported ? 

### Screenshots

**System information**
Operating system: Linux
Browser:

**Comment by krzysztofwolski** [comment]
Feature is no longer supported.

**Comment by Megidd** [comment]
@keanesf I'm using Saleor 2.11 but I cannot find `feature on home page` checkbox. Where is it? Thanks! :smiley:
