### ISSUE TITLE
Depedency conflict with M1 ARM 

### ISSUE THREAD

**Issue by TimLS94** [mirumee/saleor-storefront#1018]
### What I'm trying to achieve
When trying to run Saleor on a M1 ARM macbook, a conflict with phantom.js in the storefront repo occurs. With my Intel Macbook this error does not occur.

### Steps to reproduce the problem
1. Follow the steps on saleor-platform README.md

### What I expected to happen
Running Saleor

**System information**
Using Saleor 2.11.8, Dashboard 2.11.1, Storefront 2.11
Operating system: macOS Big Sur, Version 11.1

**Comment by krzysztofwolski** [comment]
Unforinetly the team won't be able to address this issue, we don't have any m1 machines.

**Comment by TimLS94** [comment]
> Unforinetly the team won't be able to address this issue, we don't have any m1 machines.

Thank you for the response. I have worked around the problem by using Ubuntu with a virtual machine.

**Comment by tiendq** [comment]
@tkahng could you explain more detail about changes? I also got build error with M1 :(

Thank you,

**Comment by baophan-futa** [comment]
> @tkahng could you explain more detail about changes? I also got build error with M1 :(
> 
> Thank you,

First, edit your Dockerfile files:
- saleor-storefront/Dockerfile.dev
- saleor-dashboard/Dockerfile.dev (optional)
- saleor/Dockerfile (optional)

While declaring which image use for Dockerfile (`FROM` keyword). You should declare implicit which architecture are you using.
For me, on M1 devices, using `amd64`, so my Dockerfile content like below (note the first line):

```
FROM --platform=linux/amd64 node:10
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG API_URI
ENV API_URI ${API_URI:-http://localhost:8000/graphql/}

EXPOSE 3000
CMD npm start -- --host 0.0.0.0
```

- Some IDE will warning the syntax is invalid (after FROM has -- symbol), you can skip it.
- I tested on M1 devices, run perfectly when change the file `saleor-storefront/Dockerfile.dev`. You can skip for other Dockerfile.

**Comment by dphans** [comment]
> @tkahng could you explain more detail about changes? I also got build error with M1 :(
> 
> Thank you,

> @tkahng could you explain more detail about changes? I also got build error with M1 :(
> 
> Thank you,

First, edit your Dockerfile files:
- saleor-storefront/Dockerfile.dev
- saleor-dashboard/Dockerfile.dev (optional)
- saleor/Dockerfile (optional)

While declaring which image use for Dockerfile (`FROM` keyword). You should declare implicit which architecture are you using.
For me, on M1 devices, using `amd64`, so my Dockerfile content like below (note the first line):

```
FROM --platform=linux/amd64 node:10
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG API_URI
ENV API_URI ${API_URI:-http://localhost:8000/graphql/}

EXPOSE 3000
CMD npm start -- --host 0.0.0.0
```

- Some IDE will warning the syntax is invalid (after FROM has -- symbol), you can skip it.
- I tested on M1 devices, run perfectly when change the file `saleor-storefront/Dockerfile.dev`. You can skip for other Dockerfile.
