### ISSUE TITLE
Storefront sending data to Stripe even when not configured

### ISSUE THREAD

**Issue by dsychin** [mirumee/saleor-storefront#1021]
### What I'm trying to achieve
Disable Stripe.

### Steps to reproduce the problem
1. Set up Saleor
2. Visit storefront
3. Stripe js is loaded.
4. Data is being sent to stripe's servers.

### What I expected to happen
Since the stripe plugin is not active and not configured, it should not be sending data to stripe.

### Screenshots

**System information**
Operating system: Windows 10
Browser: Firefox

**Comment by krzysztofwolski** [comment]
In saleor 3.0 default bahaviour is changed - Stripe does not load unless you configure it.
