### ISSUE TITLE
Storefront returns 500

### ISSUE THREAD

**Issue by Bturan19** [mirumee/saleor-storefront#1048]
Hi, I have followed the instructions here: https://docs.saleor.io/docs/developer/installation

I have build and created docker image but when I try to run the platform. I can't acces to storefront. Even though I can acces to dashboard and graphql pages.

Anyone having similar issue?
…

![image](https://user-images.githubusercontent.com/43322527/119030493-a0525680-b9b2-11eb-930f-7daec61d50a0.png)

**System information**
Operating system: Ubuntu 20.04
Browser: Chrome

**Comment by tuannha** [comment]
I'm having the same issue

I tried to rebuild storefront image but it didn't work 

---
**System information** 
Operating system: Mac OSX 11.4
Docker: 3.3.3

**Comment by tuannha** [comment]
Well, I managed to run storefront with saleor-platform by:

* Stop docker instance by `docker-compose down`
* Reset changes, checkout latest release version of storefront which is `2.11.0` 
* Edit docker-compose.yml file from saleor-platoform. Under storefront service, change `command: npm start -- --hostname 0.0.0.0` to `command: npm start -- --host 0.0.0.0`
* run `docker-compose up -d` to start the services again
