### ISSUE TITLE
Service Worker Returns "bad-precaching-response" category/[slug]

### ISSUE THREAD

**Issue by thisispatso** [mirumee/saleor-storefront#1052]
### What I'm trying to achieve
Build & run the project.

### Steps to reproduce the problem
1.  npm run build:start

### What I expected to happen
Project to run without errors from service worker.

### Screenshots
![image](https://user-images.githubusercontent.com/17176793/121194913-d3805b00-c877-11eb-9b23-26e172355a8f.png)
![image](https://user-images.githubusercontent.com/17176793/121195030-ed21a280-c877-11eb-8657-4faab369b8ed.png)

As seen from the images, it won't pass the slug argument but I honestly don't see why since other pages are built and run properly.

**Comment by boreBoar** [comment]
Hi! Could you tell me how you solved this?

**Comment by albertphil** [comment]
@thisispatso Hi! Could you share the solution how do you solved this issue?

**Comment by thisispatso** [comment]
Hi, to be fair I cannot fully remember but I think that this was happening due to running the service worker within the dev environment. Try disabling it while developing and only enable it on prod.
