### ISSUE TITLE
BLOCKER - Removing item stays inside local storage and stops the checkout process completly.

### ISSUE THREAD

**Issue by gorjan-mishevski** [mirumee/saleor-storefront#1059]
Found a serious bug. You can observe this on the storefront demo app also.
The cart API remove item method doesn't remove the item, rather it only sets quantity 0.
Then when doing the checkout Saleor fails with "ZERO_QUANTITY" error.

Reproduce this by adding a product then removing the product. Then add another product. Go to checkout. Add address. Saleor fails. Observe the localstorage.

```
checkoutCreate: {,…}
checkout: null
errors: [{code: "ZERO_QUANTITY", field: "quantity", message: "The quantity should be higher than zero.",…}]
0: {code: "ZERO_QUANTITY", field: "quantity", message: "The quantity should be higher than zero.",…}
__typename: "CheckoutCreate"
```

**Comment by karolkielecki** [comment]
@gorjan-mishevski Hi! Thanks for reporting. We've fixed it in SDK: https://github.com/mirumee/saleor-sdk/releases/tag/v0.3.0-10. We'll also release the beta version of Saleor Storefront with some fixes, probably this week.

Cheers,
