### ISSUE TITLE
Storefront is still using `channel` in filters

### ISSUE THREAD

**Issue by sin-ack** [mirumee/saleor-storefront#1067]
### What I'm trying to achieve
I'm trying to run the demo storefront using the `3.0` branch to test it out; however, after mirumee/saleor@ef275083, the storefront fails to load categories and collections.

### Steps to reproduce the problem
1. Checkout the `3.0` branch of both the storefront and API
2. Try to run the demo storefront with `npm run start`

### What I expected to happen
The storefront to work.

**System information**
Operating system: Debian GNU/Linux bullseye/sid
Browser: Firefox 88

**Comment by MrP01** [comment]
Thank you for the commit reference! I think the problem might be originating from here:

```typescript
  const variables: ProductListVariables = {
    filter: {
      price: {
        lte: filters.priceLte,
        gte: filters.priceGte,
      },
      collections: collectionId ? [collectionId] : [],
      categories: categoryId ? [categoryId] : [],
      channel: channelSlug,
      attributes: filters.attributes
        ? convertToAttributeScalar(filters.attributes)
        : [],
    },
    channel: channelSlug,
    first: PRODUCTS_PER_PAGE,
    sortBy: convertSortByFromString(filters.sortBy),
  };
```

(confer ![this file](https://github.com/mirumee/saleor-storefront/blob/master/src/views/Category/queries.ts))

However, after removing the channel argument from the filter, the error keeps happening. I assume, `useTypedQuery()` fills the value based on the type given. The channel attribute is then defined in the `@saleor/sdk` package, in the GraphQL type `ProductFilterInput`. But even removing that doesn't fix the 400 error.

Any ideas? :)

**Comment by jayasth** [comment]
> Thank you for the commit reference! I think the problem might be originating from here:
> 
> ```ts
>   const variables: ProductListVariables = {
>     filter: {
>       price: {
>         lte: filters.priceLte,
>         gte: filters.priceGte,
>       },
>       collections: collectionId ? [collectionId] : [],
>       categories: categoryId ? [categoryId] : [],
>       channel: channelSlug,
>       attributes: filters.attributes
>         ? convertToAttributeScalar(filters.attributes)
>         : [],
>     },
>     channel: channelSlug,
>     first: PRODUCTS_PER_PAGE,
>     sortBy: convertSortByFromString(filters.sortBy),
>   };
> ```
> 
> (confer ![this file](https://github.com/mirumee/saleor-storefront/blob/master/src/views/Category/queries.ts))
> 
> However, after removing the channel argument from the filter, the error keeps happening. I assume, `useTypedQuery()` fills the value based on the type given. The channel attribute is then defined in the `@saleor/sdk` package, in the GraphQL type `ProductFilterInput`. But even removing that doesn't fix the 400 error.
> 
> Any ideas? :)

When I was playing around, I can visit categories and collections, if I delete these two lines after removing the arguments you mentioned above, for the moment : 
In this file : saleor-storefront/src/@next/graphql/queries.ts 
Line 50:
$channel: String!
Line 56:
channel: $channel

**Comment by tmechsner** [comment]
I run into a similar error. Even before start the storefront fails building static pages because of the channel filter which the backend doesn't recognize. Thus I deleted the channel argument in the query for ShopAttributes (lines 50 & 56 in src/@next/graphql/queries.ts and line 109 in src/@next/utils/ssr.ts) and then ran npm run build-schema to generate the gql types. 

We are setting up a shop that is to launch in mid September. We thought it's a good idea to use 3.0 beta version to easier bump it to 3.0 release version when it releases. Coming across errors like this makes me doubt that idea... looks like the storefront and backend are not being developed in sync at the moment. Any input on this?

**Comment by tmechsner** [comment]
Actually fixing it should be the other way round I think, because Saleor 3.0 will include that channel feature. So the backend should support the channel argument in the query.

**Comment by tmechsner** [comment]
I provided a little dirty fix in the related backend issue.

**Comment by jwm0** [comment]
SDK and SF were updated to reflect recent changes in channel api, here's the PR: https://github.com/mirumee/saleor-storefront/pull/1072
We'll be releasing 3.0 beta version of SF today with these changes.
