### ISSUE TITLE
hyperlinks are not working 

### ISSUE THREAD

**Issue by dev1143** [mirumee/saleor-storefront#1068]
### What I'm trying to achieve
…
to change the url of the storefront when an users clicks to an hyperlink on the header
### Steps to reproduce the problem
1. the url of the address bar is changing
2. but after on clicking it is not working..

### What I expected to happen
…
to change the links of the hyperlinks of the header
### Screenshots

**System information**
Operating system: 
Browser:

**Comment by karolkielecki** [comment]
@dev1143 Hi! Maybe the following thread can help you to modify your storefront: https://spectrum.chat/saleor/saleor-storefront/modifying-the-storefront~c1955dbf-a421-4fb6-b99e-937dd2642b23

If you still have some issues, please provide more details and screenshots showing which links exactly you would like to change. 

Cheers,
