### ISSUE TITLE
Network error: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000

### ISSUE THREAD

**Issue by flexpeace** [mirumee/saleor-storefront#1076]
I am getting the error below for store front, however, dashboard works flawlessly, any help?

storefront_1  | { Error: Network error: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000
storefront_1  |     at new ApolloError (/app/node_modules/apollo-client/bundle.umd.js:92:26)
storefront_1  |     at /app/node_modules/apollo-client/bundle.umd.js:1588:34
storefront_1  |     at /app/node_modules/apollo-client/bundle.umd.js:2008:15
storefront_1  |     at Set.forEach (<anonymous>)
storefront_1  |     at /app/node_modules/apollo-client/bundle.umd.js:2006:26
storefront_1  |     at Map.forEach (<anonymous>)
storefront_1  |     at QueryManager.broadcastQueries (/app/node_modules/apollo-client/bundle.umd.js:2004:20)
storefront_1  |     at /app/node_modules/apollo-client/bundle.umd.js:1483:29
storefront_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
storefront_1  |   graphQLErrors: [],
storefront_1  |   networkError:
storefront_1  |    { FetchError: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000
storefront_1  |        at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)
storefront_1  |        at ClientRequest.emit (events.js:198:13)
storefront_1  |        at Socket.socketErrorListener (_http_client.js:401:9)
storefront_1  |        at Socket.emit (events.js:198:13)
storefront_1  |        at emitErrorNT (internal/streams/destroy.js:91:8)
storefront_1  |        at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
storefront_1  |        at process._tickCallback (internal/process/next_tick.js:63:19)
storefront_1  |      message:
storefront_1  |       'request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000',
storefront_1  |      type: 'system',
storefront_1  |      errno: 'ECONNREFUSED',
storefront_1  |      code: 'ECONNREFUSED' },
storefront_1  |   message:
storefront_1  |    'Network error: request to http://localhost:8000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:8000',
storefront_1  |   extraInfo: undefined }

**Comment by rjusher** [comment]
@flexpeace 

Did you manage to solve this problem?

I am having the same issue deploying to heroku.

Dashboard and Core work great, but the Storefront is showing this ECONNREFUSED error even tough I setted the API_URI environment variable to point to the graphql endpoint.


Any help is appreciated.

Thanks

**Comment by TheBeachMaster** [comment]
The error is coming from this line, https://github.com/mirumee/saleor-storefront/blob/master/apollo.config.js#L12  and this https://github.com/mirumee/saleor-storefront/blob/master/src/constants.ts#L1

In `app.json` , `API_URI` is referenced > https://github.com/mirumee/saleor-storefront/blob/master/app.json#L9

**Comment by TheBeachMaster** [comment]
This fixes the deployment issue but now you'll run into `Error: Cannot find module 'next-transpile-modules'` I can not tell what that error is about  ... I can't fix that

**Comment by flexpeace** [comment]
I couldn't fix the issue, l had to run storefront on its own and commented out the storefront service inside docker-compose.yml

**Comment by gasser707** [comment]
make sure you are connecting to your dashboard using http://localhost:9000 and not 0.0.0.0, as this is the allowed URL in the env config of the saleor service in dockercompose

**Comment by vhscom** [comment]
```
connect ECONNREFUSED 127.0.0.1:8000
```

The connection was refused. Stop the API and try again and you'll likely see the same error. And if you do you know your issue is a Docker networking issue and nothing to do with the storefront nor the API. In the `docker-compose.yaml` provided with `saleor-platform` repo they're Compose file v2 syntax and using [`network_mode: "host"`](https://docs.docker.com/compose/compose-file/compose-file-v2/#network_mode) to allow storefront connect to the API.

**Comment by vhscom** [comment]
Original issue appears to [have been resolved](https://github.com/saleor/saleor-platform/commit/4530c24ef4ad1d234f7929ed10ddf68eff80ce7d#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3) the same day it was opened. Others encountering similar issues can debug it by first stoppig your API service and see if you receive the same response. If you do, focus your attention on Docker networking.

**Comment by vhscom** [comment]
Original issue appears to [have been resolved](https://github.com/saleor/saleor-platform/commit/4530c24ef4ad1d234f7929ed10ddf68eff80ce7d#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3) the same day it was opened. Others encountering similar issues can debug them by first stoppig your API service and see if you receive the same response. If you do, focus your attention on Docker networking.

**Comment by vhscom** [comment]
Original issue appears to [have been resolved](https://github.com/saleor/saleor-platform/commit/4530c24ef4ad1d234f7929ed10ddf68eff80ce7d#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3) the same day it was opened. Others encountering similar issues in development can debug them by first stoppig your API service and see if you receive the same response. If you do, focus your attention on Docker networking.
