### ISSUE TITLE
Demo exposes (and probably stores) the customer's information

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor-storefront#110]
We should truncate all of the personal details (names, addresses etc.) as we did on the regular storefront

Maybe for the demo store, we could just overwrite the `save()` method of each relevant model?

**Comment by maarcingebala** [comment]
All data provided by users is anonymized in our public demos. E.g. order details page in the old storefront:
![image](https://user-images.githubusercontent.com/5421321/47998365-5e68aa00-e0ff-11e8-880f-2edf882f1543.png)

However data generated by `populatedb` may be confusing as it looks like real and anonymization isn't applied there. This is a backend issue so I'll close this one and open relevant issue in Saleor repo.
