### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor-storefront#12]
We will use https://lingui.js.org/ package.  Language should be taken from:

1. url,
2. localstorage,
3. navigator.language

**Comment by yannterzi** [comment]
Hi,
thanks for this improvement.
It could be great for beginners to add 'npm run compile' as init step in Readme, because the application crash if messages.js didn't exist in installed locales.

**Comment by bogdal** [comment]
@yannterzi Good catch 👍 Thanks
