### ISSUE TITLE
Add newsletter sign up

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor-storefront#120]

**Comment by maarcingebala** [comment]
We don't have the newsletter feature in Saleor nor we're planning to add it in the nearest future. I think we should remove the whole line "Subscribe to our newsletter..." and the "Sign up" button (which currently doesn't do anything). @pwgryglak Could you update designs on Figma to reflect that change? We can also think of some other section to put here instead but honestly, I don't have any idea.

![image](https://user-images.githubusercontent.com/5421321/50092441-66dbf680-020e-11e9-87f6-53f53d9d9f4c.png)

Social buttons are fine and should stay of course.

**Comment by pwgryglak** [comment]
If we're not putting subscription to Saleor there is no need to look for to put an additional section just because we've got place for it. Designs are adjusted.
