### ISSUE TITLE
No clear indicator on the mobile while adding an item to the cart

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor-storefront#138]
So I've tried adding a new item to the cart on the mobile. It seems like nothing happens, but after all, item is added. 

I'd expect something more clear, like a drop-down at the top of the screen with a confirmation that item was successfully added to the cart. 

Also, I think we can do better with Add-to-cart animation, maybe something similar to Medium's clap animation? 

### Screenshots
![add_to_cart_mobile](https://user-images.githubusercontent.com/21290461/48216357-c8de4c00-e384-11e8-8837-bddd50b32d8f.gif)

**System information**
Operating system: iOS
Browser: Chrome

**Comment by NyanKiyoshi** [comment]
Isn't the same issue on desktop?
I was hesitating to open an issue for that, I'm not sure if it is already on the roadmap.

**Comment by Pacu2** [comment]
Right, both could use some sort of an improvement
