### ISSUE TITLE
How can I jump from existing saleor version to saleor-storefront 2.0

### ISSUE THREAD

**Issue by raviprakash007** [mirumee/saleor-storefront#141]
### What I'm trying to achieve

Upgrading From Saleor to saleor-storefront

### Steps to reproduce the problem
1. 
2. 

### What I expected to happen
…

### Screenshots

**System information**
Operating system: CentOS7
Browser:

**Comment by maarcingebala** [comment]
Hey, take a look at instructions in README. First, you need a running instance of [Saleor](https://github.com/mirumee/saleor/) as a backend, then you can build and run this storefront separately on a different port.
