### ISSUE TITLE
How to run it on other port than 3000

### ISSUE THREAD

**Issue by raviprakash007** [mirumee/saleor-storefront#142]
### What I'm trying to achieve
… Want to run on port number 80 on localhost

### Steps to reproduce the problem
1. 
2. 

### What I expected to happen
…

### Screenshots

[simpy.sri@e-commerce saleor-storefront]$ npm start

> saleor-site@0.1.0 start /home/simpy.sri/saleor2/saleor-storefront
> NODE_ENV=develop webpack-dev-server --history-api-fallback --open --watch --port 80 --host 0.0.0.0 --mode development

clean-webpack-plugin: /home/simpy.sri/saleor2/saleor-storefront/dist has been removed.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1269:19)
    at listenInCluster (net.js:1334:12)
    at doListen (net.js:1460:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor-site@0.1.0 start: `NODE_ENV=develop webpack-dev-server --history-api-fallback --open --watch --port 80 --host 0.0.0.0 --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the saleor-site@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/simpy.sri/.npm/_logs/2018-11-09T16_59_35_529Z-debug.log

**System information**
Operating system:  Linux CentOs7
Browser:

**Comment by NyanKiyoshi** [comment]
Hi,

You cannot make a program listen on the port 80 (any port < 1024) as a non-root user.
A quick [google search](https://www.google.com/search?hl=en&q=listen%20port%2080%20as%20user) will give you the answer on how to run it without root privileges.

**Comment by maarcingebala** [comment]
@raviprakash007 You cannot set it to `80` as described in the comment above. You can change it to any other allowed port in [package.json](https://github.com/mirumee/saleor-storefront/blob/master/package.json#L92) (look for `--port`).
