### ISSUE TITLE
Add OpenGraph and Meta tags

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor-storefront#146]
We should add OpenGraph and Meta Tags to the pages. 

This package could be used
https://www.npmjs.com/package/react-meta-tags

**Comment by maarcingebala** [comment]
I'm not sure if that's already implemented or not but we have `seoTitle` and `seoDescription` fields available for that purpose. They are available for the following models: `Product`, `Category`, `Collection`.

**Comment by maarcingebala** [comment]
Related issue - #169 - could be done as one PR.
