### ISSUE TITLE
Slugify does not suport non-English characters and generateCategoryUrl should use category.slug instead

### ISSUE THREAD

**Issue by jxltom** [mirumee/saleor-storefront#157]
### What I'm trying to achieve

The name of category can be any characters such as non-English characters but ```slugify``` only support English. This will generate empty url if category name is not fully english.

We could use ```category.slug``` which is generated from backend directly instead. But product url also has this kind of issue and graphql backend does not ```slug``` for ```product``` types.

Or we can let ```slugify``` support any characters, which is I would recommend

**Comment by korolevpavel** [comment]
I have the same error in Saleor 2.11

**Comment by fxp** [comment]
I have the same problem
