### ISSUE TITLE
Fresh Install - Checkout Summary Blank

### ISSUE THREAD

**Issue by steveconstantine** [mirumee/saleor-storefront#174]
Hey.

Great work.

I have 3 separate issues regarding a brand new install. 

1. The Cart doesn't transfer into the Checkout (no checkout summary visible).
2. The Shipping Address / Billing Address are saved as NULL when I enter in all information as a guest, and I get an error:

Uncaught (in promise) TypeError: Cannot read property 'firstName' of null
    at AddressSummary (index.tsx:12)

So the checkout isn't updating nor being created successfully from what I gather. I have no idea where to start with this!

3. The login creates a GraphQL permissions issue when I attempt to log into a newly created account:

Uncaught (in promise) Error: GraphQL error: You do not have permission to perform this action

Please advise.

steveconstantine!

**Comment by maarcingebala** [comment]
Hey @steveconstantine, thanks for reporting! We're in the middle of rethinking the entire checkout architecture. I have to admit that current implementation isn't perfect, but that's why we're still considering this project of beta quality. I'd recommend holding on with using it for now and waiting until the next release in January in which we're planning to fix all of those issues.

**Comment by maarcingebala** [comment]
About the third issue - this is a problem in our backend, I'll open an issue in Saleor repository.

**Comment by petrukngantuk** [comment]
Hello,
I'm run problem in this issue again,

Step to reproduce :
1. Install saleor v2.9.0 (using docker method) & saleor-dashboard v2.0.0 ( everything fine )
2. clone saleor-storefront & checkout to v0.7.0
3. `npm install`
4. `npm start:worker`
5. visit localhost:3000
6. clicked checkout icons, then blank 

chrome console log 
```
Uncaught TypeError: Cannot destructure property `node` of 'undefined' or 'null'.
    at utils.ts:13
    at Array.reduce (<anonymous>)
    at Object../src/components/CartProvider/utils.ts.exports.getTotal (utils.ts:12)
    at Cart.tsx:94
    at Object.children (queries.tsx:94)
    at finish (react-apollo.esm.js:348)
    at Query../node_modules/react-apollo/react-apollo.esm.js.Query.render (react-apollo.esm.js:352)
    at finishClassComponent (react-dom.development.js:14742)
    at updateClassComponent (react-dom.development.js:14697)
    at beginWork (react-dom.development.js:15645)
(anonymous) @ utils.ts:13
./src/components/CartProvider/utils.ts.exports.getTotal @ utils.ts:12
(anonymous) @ Cart.tsx:94
(anonymous) @ queries.tsx:94
finish @ react-apollo.esm.js:348
./node_modules/react-apollo/react-apollo.esm.js.Query.render @ react-apollo.esm.js:352
finishClassComponent @ react-dom.development.js:14742
updateClassComponent @ react-dom.development.js:14697
beginWork @ react-dom.development.js:15645
performUnitOfWork @ react-dom.development.js:19313
workLoop @ react-dom.development.js:19353
callCallback @ react-dom.development.js:150
invokeGuardedCallbackDev @ react-dom.development.js:200
invokeGuardedCallback @ react-dom.development.js:257
replayUnitOfWork @ react-dom.development.js:18579
renderRoot @ react-dom.development.js:19469
performWorkOnRoot @ react-dom.development.js:20343
performWork @ react-dom.development.js:20255
performSyncWork @ react-dom.development.js:20229
interactiveUpdates$1 @ react-dom.development.js:20496
interactiveUpdates @ react-dom.development.js:2171
dispatchInteractiveEvent @ react-dom.development.js:4883
react-dom.development.js:17118 The above error occurred in the <Query> component:
    in Query
    in Unknown (created by Context.Consumer)
    in NetworkStatus (created by Online)
    in Online (created by Cart)
    in div (created by Overlay)
    in div (created by Overlay)
    in Overlay (created by Cart)
    in Cart (created by Context.Consumer)
    in OverlayManager (created by App)
    in App (created by Route)
    in Route (created by Context.Consumer)
    in Switch (created by Context.Consumer)
    in CartProvider (created by Context.Consumer)
    in Unknown (created by Checkout)
    in Checkout
    in Provider (created by Route)
    in Route (created by withRouter(Provider))
    in withRouter(Provider)
    in Query
    in Unknown (created by ShopProvider)
    in ShopProvider
    in CredentialsProvider (created by SaleorProvider)
    in SaleorProvider
    in ApolloProvider
    in Route (created by QueryParamProvider)
    in QueryParamProvider
    in Router
    in Unknown (created by HotExportedComponent)
    in AppContainer (created by HotExportedComponent)
    in HotExportedComponent
    in Unknown
    in Provider
    in I18nProvider
    in Unknown
    in ThemeProvider

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
logCapturedError @ react-dom.development.js:17118
logError @ react-dom.development.js:17154
callback @ react-dom.development.js:18095
callCallback @ react-dom.development.js:16434
commitUpdateEffects @ react-dom.development.js:16473
commitUpdateQueue @ react-dom.development.js:16464
commitLifeCycles @ react-dom.development.js:17365
commitAllLifeCycles @ react-dom.development.js:18737
callCallback @ react-dom.development.js:150
invokeGuardedCallbackDev @ react-dom.development.js:200
invokeGuardedCallback @ react-dom.development.js:257
commitRoot @ react-dom.development.js:18949
(anonymous) @ react-dom.development.js:20419
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20418
performWorkOnRoot @ react-dom.development.js:20347
performWork @ react-dom.development.js:20255
performSyncWork @ react-dom.development.js:20229
interactiveUpdates$1 @ react-dom.development.js:20496
interactiveUpdates @ react-dom.development.js:2171
dispatchInteractiveEvent @ react-dom.development.js:4883
react-hot-loader.development.js:247 TypeError: Cannot destructure property `node` of 'undefined' or 'null'.
    at utils.ts:13
    at Array.reduce (<anonymous>)
    at Object../src/components/CartProvider/utils.ts.exports.getTotal (utils.ts:12)
    at Cart.tsx:94
    at Object.children (queries.tsx:94)
    at finish (react-apollo.esm.js:348)
    at Query../node_modules/react-apollo/react-apollo.esm.js.Query.render (react-apollo.esm.js:352)
    at finishClassComponent (react-dom.development.js:14742)
    at updateClassComponent (react-dom.development.js:14697)
    at beginWork (react-dom.development.js:15645)
error @ react-hot-loader.development.js:247
componentDidCatch @ react-hot-loader.development.js:2183
callback @ react-dom.development.js:18096
callCallback @ react-dom.development.js:16434
commitUpdateEffects @ react-dom.development.js:16473
commitUpdateQueue @ react-dom.development.js:16464
commitLifeCycles @ react-dom.development.js:17365
commitAllLifeCycles @ react-dom.development.js:18737
callCallback @ react-dom.development.js:150
invokeGuardedCallbackDev @ react-dom.development.js:200
invokeGuardedCallback @ react-dom.development.js:257
commitRoot @ react-dom.development.js:18949
(anonymous) @ react-dom.development.js:20419
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20418
performWorkOnRoot @ react-dom.development.js:20347
performWork @ react-dom.development.js:20255
performSyncWork @ react-dom.development.js:20229
interactiveUpdates$1 @ react-dom.development.js:20496
interactiveUpdates @ react-dom.development.js:2171
dispatchInteractiveEvent @ react-dom.development.js:4883
utils.ts:13 Uncaught TypeError: Cannot destructure property `node` of 'undefined' or 'null'.
    at utils.ts:13
    at Array.reduce (<anonymous>)
    at Object../src/components/CartProvider/utils.ts.exports.getTotal (utils.ts:12)
    at Cart.tsx:94
    at Object.children (queries.tsx:94)
    at finish (react-apollo.esm.js:348)
    at Query../node_modules/react-apollo/react-apollo.esm.js.Query.render (react-apollo.esm.js:352)
    at finishClassComponent (react-dom.development.js:14742)
    at updateClassComponent (react-dom.development.js:14697)
    at beginWork (react-dom.development.js:15645)
(anonymous) @ utils.ts:13
./src/components/CartProvider/utils.ts.exports.getTotal @ utils.ts:12
(anonymous) @ Cart.tsx:94
(anonymous) @ queries.tsx:94
finish @ react-apollo.esm.js:348
./node_modules/react-apollo/react-apollo.esm.js.Query.render @ react-apollo.esm.js:352
finishClassComponent @ react-dom.development.js:14742
updateClassComponent @ react-dom.development.js:14697
beginWork @ react-dom.development.js:15645
performUnitOfWork @ react-dom.development.js:19313
workLoop @ react-dom.development.js:19353
renderRoot @ react-dom.development.js:19436
performWorkOnRoot @ react-dom.development.js:20343
performWork @ react-dom.development.js:20255
performSyncWork @ react-dom.development.js:20229
interactiveUpdates$1 @ react-dom.development.js:20496
interactiveUpdates @ react-dom.development.js:2171
dispatchInteractiveEvent @ react-dom.development.js:4883
react-dom.development.js:17118 The above error occurred in the <AppContainer> component:
    in AppContainer (created by HotExportedComponent)
    in HotExportedComponent
    in Unknown
    in Provider
    in I18nProvider
    in Unknown
    in ThemeProvider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:17118
logError @ react-dom.development.js:17154
update.callback @ react-dom.development.js:18066
callCallback @ react-dom.development.js:16434
commitUpdateEffects @ react-dom.development.js:16473
commitUpdateQueue @ react-dom.development.js:16461
commitLifeCycles @ react-dom.development.js:17384
commitAllLifeCycles @ react-dom.development.js:18737
callCallback @ react-dom.development.js:150
invokeGuardedCallbackDev @ react-dom.development.js:200
invokeGuardedCallback @ react-dom.development.js:257
commitRoot @ react-dom.development.js:18949
(anonymous) @ react-dom.development.js:20419
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20418
performWorkOnRoot @ react-dom.development.js:20347
performWork @ react-dom.development.js:20255
performSyncWork @ react-dom.development.js:20229
interactiveUpdates$1 @ react-dom.development.js:20496
interactiveUpdates @ react-dom.development.js:2171
dispatchInteractiveEvent @ react-dom.development.js:4883
utils.ts:13 Uncaught TypeError: Cannot destructure property `node` of 'undefined' or 'null'.
    at utils.ts:13
    at Array.reduce (<anonymous>)
    at Object../src/components/CartProvider/utils.ts.exports.getTotal (utils.ts:12)
    at Cart.tsx:94
    at Object.children (queries.tsx:94)
    at finish (react-apollo.esm.js:348)
    at Query../node_modules/react-apollo/react-apollo.esm.js.Query.render (react-apollo.esm.js:352)
    at finishClassComponent (react-dom.development.js:14742)
    at updateClassComponent (react-dom.development.js:14697)
    at beginWork (react-dom.development.js:15645)
(anonymous) @ utils.ts:13
./src/components/CartProvider/utils.ts.exports.getTotal @ utils.ts:12
(anonymous) @ Cart.tsx:94
(anonymous) @ queries.tsx:94
finish @ react-apollo.esm.js:348
./node_modules/react-apollo/react-apollo.esm.js.Query.render @ react-apollo.esm.js:352
finishClassComponent @ react-dom.development.js:14742
updateClassComponent @ react-dom.development.js:14697
beginWork @ react-dom.development.js:15645
performUnitOfWork @ react-dom.development.js:19313
workLoop @ react-dom.development.js:19353
renderRoot @ react-dom.development.js:19436
performWorkOnRoot @ react-dom.development.js:20343
performWork @ react-dom.development.js:20255
performSyncWork @ react-dom.development.js:20229
interactiveUpdates$1 @ react-dom.development.js:20496
interactiveUpdates @ react-dom.development.js:2171
dispatchInteractiveEvent @ react-dom.development.js:4883
react-dom.development.js:507 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Cart (created by Context.Consumer)
    in OverlayManager (created by App)
    in App (created by Route)
    in Route (created by Context.Consumer)
    in Switch (created by Context.Consumer)
    in CartProvider (created by Context.Consumer)
    in Unknown (created by Checkout)
    in Checkout
    in Provider (created by Route)
    in Route (created by withRouter(Provider))
    in withRouter(Provider)
    in Query
    in Unknown (created by ShopProvider)
    in ShopProvider
    in CredentialsProvider (created by SaleorProvider)
    in SaleorProvider
    in ApolloProvider
    in Route (created by QueryParamProvider)
    in QueryParamProvider
    in Router
    in Unknown (created by HotExportedComponent)

```

![Screenshot at Oct 30 01-40-40](https://user-images.githubusercontent.com/4683704/67798589-5e9f4980-fab6-11e9-827c-08a15dbe9497.png)
![Screenshot at Oct 30 01-40-54](https://user-images.githubusercontent.com/4683704/67798591-5f37e000-fab6-11e9-8cf2-4b2e93d187bc.png)

anyone can help?

**Comment by svenvanlierde** [comment]
> Hello,
> I'm run problem in this issue again,
> 
> Step to reproduce :
> 
> 1. Install saleor v2.9.0 (using docker method) & saleor-dashboard v2.0.0 ( everything fine )
> 2. clone saleor-storefront & checkout to v0.7.0
> 3. `npm install`
> 4. `npm start:worker`
> 5. visit localhost:3000
> 6. clicked checkout icons, then blank
> 
> chrome console log
> 
> ```
> Uncaught TypeError: Cannot destructure property `node` of 'undefined' or 'null'.
>     at utils.ts:13
>     at Array.reduce (<anonymous>)
>     at Object../src/components/CartProvider/utils.ts.exports.getTotal (utils.ts:12)
>     at Cart.tsx:94
>     at Object.children (queries.tsx:94)
>     at finish (react-apollo.esm.js:348)
>     at Query../node_modules/react-apollo/react-apollo.esm.js.Query.render (react-apollo.esm.js:352)
>     at finishClassComponent (react-dom.development.js:14742)
>     at updateClassComponent (react-dom.development.js:14697)
>     at beginWork (react-dom.development.js:15645)
> (anonymous) @ utils.ts:13
> ./src/components/CartProvider/utils.ts.exports.getTotal @ utils.ts:12
> (anonymous) @ Cart.tsx:94
> (anonymous) @ queries.tsx:94
> finish @ react-apollo.esm.js:348
> ./node_modules/react-apollo/react-apollo.esm.js.Query.render @ react-apollo.esm.js:352
> finishClassComponent @ react-dom.development.js:14742
> updateClassComponent @ react-dom.development.js:14697
> beginWork @ react-dom.development.js:15645
> performUnitOfWork @ react-dom.development.js:19313
> workLoop @ react-dom.development.js:19353
> callCallback @ react-dom.development.js:150
> invokeGuardedCallbackDev @ react-dom.development.js:200
> invokeGuardedCallback @ react-dom.development.js:257
> replayUnitOfWork @ react-dom.development.js:18579
> renderRoot @ react-dom.development.js:19469
> performWorkOnRoot @ react-dom.development.js:20343
> performWork @ react-dom.development.js:20255
> performSyncWork @ react-dom.development.js:20229
> interactiveUpdates$1 @ react-dom.development.js:20496
> interactiveUpdates @ react-dom.development.js:2171
> dispatchInteractiveEvent @ react-dom.development.js:4883
> react-dom.development.js:17118 The above error occurred in the <Query> component:
>     in Query
>     in Unknown (created by Context.Consumer)
>     in NetworkStatus (created by Online)
>     in Online (created by Cart)
>     in div (created by Overlay)
>     in div (created by Overlay)
>     in Overlay (created by Cart)
>     in Cart (created by Context.Consumer)
>     in OverlayManager (created by App)
>     in App (created by Route)
>     in Route (created by Context.Consumer)
>     in Switch (created by Context.Consumer)
>     in CartProvider (created by Context.Consumer)
>     in Unknown (created by Checkout)
>     in Checkout
>     in Provider (created by Route)
>     in Route (created by withRouter(Provider))
>     in withRouter(Provider)
>     in Query
>     in Unknown (created by ShopProvider)
>     in ShopProvider
>     in CredentialsProvider (created by SaleorProvider)
>     in SaleorProvider
>     in ApolloProvider
>     in Route (created by QueryParamProvider)
>     in QueryParamProvider
>     in Router
>     in Unknown (created by HotExportedComponent)
>     in AppContainer (created by HotExportedComponent)
>     in HotExportedComponent
>     in Unknown
>     in Provider
>     in I18nProvider
>     in Unknown
>     in ThemeProvider
> 
> React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
> logCapturedError @ react-dom.development.js:17118
> logError @ react-dom.development.js:17154
> callback @ react-dom.development.js:18095
> callCallback @ react-dom.development.js:16434
> commitUpdateEffects @ react-dom.development.js:16473
> commitUpdateQueue @ react-dom.development.js:16464
> commitLifeCycles @ react-dom.development.js:17365
> commitAllLifeCycles @ react-dom.development.js:18737
> callCallback @ react-dom.development.js:150
> invokeGuardedCallbackDev @ react-dom.development.js:200
> invokeGuardedCallback @ react-dom.development.js:257
> commitRoot @ react-dom.development.js:18949
> (anonymous) @ react-dom.development.js:20419
> unstable_runWithPriority @ scheduler.development.js:255
> completeRoot @ react-dom.development.js:20418
> performWorkOnRoot @ react-dom.development.js:20347
> performWork @ react-dom.development.js:20255
> performSyncWork @ react-dom.development.js:20229
> interactiveUpdates$1 @ react-dom.development.js:20496
> interactiveUpdates @ react-dom.development.js:2171
> dispatchInteractiveEvent @ react-dom.development.js:4883
> react-hot-loader.development.js:247 TypeError: Cannot destructure property `node` of 'undefined' or 'null'.
>     at utils.ts:13
>     at Array.reduce (<anonymous>)
>     at Object../src/components/CartProvider/utils.ts.exports.getTotal (utils.ts:12)
>     at Cart.tsx:94
>     at Object.children (queries.tsx:94)
>     at finish (react-apollo.esm.js:348)
>     at Query../node_modules/react-apollo/react-apollo.esm.js.Query.render (react-apollo.esm.js:352)
>     at finishClassComponent (react-dom.development.js:14742)
>     at updateClassComponent (react-dom.development.js:14697)
>     at beginWork (react-dom.development.js:15645)
> error @ react-hot-loader.development.js:247
> componentDidCatch @ react-hot-loader.development.js:2183
> callback @ react-dom.development.js:18096
> callCallback @ react-dom.development.js:16434
> commitUpdateEffects @ react-dom.development.js:16473
> commitUpdateQueue @ react-dom.development.js:16464
> commitLifeCycles @ react-dom.development.js:17365
> commitAllLifeCycles @ react-dom.development.js:18737
> callCallback @ react-dom.development.js:150
> invokeGuardedCallbackDev @ react-dom.development.js:200
> invokeGuardedCallback @ react-dom.development.js:257
> commitRoot @ react-dom.development.js:18949
> (anonymous) @ react-dom.development.js:20419
> unstable_runWithPriority @ scheduler.development.js:255
> completeRoot @ react-dom.development.js:20418
> performWorkOnRoot @ react-dom.development.js:20347
> performWork @ react-dom.development.js:20255
> performSyncWork @ react-dom.development.js:20229
> interactiveUpdates$1 @ react-dom.development.js:20496
> interactiveUpdates @ react-dom.development.js:2171
> dispatchInteractiveEvent @ react-dom.development.js:4883
> utils.ts:13 Uncaught TypeError: Cannot destructure property `node` of 'undefined' or 'null'.
>     at utils.ts:13
>     at Array.reduce (<anonymous>)
>     at Object../src/components/CartProvider/utils.ts.exports.getTotal (utils.ts:12)
>     at Cart.tsx:94
>     at Object.children (queries.tsx:94)
>     at finish (react-apollo.esm.js:348)
>     at Query../node_modules/react-apollo/react-apollo.esm.js.Query.render (react-apollo.esm.js:352)
>     at finishClassComponent (react-dom.development.js:14742)
>     at updateClassComponent (react-dom.development.js:14697)
>     at beginWork (react-dom.development.js:15645)
> (anonymous) @ utils.ts:13
> ./src/components/CartProvider/utils.ts.exports.getTotal @ utils.ts:12
> (anonymous) @ Cart.tsx:94
> (anonymous) @ queries.tsx:94
> finish @ react-apollo.esm.js:348
> ./node_modules/react-apollo/react-apollo.esm.js.Query.render @ react-apollo.esm.js:352
> finishClassComponent @ react-dom.development.js:14742
> updateClassComponent @ react-dom.development.js:14697
> beginWork @ react-dom.development.js:15645
> performUnitOfWork @ react-dom.development.js:19313
> workLoop @ react-dom.development.js:19353
> renderRoot @ react-dom.development.js:19436
> performWorkOnRoot @ react-dom.development.js:20343
> performWork @ react-dom.development.js:20255
> performSyncWork @ react-dom.development.js:20229
> interactiveUpdates$1 @ react-dom.development.js:20496
> interactiveUpdates @ react-dom.development.js:2171
> dispatchInteractiveEvent @ react-dom.development.js:4883
> react-dom.development.js:17118 The above error occurred in the <AppContainer> component:
>     in AppContainer (created by HotExportedComponent)
>     in HotExportedComponent
>     in Unknown
>     in Provider
>     in I18nProvider
>     in Unknown
>     in ThemeProvider
> 
> Consider adding an error boundary to your tree to customize error handling behavior.
> Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
> logCapturedError @ react-dom.development.js:17118
> logError @ react-dom.development.js:17154
> update.callback @ react-dom.development.js:18066
> callCallback @ react-dom.development.js:16434
> commitUpdateEffects @ react-dom.development.js:16473
> commitUpdateQueue @ react-dom.development.js:16461
> commitLifeCycles @ react-dom.development.js:17384
> commitAllLifeCycles @ react-dom.development.js:18737
> callCallback @ react-dom.development.js:150
> invokeGuardedCallbackDev @ react-dom.development.js:200
> invokeGuardedCallback @ react-dom.development.js:257
> commitRoot @ react-dom.development.js:18949
> (anonymous) @ react-dom.development.js:20419
> unstable_runWithPriority @ scheduler.development.js:255
> completeRoot @ react-dom.development.js:20418
> performWorkOnRoot @ react-dom.development.js:20347
> performWork @ react-dom.development.js:20255
> performSyncWork @ react-dom.development.js:20229
> interactiveUpdates$1 @ react-dom.development.js:20496
> interactiveUpdates @ react-dom.development.js:2171
> dispatchInteractiveEvent @ react-dom.development.js:4883
> utils.ts:13 Uncaught TypeError: Cannot destructure property `node` of 'undefined' or 'null'.
>     at utils.ts:13
>     at Array.reduce (<anonymous>)
>     at Object../src/components/CartProvider/utils.ts.exports.getTotal (utils.ts:12)
>     at Cart.tsx:94
>     at Object.children (queries.tsx:94)
>     at finish (react-apollo.esm.js:348)
>     at Query../node_modules/react-apollo/react-apollo.esm.js.Query.render (react-apollo.esm.js:352)
>     at finishClassComponent (react-dom.development.js:14742)
>     at updateClassComponent (react-dom.development.js:14697)
>     at beginWork (react-dom.development.js:15645)
> (anonymous) @ utils.ts:13
> ./src/components/CartProvider/utils.ts.exports.getTotal @ utils.ts:12
> (anonymous) @ Cart.tsx:94
> (anonymous) @ queries.tsx:94
> finish @ react-apollo.esm.js:348
> ./node_modules/react-apollo/react-apollo.esm.js.Query.render @ react-apollo.esm.js:352
> finishClassComponent @ react-dom.development.js:14742
> updateClassComponent @ react-dom.development.js:14697
> beginWork @ react-dom.development.js:15645
> performUnitOfWork @ react-dom.development.js:19313
> workLoop @ react-dom.development.js:19353
> renderRoot @ react-dom.development.js:19436
> performWorkOnRoot @ react-dom.development.js:20343
> performWork @ react-dom.development.js:20255
> performSyncWork @ react-dom.development.js:20229
> interactiveUpdates$1 @ react-dom.development.js:20496
> interactiveUpdates @ react-dom.development.js:2171
> dispatchInteractiveEvent @ react-dom.development.js:4883
> react-dom.development.js:507 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
>     in Cart (created by Context.Consumer)
>     in OverlayManager (created by App)
>     in App (created by Route)
>     in Route (created by Context.Consumer)
>     in Switch (created by Context.Consumer)
>     in CartProvider (created by Context.Consumer)
>     in Unknown (created by Checkout)
>     in Checkout
>     in Provider (created by Route)
>     in Route (created by withRouter(Provider))
>     in withRouter(Provider)
>     in Query
>     in Unknown (created by ShopProvider)
>     in ShopProvider
>     in CredentialsProvider (created by SaleorProvider)
>     in SaleorProvider
>     in ApolloProvider
>     in Route (created by QueryParamProvider)
>     in QueryParamProvider
>     in Router
>     in Unknown (created by HotExportedComponent)
> ```
> 
> ![Screenshot at Oct 30 01-40-40](https://user-images.githubusercontent.com/4683704/67798589-5e9f4980-fab6-11e9-827c-08a15dbe9497.png)
> ![Screenshot at Oct 30 01-40-54](https://user-images.githubusercontent.com/4683704/67798591-5f37e000-fab6-11e9-8cf2-4b2e93d187bc.png)
> 
> anyone can help?

i've the same problem..
you already found a solution?

thanks

**Comment by orzechdev** [comment]
Hey, can you describe the issue more precisely? Especially sixth step, because I'm not able to reproduce the problem.
