### ISSUE TITLE
Implement user account page

### ISSUE THREAD

**Issue by hassanzadeh** [mirumee/saleor-storefront#175]
### What I'm trying to achieve
The previous store front has the list of last orders under account, for this one, only the logout exist there!

Is it not implemented yet?

**Comment by maarcingebala** [comment]
Right, there is no such view yet but we're planning to add it. Not sure if there is an issue for that already, if not then I'll create one. Should be added in January or February.

**Comment by maarcingebala** [comment]
No, it's not implemented yet. The picture above shows a mockup of the interface that will be added.

**Comment by lexvz** [comment]
Hi @maarcingebala,

Do you have an idea when this feature will be implemented?

Thanks in advance!

**Comment by bogdal** [comment]
The user profile page is already implemented 🎉
