### ISSUE TITLE
Storefront Improvements

### ISSUE THREAD

**Issue by pwgryglak** [mirumee/saleor-storefront#176]
I've made a review to the storefront and found a couple of things that can improve UX and Consistency 

Adds:
- [x] "QUICK SEARCH VIEW" Add explainer text to quick search with no results - Can be found on mockups
- [x] "Search input" should work after hitting enter - right now it doesn't
- [x] Losing focus on "search input" should collapse the input 
- [x] "SHOPPING CART" Change "Shopping Cart" text to "Shopping Bag" increases consistency in naming
- [x] "My Bag Drawer" Change text on button from "My Bag" to "Go to my bag" - more explanatory
- [x] Change copy on "No search results" page - copy can be found on designs

**Comment by maarcingebala** [comment]
Thanks @pwgryglak!
