### ISSUE TITLE
relation "django_session" does not exist LINE 1: ...ession_data", "django_session"."expire_date" FROM

### ISSUE THREAD

**Issue by officerebel** [mirumee/saleor-storefront#179]
### What I'm trying to achieve
Run saleor Locally with docker

### Steps to reproduce the problem
1. docker-compuse up

### What I expected to happen
see the saleor app

### Screenshots

Request Method: | GET
-- | --
http://127.0.0.1:8000/
2.1.4
ProgrammingError
relation "django_session" does not exist LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...                                                              ^
/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py in _execute, line 85
/usr/local/bin/python
3.6.7
['/app',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages',  '/app']
do, 27 Dec 2018 08:02:03 +0100

**System information**
Operating system: 
Browser:

**Comment by maarcingebala** [comment]
It looks like migrations weren't run. You can run them with this command:
```
docker-compose run web python3 manage.py migrate
```

You can also inspect what migrations were run with this one:
```
docker-compose run web python3 manage.py showmigrations
```

For the future - please open Django/backend related issues in [Saleor repository](https://github.com/mirumee/saleor). This one is meant for tracking issues related to the single-page storefront client (so mostly JS or design issues).

**Comment by maarcingebala** [comment]
If the commands I posted above doesn't help, please open this issue in Saleor repository.
