### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-storefront#187]
The time has come to consider adding a test framework 🙂. In the Dashboard 2.0 we use `jest` and I think that it works fine, but probably @dominik-zeglen has more to say about it. I'm not familiar with the best practices for testing React so I'll leave it for discussion to frontend guys: @piotrgrundas @dominik-zeglen @patrys 

Next week we're going to start checkout refactoring and I think it'll be a good ocassion to start adding tests as well.

**Comment by piotrgrundas** [comment]
Probably `jest` + `enzyme` would be the best choice.
