### ISSUE TITLE
Dynamic filters

### ISSUE THREAD

**Issue by piotrgrundas** [mirumee/saleor-storefront#188]
Currently, when someone tries to search a product and narrow out the results using filters there is no way of clearing the criteria. 
As established with @pwgryglak we need to add a clear filters option and change to display only filters that are available for left products as we search - not all of them.
The same goes for the price filter which needs an update.
![image](https://user-images.githubusercontent.com/5078402/50625159-79e90900-0f26-11e9-9de6-c264394bb09b.png)

Also in this ticket, we could improve a bit UX of the search in such way, that only the container with the filters and products list will rerender upon search - without the container with search phrase input which should be only disabled while fetching data.

**Comment by pwgryglak** [comment]
Clear filters button is added to the mockups. I agree with everything Pete written.
