### ISSUE TITLE
Store currently selected variant in the URL

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-storefront#192]
We should extend the variant selector to store its state in the URL. Also, we should be able to recreate the state of variant selector from the query string.

![image](https://user-images.githubusercontent.com/5421321/50689243-1f84a100-1029-11e9-83ab-b65d2509822c.png)

This is currently implemented in the old storefront e.g. entering this URL results in preselecting the XXL variant:

https://demo.getsaleor.com/en/products/code-division-t-shirt-89/?size=xxl

`size` is a slug for the "Size" attribute, while `xxl` is a slug of one of the possible values for that attribute.

**Comment by bogdal** [comment]
We need to keep in mind that this requires sitemap generator adaptation.

**Comment by krzysztofwolski** [comment]
Implemented in #708
