### ISSUE TITLE
Implement PWA update mechanism after releases

### ISSUE THREAD

**Issue by piotrgrundas** [mirumee/saleor-storefront#203]
Currently, after each release user needs to clear the cache for the page to work. We need to implement some sort of update mechanism to avoid this.

**Comment by timuric** [comment]
@piotrgrundas is it related to Apollo cache or is it more than that?

**Comment by bogdal** [comment]
We have replaced `sw-precache` in favor of [Workbox](https://developers.google.com/web/tools/workbox/guides/get-started) which resolved some of our problems with cache.
