### ISSUE TITLE
Add ability to chose payment type

### ISSUE THREAD

**Issue by piotrgrundas** [mirumee/saleor-storefront#208]
Currently, we hardcode Braintree to be the only available payment method. As the [backend allows retrieving available payment](https://github.com/mirumee/saleor/issues/3617) methods from the API, we should add the ability for users to chose them at checkout.

**NOTE**
Here also please extract page content into a separate component and wrap it with`<StepCheck/>` component. Sometimes still, after the view is cached, and someone jumps manually i.e. from shipping options to payment app breaks.

**Comment by pwgryglak** [comment]
@piotrgrundas 
Design is prepared to handle more than one payment option at checkout.
Can you provide a difference that we should adjust the designs to?

**Comment by piotrgrundas** [comment]
@pwgryglak My bad. Found them after creating a ticket
