### ISSUE TITLE
Cannot see Dashboard or User Profile option in Storefront UI.

### ISSUE THREAD

**Issue by amitosh1995** [mirumee/saleor-storefront#214]
### What I'm trying to achieve
… when i login using superuser account in new storefront. I cannot see dashboard or userprofile option. Is this a bug or a feature yet to be added ? or Do i have to deploy on heroku to see the feature ?

Also can you please tell me what process to follow to properly deploy both the backend and frontend on heroku properly in windows 10?

### Steps to reproduce the problem
1. 
2. 

### What I expected to happen
…

### Screenshots

**System information**
Operating system: Windows 10 x64
Browser: Chrome
![untitled2](https://user-images.githubusercontent.com/29412198/51373551-79f02800-1b26-11e9-8ed1-6261a98981f3.png)

**Comment by amitosh1995** [comment]
I can see the dashboard and user profile only in the old saleor UI which is hosted at `http://localhost:8000/dashboard`.

**Comment by piotrgrundas** [comment]
I don' think this is a storefront issue. It's normal that locally backend and frontend are running on different ports thus u can't reach them by the same URL. 
I.e. by using nginx u could solve that problem.

**Comment by amitosh1995** [comment]
Sorry for the late reply but @piotrgrundas solved my doubt. :)
