### ISSUE TITLE
Add register option at login screen

### ISSUE THREAD

**Issue by piotrgrundas** [mirumee/saleor-storefront#218]
![image](https://user-images.githubusercontent.com/5078402/51459288-514f7480-1d58-11e9-9440-75291a36c171.png)

**Comment by maarcingebala** [comment]
@pwgryglak What should happen after clicking the "create an account" link? Currently, registration is available in the right overlay panel after clicking on the user icon in the top bar. I guess we could just open this drawer when users click on this link:

![image](https://user-images.githubusercontent.com/5421321/56357371-de7d5a80-61db-11e9-84b7-a2f4857f725f.png)

**Comment by pwgryglak** [comment]
@maarcingebala 
Exactly. There is a view in the project showing. That it should do exactly that.
