### ISSUE TITLE
'NODE_ENV' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by hoflish** [mirumee/saleor-storefront#232]
### What I'm trying to achieve
I want to run the development server

### Steps to reproduce the problem
1. Running `npm start`

### Screenshots  
`$ npm start`

`> NODE_ENV=develop webpack-dev-server --history-api-fallback --watch --port 3000 --mode development

'NODE_ENV' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor-site@0.3.0 start: `NODE_ENV=develop webpack-dev-server --history-api-fallback --watch --port 3000 --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the saleor-site@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

### System information
Operating system: **Windows 10**
Browser: ...

### Resolution
 I installed the cross-env package by running `npm i cross-env`, then updated the scripts to reflect it:

```javascript
"scripts": {
   // ...
   "start": "cross-env NODE_ENV=develop && webpack-dev-server --history-api-fallback --watch --port 3000 --mode development",
   // ...
  }
```

**Comment by 2mwayungi** [comment]
os:windows 10
I get 
WARNING in EnvironmentPlugin - http://localhost:8000/ environment variable is undefined.

can you show me  your  BACKEND_URL

**Comment by hoflish** [comment]
Hi @2mwayungi , 
After running an instance of Saleor:
```javascript
$ python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
February 06, 2019 - 14:06:48
Django version 2.1.5, using settings 'saleor.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
```
you have to set the BACKEND_URL environment to point to the Saleor instance running at http://127.0.0.1:8000/
