### ISSUE TITLE
WARNING in EnvironmentPlugin - http://localhost:8000/ environment variable is undefined.

### ISSUE THREAD

**Issue by 2mwayungi** [mirumee/saleor-storefront#234]
os: windows 10
I run Saleor locally with the default settings,  I set BACKEND_URL to: http://localhost:8000/ 

running npm start  gives the warning

![g](https://user-images.githubusercontent.com/42558854/52175557-a6f33a80-27b6-11e9-8f0e-08b21d6bb82c.jpg)

**Comment by piotrgrundas** [comment]
As the error claims, set the env var BACKEND_URL='http://127.0.0.1:8000/'`

**Comment by 2mwayungi** [comment]
i still receive warning after setting  BACKEND_URL='http://127.0.0.1:8000/`

**Comment by hoflish** [comment]
@2mwayungi , did you check if BACKEND_URL is set ?

**Comment by piotrgrundas** [comment]
Closing since there is no response back.
If u did not set the env variable then the #233 might resolved ur issue.

**Comment by zatin009** [comment]
@piotrgrundas , Could you tell me which file name we should place the   **BACKEND_URL='http://127.0.0.1:8000/`** ?

**Comment by heiqs** [comment]
Start the app with:

BACKEND_URL='http://127.0.0.1:8000/ npm start
