### ISSUE TITLE
Selecting the right address for checkout steps

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-storefront#241]
### Steps to reproduce the problem
1. Add a product to bag and go to checkout as an authenticated user.
2. Fill the shipping address (note that at this point this form is empty, while we might have the default address assigned to the user) and select option `Use as Billing Address`.
![image](https://user-images.githubusercontent.com/5421321/52358610-99e57e00-2a38-11e9-96af-c2a0e6aabad7.png)
3. Continue to the billing address step. Instead of the address from the first step, there is a different address which is assigned to my account.
![image](https://user-images.githubusercontent.com/5421321/52358713-cc8f7680-2a38-11e9-9d93-f9c29993ed0b.png)

First we should make sure that `Use as billing` checkbox actually works properly. Second, user should be able to use his default addresses that are already saved in his account. I'm not sure about the UI/UX of this - e.g. in the old storefront we show a selection of existing addresses or a form to add new address. Don't know how do we want to approach it here (question to @pwgryglak, but maybe we already have that on mockups).

**Comment by pwgryglak** [comment]
@piotrgrundas 
We'll be moving "use this as billing address" to billing address section. We'll rename it to same as shipping. It should fill up the form.
Updates will be on Figma.
