### ISSUE TITLE
Implement order confirmation page

### ISSUE THREAD

**Issue by mridang** [mirumee/saleor-storefront#252]
### What I'm trying to achieve
There doesn't seem to be an order-confirmation page. After purchasing, it seems to place the order but redirects me back to the home page.

### Describe a proposed solution
Implementation.

**Comment by piotrgrundas** [comment]
Well You have a review page.
![image](https://user-images.githubusercontent.com/5078402/52548562-b84bd080-2dce-11e9-91e2-0ad01ba6980f.png)

**Comment by piotrgrundas** [comment]
Estimated delivery is not implemented yet thus will be added to that screen later on.
