### ISSUE TITLE
Ability to apply a discount code

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-storefront#257]
Add the ability to apply a discount code in the shopping cart view:

![image](https://user-images.githubusercontent.com/5421321/52624972-40ee6d80-2eb0-11e9-887a-a600ed8cef54.png)

The code should be stored in the local cart (local storage) to support offline mode and guest checkouts. There should be also a way to save the code in API.

Blocker: from what I see there is no mutation yet to add a discount code to a checkout instance in the API. We will have to add it first in the backend.

**Comment by maarcingebala** [comment]
Mutation `checkoutAddPromoCode` allows to provide a discount code to use in checkout.

**Comment by giovannipiccinelli** [comment]
Hello! I have a live shop using your framework running at https://www.storitalia.com I would like to know wether this feature will be added to the project anytime soon. Thanks!

**Comment by giovannipiccinelli** [comment]
@maarcingebala 
Any update on this issue?
Thanks

**Comment by orzechdev** [comment]
@giovannipiccinelli Now you can add discount code in checkout page
