### ISSUE TITLE
Order history view

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-storefront#259]
Implement the Order History view which will list all orders of a user. This view will be available only for authenticated users within their user account section. Query to fetch the data according to

Query to fetch the data as on the mockup:

```graphql
{
  me {
    orders(first: $first) {
      edges {
        node {
          id
          number
          lines {
            id
            thumbnailUrl
          }
          created
          total {
            gross {
              localized
            }
          }
          statusDisplay
        }
      }
    }
  }
}
```

Blocker: If I'm correct there is no way to navigate from an order line to the product details page. Line item holds some information about the product, but I don't know if those fields will allow constructing the product details URL. We should remember that product might be not available (might have been removed from the database) - in that case, the navigation won't be possible.

**Comment by bogdal** [comment]
We already implemented this 🎉
