### ISSUE TITLE
Network error: Preflight response is not successful

### ISSUE THREAD

**Issue by officerebel** [mirumee/saleor-storefront#266]
### What I'm trying to achieve
Load the backend and the frontend

### Steps to reproduce the problem
1. Install and load the frontend app
2. Install and run te backend app

### What I expected to happen
See images on port 3000

### Screenshots

<img width="1284" alt="schermafbeelding 2019-02-20 om 13 19 07" src="https://user-images.githubusercontent.com/7673074/53091436-3b2d0380-3512-11e9-9fbe-ff6bf87aad43.png">

**System information**
Operating system: 
osx
Browser:
safari

**Comment by piotrgrundas** [comment]
@officerebel please check if tips from #206 will resolve ur problems.

**Comment by officerebel** [comment]
No Tried them Did not work

**Comment by 2mwayungi** [comment]
I  got same error 

Operating system:
ubuntu

**Comment by piotrgrundas** [comment]
To sum up, did u guys set properly:
* `ALLOWED_HOSTS=[*]` in the backend settings or env var in saleor
* `BACKEND_URL='http://127.0.0.1:8000/'` in env var in storefront

If yes could you pass some more info about the error?

**Comment by officerebel** [comment]
Entrypoint app = js/app.js js/app.js.map
[0] multi (webpack)-dev-server/client?http://localhost:3000 ./src/index.tsx 40 bytes {app} [built]
[./node_modules/apollo-cache-inmemory/lib/index.js] 272 bytes {app} [built]
[./node_modules/apollo-cache-persist/bundle.umd.js] 18.3 KiB {app} [built]
[./node_modules/apollo-client/index.js] 387 bytes {app} [built]
[./node_modules/apollo-link-batch-http/lib/index.js] 66 bytes {app} [built]
[./node_modules/apollo-link-retry/lib/index.js] 62 bytes {app} [built]
[./node_modules/apollo-link/lib/index.js] 220 bytes {app} [built]
[./node_modules/history/es/index.js] 460 bytes {app} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {app} [built]
[./node_modules/react-apollo/react-apollo.browser.umd.js] 64.3 KiB {app} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {app} [built]
[./node_modules/react-router-dom/es/index.js] 1010 bytes {app} [built]
[./node_modules/react/index.js] 190 bytes {app} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:3000] (webpack)-dev-server/client?http://localhost:3000 7.78 KiB {app} [built]
[./src/index.tsx] 4.39 KiB {app} [built]
    + 573 hidden modules

WARNING in EnvironmentPlugin - BACKEND_URL environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 416 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
Child webapp-webpack-plugin:
     1 asset
    Entrypoint favicon.png = faf75404bf59c996c1b5
    [./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"/Users/timvogt/Software_projects/Frontend/saleor-storefront/node_modules/.cache/webapp-webpack-plugin"}!./node_modules/webapp-webpack-plugin/src/loader.js?{"prefix":"images/favicons/","options":{"appName":"Saleor","appDescription":"Storefront for the Saleor e-commerce platform","display":"standalone","developerURL":null,"background":"#ddd","theme_color":"#333","version":"0.2.0","developerName":"Mirumee"},"path":"/"}!./src/images/favicon.png] 1.06 MiB {favicon.png} [built]
ℹ ｢wdm｣: Compiled with warnings.

**Comment by piotrgrundas** [comment]
`WARNING in EnvironmentPlugin - BACKEND_URL environment variable is undefined.` set it

**Comment by officerebel** [comment]
What does it mean? Post backend url in the backend or frontend ?

**Comment by 2mwayungi** [comment]
@piotrgrundas Thank you solved.
@officerebel  saleor  inside settings.py  add ALLOWED_HOSTS=[*]
       saleorfront webpack.config.js replace BACKEND_URL to  'http://127.0.0.1:8000/'
