### ISSUE TITLE
storybook not working

### ISSUE THREAD

**Issue by raitalharehman** [mirumee/saleor-storefront#272]
### What I'm trying to achieve
I am trying to run storybook

### Steps to reproduce the problem
1. yarn storybook

### Error Log
```ERROR in ./src/storybook/stories/components.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: D:/Workspace/saleor-storefront-0.4.0/src/storybook/stories/components.js: Unexpected token (14:4)

  12 | storiesOf("Components", module)
  13 |   .add('Button', () => (
> 14 |     <div className="button-section">
     |     ^
  15 |       <Button>Sample Button</Button>
  16 |       <Button secondary>Secondary Button</Button>
  17 |     </div>

```
**System information**
Operating system: Windows 10
Browser: chrome
Node: v11.10.0

**Comment by hoflish** [comment]
Hi @raitalharehman, 

I think you got the error due to missing babel config file, try to create a `.babelrc` file inside `storybook` folder with the following content
 ```javascript
{
    "presets": ["react"]
}
```

**Comment by raitalharehman** [comment]
Hi @hoflish 

Thank you very much it works

**Comment by timuric** [comment]
@hoflish do you know if it is deliberately missing?
