### ISSUE TITLE
CORS policy error

### ISSUE THREAD

**Issue by chuanman2707** [mirumee/saleor-storefront#285]
### What I'm trying to achieve
I downloaded both the saleor and saleor-storefront, setup well with the saleor.
but when it come to storefront, there are alot of error occured while i'm trying to setup.
### Steps to reproduce the problem
1.  For the saleor django, i set `ALLOWED_HOST="*" in setting.py`.
2.  For saleor-frontend, i use dotenv-webpack and create .env file and paste `BACKEND_URL='http://127.0.0.1:8000/'`

### What I expected to happen
How do i resolve this error? , someone please help me.
### Screenshots

![image](https://user-images.githubusercontent.com/29907469/55139434-5837a080-5168-11e9-849f-e17770ea8f35.png)

**System information**
Operating system: Windows 10 pro.
Browser: Chrome

**Comment by bogdandjukic** [comment]
Have you tired adding a specific host to ALLOWED_HOST instead of * ?
Something more like 'localhost, 127.0.0.1'

**Comment by krzysztofwolski** [comment]
Have same issue. Allowed hosts change does not help.

**Comment by krzysztofwolski** [comment]
![Screenshot 2019-03-28 at 11 59 18](https://user-images.githubusercontent.com/5188636/55154862-2c132400-5156-11e9-96e4-126b3fc2de8f.png)

**Comment by chuanman2707** [comment]
> Have you tired adding a specific host to ALLOWED_HOST instead of * ?
> Something more like 'localhost, 127.0.0.1'
I just follow the same method #206 what the dev told me to do. tried to add `localhost, 127.0.0.1` but still same thing happen.
