### ISSUE TITLE
Wrong item counter

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor-storefront#286]
### Steps to reproduce the problem
1. Add 2 pieces of one product
2. Open cart tab

### What I expected to happen
Same counter both on cart icon and 'items counter' in sidebar

### Screenshots
Same cart:
![Screenshot 2019-03-27 at 16 45 44](https://user-images.githubusercontent.com/5188636/55090737-e6038500-50af-11e9-8fc9-6aef06d0e5e6.png)
![Screenshot 2019-03-27 at 16 45 33](https://user-images.githubusercontent.com/5188636/55090738-e6038500-50af-11e9-9d81-070895009009.png)

**System information**
Operating system: OSX
Browser: Chrome

**Comment by chuanman2707** [comment]
i think you misunderstand the concept here, you are buying 1 item with quantity of 2, not 2 items.

**Comment by krzysztofwolski** [comment]
I've discussed this with the author of design. Both counters should be the same.
