### ISSUE TITLE
Add server side rendering

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor-storefront#296]
Server-side rendering is crucial for page visibility for search engines. I think there was a proposition to use Gatsby, but @patrys can tell more on what we've agreed on.

**Comment by maarcingebala** [comment]
@mateuszkula Is already working on it.

**Comment by adrienshen** [comment]
Hello, would this project https://nextjs.org help with Server-side rendering?

**Comment by maarcingebala** [comment]
The problem with `next.js` or a `Gatsby` is that they might require rewriting the structure of our app, which we'd like to avoid. There are also tools like [Rendertron](https://github.com/GoogleChrome/rendertron) which can be used as a proxy for accessing prerendered content by search bots, and this solution may not require changes to our app. So to summarize, we haven't yet decided which way to go and we're evaluating these various solutions.

**Comment by bogdal** [comment]
We have decided not to integrate Gatsby or other tools now. [Rendertron](https://github.com/GoogleChrome/rendertron) is a great alternative and pretty much sufficient for our needs.

**Comment by petedermott** [comment]
Are there any guides on how to set this up? Are there going to be any changes made to the storefront to implement this? 

From what I can tell we need to run a proxy server in front of the storefront in order to redirect any traffic from search engines to either a separate Rendertron instance or to something like prerender.io, is that correct?

**Comment by bogdal** [comment]
@petedermott You are right. You need to set up a proxy on your own side and redirect selected requests (from bots) to the rendertron/prerender.io instance. We don't plan to make any changes to the storefront.

**Comment by cr0nex** [comment]
I intend to look into paring gatsby + django-side saleor, what do you think the problems might be? (in terms of "rewriting the structure of our app"?)

**Comment by maarcingebala** [comment]
@cr0nex I don't see any particular problems now but there are a few things to consider.

First, you would need to build a source plugin for Gatsby that will fetch products, categories, etc. from our API. This is easy as it's just reading some data and generating static product pages/listings based on this data. I think this is the easiest part.

What I'm not so sure about (but I also have elementary experience with Gatsby) is how to build the checkout that will use our API. Checkout is a bit more dynamic and requires calling a few mutations in Saleor API. If I'm correct, you can embed dynamic React components in Gatsby, and maybe this would be the solution here.

I would love to see some Saleor plugins for Gatsby one day. But unfortunately, it's not something that's on our roadmap now; we're more focused on developing this storefront.

**Comment by patrys** [comment]
@maarcingebala Gatsby renders a static HTML version but it also runs the React app in the browser so you can mix the two. The potential problem I see with Gatsby is that we need to create all of the pages up-front which will become a challenge if you have 100k+ products and change your prices often. For large vendors, Next.js could be a better match even if it requires additional infrastructure to run.

**Comment by cr0nex** [comment]
@patrys from what I understand, with gatsby its also possible to tie specific parts of the application directly to graphql queries. E.g price and availability will not be statically generated, but queried each time. I still think static site generation is rather niche and comes with a lot of tradeoffs, which make it unsuitable as a one-stop general solution when building a storefront.

However, it may be adequate for our vision, so I will report on the _gastby + saleor_ progress in the following months.
