### ISSUE TITLE
Use storefront in production

### ISSUE THREAD

**Issue by phamvietloi** [mirumee/saleor-storefront#300]
I want to use the saleor-storefront in production.
I deployed Saleor on Ubuntu VPS, use Gunicorn and Nginx suscessfully
Then I follow the instruction to install PWA Storefront on the same VPS, set BACKEND_URL variable to http://localhost:8000 as instruction but just blank page.
Thanks so much

**Comment by NyanKiyoshi** [comment]
Hi,

Could you provide the errors shown in your browser console ?

**Comment by pojebunny** [comment]
Hi.
Same thing, but I'm on Arch.
I've had to change the BACKEND_URL to external address (for ex. http://mydomain.com:8000/) for the storefront to stop throwing 404 errors.
Base is deployed through docker / docker-compose.

![image](https://user-images.githubusercontent.com/22904165/57855877-ff8d9700-77eb-11e9-9639-bbbd0df263c7.png)

**Comment by NyanKiyoshi** [comment]
@pojebunny it says it's building "wait until bundle finished", have tried to wait some time for it to get the build ready in the browser?

**Comment by pojebunny** [comment]
Yes. The webpack server doesn't push ANY data until the build is finished. Meaning, the page is loading and the browser doesn't display anything before receiving a confirmation response.

You can see the build time on first screen (loooong green line at the beginning)

**Comment by NyanKiyoshi** [comment]
Shouldn't this be normal? The `npm start` command is starting a development server and thus watches for changes and compiles on the go.

If you want to get static files e.g. for production, try `npm run build`.

**Comment by pojebunny** [comment]
I want to run whole dev environment on a dev server (In virtual machine), because that's where I can run the docker image.
Should I separate them like this?:
-Virtual Machine with backend hosted from docker and ports forwarded to host.
-Host machine with webpack dev mode hosted PWA frontend.

**Comment by NyanKiyoshi** [comment]
The point of docker is to do the job of a virtual machine... well to be isolated from the host machine.
But yes, what you are suggesting should work if properly configured.

**Comment by pojebunny** [comment]
Oh. Yeah.
By Host I mean my desktop environment with dev tools.
VM is my testing Server machine and docker (with many docker services running on it)

**Comment by pojebunny** [comment]
@NyanKiyoshi 
With the PWA frontend launched on localhost Windows machine, the UI loads, but seems to be unable to receive data from the backend.
![image](https://user-images.githubusercontent.com/22904165/57879703-5b244880-781d-11e9-8a53-cdfb3184db65.png)

Arch server: VirtualBox with port 8000 forwarded to Main machine. Saleor default/unmodified image running from docker with some products added through dashboard.
Windows host: set BACKEND_URL: http://127.0.0.1:8000/ and unmodified saleor-storefront npm install'ed and start'ed.

**Comment by pojebunny** [comment]
Aight. Everything works.
THANK YOU VERY MUCH <3

**Comment by pojebunny** [comment]
![image](https://user-images.githubusercontent.com/22904165/57921817-987cea80-789e-11e9-8a82-e464773f605d.png)

Well, I woke up and that's what I'm greeted by after booting the computer and launching everything like I did yesterday...

@NyanKiyoshi

**Comment by yannterzi** [comment]
I case of Production, you should use nginx with your PWA production build ( made with npm run build ).

Also, PWA redirect to / in case of production ( see https://github.com/mirumee/saleor-storefront/blob/2a9d4dad8f96dd5c1f2d98b72cb4a695ebed5082/src/constants.ts#L3 )
So if you need to call a different API URI, you could edit constants.ts for your use case.

**Comment by giovannipiccinelli** [comment]
On localhost it works well, however I have spent several hours trying to make this work on an external server using heroku. I have not succeeded. Can someone share a step by step procedure to make this project usable in production with heroku?

**Comment by appleyuchi** [comment]
> On localhost it works well, however I have spent several hours trying to make this work on an external server using heroku. I have not succeeded. Can someone share a step by step procedure to make this project usable in production with heroku?

could you leave your chatting tool number?
I want to discuss with someone on server deployment if possible.

**Comment by rjusher** [comment]
> 
> 
> On localhost it works well, however I have spent several hours trying to make this work on an external server using heroku. I have not succeeded. Can someone share a step by step procedure to make this project usable in production with heroku?

I am also finding issues deploying storefront to heroku, I keep getting ECONNREFUSED error when I try to push the proyect to heroku.
