### ISSUE TITLE
Cart clear is not working as supposed

### ISSUE THREAD

**Issue by bogdandjukic** [mirumee/saleor-storefront#301]
### What I'm trying to achieve
When using cartContext clear functionality it clears the cart by emptying the lines in the state and by removing the cart from localStorage. It doesn't remove the checkout or the products from the checkout (the user is logged in). That leads to products appearing back in the cart on page refresh.

### Steps to reproduce the problem
1. Log in
2. Add products to cart
3. Call a cart clear function (from cartContext).
4. Refresh page

### What I expected to happen

The question is, what is the expected behavior? Should we remove the checkout completely, or just remove the products (lines) from it by iterating thru them?

### Screenshots

**System information**
Operating system: Mac OS 10.14.4
Browser: Chrome 73

**Comment by maarcingebala** [comment]
Needs to be verified if it's still valid.

**Comment by orzechdev** [comment]
We have created new SDK, which makes issue outdated. Please make another issues if there are missing methods worth to implement in SDK or methods from there don't work.
