### ISSUE TITLE
Use JSON fields for rendering rich-text content

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-storefront#305]
As we have recently switched to [Draftail](https://draftail.org) editor in Dashboard 2.0, the rich-text content is now saved as JSON. We should use those fields for rendering content such as product description or static pages content.

Queries to fetch JSON content for products description:
```
product {
  descriptionJson
}
```

Pages content:
```
page {
  contentJson
}
```

I'm not sure about the best way to transform Draftail's JSON format to something more "renderable" but apparently, there are some tools to do that, we'd just have to pick one (the most popular/maintained): https://project-awesome.org/nikgraf/awesome-draft-js

**Comment by patrys** [comment]
There's https://github.com/sstur/draft-js-utils which includes `draft-js-export-html`.
