### ISSUE TITLE
Deploy to Heroku Broken

### ISSUE THREAD

**Issue by johndangerstorey** [mirumee/saleor-storefront#309]
### What I'm trying to achieve
…
Do a one step deploy to heroku via the button on the readme of github.

### Steps to reproduce the problem
1. Visit github readme, sign into Heroku, click "Deploy to Heroku"
2. Redirected page at Heroku.com `https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fheroku.com%2F&template=https%3A%2F%2Fheroku.com%2F` which loads forever.
3. Open up dev tools, see errors in console
![image](https://user-images.githubusercontent.com/2646310/56871112-36d80780-69e7-11e9-8201-a6c08aba9974.png)
4.  Visit one of the error URLs to `https://particleboard.heroku.com/github/account/integration/` and see this error `{"errors":[{"detail":"Page not found"}]}`

### What I expected to happen
Heroku opens and starts installation and packages to get this bad boy up and running!
…

### Screenshots
![image](https://user-images.githubusercontent.com/2646310/56871134-8cacaf80-69e7-11e9-84db-fd3377e53b67.png)

**System information**
Operating system:  MacOS Mojave
Browser: Brave

**Comment by NyanKiyoshi** [comment]
Hey!

Can you go to the network tab, refresh the page, and show us the network tab's content.
Seems like you did not properly configure the `ENDPOINT_URL` environment variable.

**Comment by NyanKiyoshi** [comment]
Note the last URL is saying `undefined` multiple times. I can't help with heroku issues, hopefully somebody else can.

**Comment by biomassives** [comment]
So this will get you a little futher forward.. structure your heroku app launch link as so: https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Fmirumee%2Fsaleor-storefront   This will install the app, but url /graphql remains missing..  I'm looking in to how to ensure that Heroku launches a graphql server in the place specified..

**Comment by biomassives** [comment]
found the following in the generated js payload.. {if(!e.cache)throw new Error("In order to persist your Apollo Cache, you need to pass in a cache. Please see https://www.apollographql.com/docs/react/basics/caching.html for our default InMemoryCache.");if(!e.storage)throw new Error("In order to persist your Apollo Cache, you need to pass in an underlying storage provider. Please see https://github.com/apollographql/apollo-cache-persist#storage-providers")

**Comment by biomassives** [comment]
this resource seems to hold some promise.> https://github.com/apollographql/apollo-client/issues/3639
   I have been looking at the core saleor app as a reference as well

**Comment by biomassives** [comment]
I made a pull request for my update to the apollo setup, which fixed the heroku launch
the app I deployed is here : https://tinyfoodui1.herokuapp.com/
