### ISSUE TITLE
Missing login button on mobile view

### ISSUE THREAD

**Issue by mateuszkula** [mirumee/saleor-storefront#336]
Mobile view is missing login option:

Current implementation:
![zrzut 2019-05-24 14 59 52](https://user-images.githubusercontent.com/30259869/58329510-01330c80-7e35-11e9-9065-5c425e34551a.png)
Design:
![Zrzut ekranu 2019-05-24 o 15 00 42](https://user-images.githubusercontent.com/30259869/58329518-07c18400-7e35-11e9-86a1-9762431b256a.png)

**Comment by krzysztofwolski** [comment]
Navigation will be remodeled with new menu design.
