### ISSUE TITLE
Can't Install saleor repostiory

### ISSUE THREAD

**Issue by Dirik94** [mirumee/saleor-storefront#338]
### What I'm trying to achieve
I am trying to install salor repostiory by cloning "git clone git@github.com:mirumee/saleor-storefront.git" in to a terminal and I get: "Cloning into 'saleor-storefront'...
Warning: Permanently added the RSA host key for IP address '140.82.118.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository."

### Steps to reproduce the problem
1. Go to MacOS Mojave 10.14.5 terminal
2. enter "git clone git@github.com:mirumee/saleor-storefront.git"

### What I expected to happen
Get acces to the storefront

### Screenshots

**System information**
Operating system: MacOS Mojave 10.14.5
Browser: Safari

**Comment by NyanKiyoshi** [comment]
Hi

You are using the wrong ssh key for GitHub.

There are two solutions for you:
1. Cloning through HTTP instead of SSH
1. Creating a new SSH key in `~/.ssh/github_rsa and` adding to `~/.ssh/config`:
  ```
Host github.com
  IdentityFile ~/.ssh/github_rsa
```
