### ISSUE TITLE
Checkout caches Total for old products' list

### ISSUE THREAD

**Issue by korycins** [mirumee/saleor-storefront#341]
### What I'm trying to achieve
Receive correct value for Grand Total

### Steps to reproduce the problem
1. Add product to bag
2. Go to the checkout and choose a shipping method
3. Go back to the product list and add another item
4. Go to the checkout -> GRAND TOTAL will show old price (first item + shipping)
5. Refresh the page to recalculate grand total.

### What I expected to happen
Checkout shouldn't cache these data.

**System information**
Operating system: Mac 
Browser: Chrome

**Comment by bogdandjukic** [comment]
On successful add to cart **checkoutContext** should be also updated with **totalPrice**

**Comment by beohoang98** [comment]
https://github.com/mirumee/saleor-storefront/blob/a98138786e9c9560d8f76cd40a0a45f66ca21d7a/src/checkout/queries.ts#L162-L182
Yes, the query should have field **totalPrice** after **subtotalPrice**

**Comment by zzzzasd** [comment]
Any updates on this?
