### ISSUE TITLE
Order details view should use order token instead of ID

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-storefront#358]
### What I'm trying to achieve
I'm trying to view an order after successful checkout.

### Steps to reproduce the problem
1. Go through checkout, pay with dummy payment by selecting "Charged" option.
2. On the "Thank you" page click "Order details"
3. "You don't have permissions" error occurs.

After clicking "Order details" button I'm getting redirected to URL `http://localhost:3000/my-account/order/T3JkZXI6MjE=/` which indicates that an ID is used to fetch the order, but this query actually required admin permissions. To fetch any order without permissions check with have `orderByToken` query which should be used here instead. 

The token can be obtained after creating an order:

```
mutation {
  checkoutComplete(checkoutId: "") {
    order {
      token
    }
  }
}
```

### Screenshots
![image](https://user-images.githubusercontent.com/5421321/59344623-c2df8d80-8d0e-11e9-9718-fcef106c28d5.png)

**Comment by bogdal** [comment]
It's already done 🎉
