### ISSUE TITLE
Error in connecting to backend

### ISSUE THREAD

**Issue by heiqs** [mirumee/saleor-storefront#364]
### What I'm trying to achieve
I am trying to run storefront based documentation
### Steps to reproduce the problem
1. install saleor backend
2. populate database
3. run saleor front

### What I expected to happen
-
### Screenshots
Following error:

Uncaught (in promise) TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.

![image](https://user-images.githubusercontent.com/3305298/59561590-93889380-9022-11e9-860e-80cc3b788297.png)

**System information**
Operating system: Ubuntu 18.04
Browser: Chrome, Firefox

**Comment by jwm0** [comment]
Have you set the `BACKEND_URL` env to point to the saloer backend (by default it's on port 8000)? It looks like your app loads but it cannot get the items because you're using wrong port for API. Errors considering service worker wouldn't have any real effect on the look of the app itself - it's only data caching between sessions.

**Comment by NyanKiyoshi** [comment]
If it doesn't fix your issue, please attach a screenshot of the network tab of the inspector.

**Comment by heiqs** [comment]
This is the command for running front: `BACKEND_URL=http://127.0.0.1:8000 npm start`

Following are console and network tabs:

![console](https://user-images.githubusercontent.com/3305298/59716543-71effd80-9216-11e9-8ced-1179ec853cff.png)

![network](https://user-images.githubusercontent.com/3305298/59716544-72889400-9216-11e9-9c2e-ebbdf3e29879.png)

**Comment by heiqs** [comment]
The collection was empty. If I add a collection, then I don't see the above error. I get the following one: 

![network_collection](https://user-images.githubusercontent.com/3305298/59717845-1f641080-9219-11e9-8df8-e7545be60f02.png)
![no_product_in_collection](https://user-images.githubusercontent.com/3305298/59717847-1ffca700-9219-11e9-8ab9-a5181b7e19d6.png)

**Comment by heiqs** [comment]
Ok. I see no error when I use Chrome. Seems that the error is in connection with the bowser (here Firefox). Any Idea why?

**Comment by jwm0** [comment]
Did you open the new storefront before populating the DB? This looks like a rehydration issue. Try clearing cache and refresh.

**Comment by heiqs** [comment]
You are right. It was the caching problem. Thanks.
