### ISSUE TITLE
Endpoints are wrong

### ISSUE THREAD

**Issue by heiqs** [mirumee/saleor-storefront#374]
I see some problems with endpoints:

1. Clicking on my account redirects me to /my_account which is wrong. It should be /account.

2. When I finish an order, I can see the details but when I want to click on "Go back to Order History", the endpoint is "my-account/order/history/" which is wrong. The correct endpoint is /order-history.

3. Even after having some orders, and then orders are shown in the dashboard, they are not present in the order history of the Storefront. And it shows an empty page.

**Comment by bogdal** [comment]
Thank you for the detailed info. All your things have been fixed 👍
