### ISSUE TITLE
WARNING in EnvironmentPlugin - BACKEND_URL environment variable is undefined.

### ISSUE THREAD

**Issue by zatin009** [mirumee/saleor-storefront#376]
![image](https://user-images.githubusercontent.com/40449637/60005737-4bf4ae00-9699-11e9-851e-45e9cf82cfa1.png)

**Comment by zatin009** [comment]
![image](https://user-images.githubusercontent.com/40449637/60005800-67f84f80-9699-11e9-8ec1-bd9f4f790cb0.png)

**Comment by mateuszkula** [comment]
This is intended behavoiur.

Accordingly to storefront README file:

> To run the storefront, you have to set the BACKEND_URL environment to point to the Saleor instance. If you are running Saleor locally with the default settings, set BACKEND_URL to: http://localhost:8000/.

**Comment by zatin009** [comment]
@mateuszkula Howdy dear, May I know which file name or directory path I should place the BACKEND_URL = "http://localhost:8000/"

**Comment by mateuszkula** [comment]
@zatin009 You do not set it in file. Please follow latest comment from @korycins 
https://spectrum.chat/saleor/general/hello-team-may-i-know-how-to-install-the-pwa-store-front-in-local-computer~6bb6d8ad-0560-48f9-912a-9822ebd50adf

**Comment by zatin009** [comment]
@mateuszkula Thanks you
