### ISSUE TITLE
 Entrypoint undefined = index.html

### ISSUE THREAD

**Issue by desfacs-techy** [mirumee/saleor-storefront#388]
### What I'm trying to achieve
Running the application

### Steps to reproduce the problem
1. RUN npm start

### What I expected to happen
Should run the app successfully

### Screenshots
![Screenshot from 2019-06-29 19-23-35](https://user-images.githubusercontent.com/51677485/60385125-7e404a00-9aa3-11e9-83f5-42cb1d62deb4.png)
![Screenshot from 2019-06-29 19-27-49](https://user-images.githubusercontent.com/51677485/60385185-0cb4cb80-9aa4-11e9-96af-c2930a48721c.png)

**System information**
Operating system: Ubuntu 18.04
Browser: Firefox
Node Version: v10.16.0

**Comment by bogdal** [comment]
Hello @desfacs-techy. Have you properly set the env variable `BACKEND_URL`? It should point to the working Saleor instance.

**Comment by desfacs-techy** [comment]
@bogdal ,
Thanks for quick response.

For just testing I was using https://demo.getsaleor.com/graphql/ as graphql endpoint.
Is this is the correct way?

**Comment by bogdal** [comment]
@desfacs-techy The env variable should point to the Saleor instance, not to the graphql endpoint.
Try this one:
```
BACKEND_URL=https://demo.getsaleor.com
```

**Comment by desfacs-techy** [comment]
@bogdal ,

Thanks a lot Man. It's working.
