### ISSUE TITLE
Invalid handling of checkouts without shipping

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-storefront#400]
### What I'm trying to achieve
Order products that have no shipping.

### Steps to reproduce the problem
1. Add a product without shipping (books, digital, etc.)
2. Try to complete the checkout
3. It will fail

### What I expected to happen
1. Not to be able to add a shipping address
1. Not to be able to select a shipping method

### Notes
This is related and blocked by https://github.com/mirumee/saleor/issues/4321.

**Comment by amazedge** [comment]
Team,Any fix planned on this issue?  Believe related issue (mirumee/saleor#4321)closed already.
