### ISSUE TITLE
Login before proceeding to checkout fails

### ISSUE THREAD

**Issue by amazedge** [mirumee/saleor-storefront#414]
**Steps to reproduce the problem:**

- As a guest customer add some items to bag and go to checkout.
- Before entering checkout, user is asked to log in or continue as guest. Trying to login on this page does NOT work  and does NOT redirect to checkout/shipping-address/.

**Comment by yannterzi** [comment]
Up, same issue with my storefront
Also, if i'm logged before checkout, the store ask to log in or continue as guest too.
On my side, this issue happen around 19 july, after merging this PR: https://github.com/mirumee/saleor-storefront/pull/409

**Comment by bogdal** [comment]
Thank you for reporting this. The issue has been resolved.
