### ISSUE TITLE
Share a link for a first time user

### ISSUE THREAD

**Issue by ridiaz** [mirumee/saleor-storefront#419]
### What I'm trying to achieve
Try to share a link for a product

### Steps to reproduce the problem
1. deploy to hosting (ex. firebase hosting)
2. share a link of a product ex. https://kashima-app.firebaseapp.com/product/kashima-pastillas-de-freno-delanteras-hyundai-accent-1400cc-2010/437/
3. open in a browser who never got the app before
4. Got a 404

### What I expected to happen
Open the app with the product shared

### Screenshots

![image](https://user-images.githubusercontent.com/1059914/61791317-447f0c80-addf-11e9-81fa-6f6f23494e79.png)
![image](https://user-images.githubusercontent.com/1059914/61791342-582a7300-addf-11e9-808c-32f211c7d7dd.png)

**System information**
Operating system: 
Browser:

**Comment by bogdal** [comment]
Hello @ridiaz. It's a matter of configuring your hosting. You need to use Firebase's [rewrites](https://firebase.google.com/docs/hosting/full-config#rewrites) to support push-state URLs.
