### ISSUE TITLE
Issue when running 'npm i'

### ISSUE THREAD

**Issue by likewhoa** [mirumee/saleor-storefront#436]
### What I'm trying to achieve
install the npm dependencies

### Steps to reproduce the problem
1. npm i

### Screenshots
../src/binding.cpp:350:42:   required from here
../../nan/nan.h:2378:3: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 2378 |   recv->Set(name, GetFunction(tpl).ToLocalChecked());
      |   ^~~~
In file included from /home/wster/.node-gyp/12.9.0/include/node/v8-internal.h:14,
                 from /home/wster/.node-gyp/12.9.0/include/node/v8.h:25,
                 from /home/wster/.node-gyp/12.9.0/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/binding.cpp:1:
/home/wster/.node-gyp/12.9.0/include/node/v8.h:3372:22: note: declared here
 3372 |                 bool Set(Local<Value> key, Local<Value> value));
      |                      ^~~
/home/wster/.node-gyp/12.9.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
make: *** [binding.target.mk:125: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/wster/.work/saleor-pwa/saleor-storefront-0.6.0/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/wster/.work/saleor-pwa/saleor-storefront-0.6.0/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.0.21-gentoo
gyp ERR! command "/usr/bin/node" "/home/wster/.work/saleor-pwa/saleor-storefront-0.6.0/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/wster/.work/saleor-pwa/saleor-storefront-0.6.0/node_modules/node-sass
gyp ERR! node -v v12.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN @storybook/addon-options@3.4.11 requires a peer of @storybook/addons@^3.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-prettier@2.10.0 requires a peer of eslint@>=3.14.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-prettier@2.7.0 requires a peer of prettier@>= 0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-css-transition-group@15.6.2 requires a peer of react@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-alert@5.5.0 requires a peer of react-transition-group@^2.5.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**System information**
Operating system: Linux
Browser: Chromium

**Comment by NyanKiyoshi** [comment]
@likewhoa feel free to open a pull request 👍

**Comment by likewhoa** [comment]
> @likewhoa feel free to open a pull request +1

see #439
