### ISSUE TITLE
The linguijs translation does not work

### ISSUE THREAD

**Issue by ryan-zheng0312** [mirumee/saleor-storefront#446]
### What I'm trying to achieve
…
I want to use the linguijs <Trans> macro to get translations
### Steps to reproduce the problem
1. Configure as what is said here from linguijs typescript configuration
https://lingui.js.org/guides/typescript.html

2Add any <Trans>Component for some text
3.run npm start. 

### What I expected to happen
…
I would expect that what i have configured in the translation *.po file would get loaded into frontend

### Screenshots

![image](https://user-images.githubusercontent.com/5105956/64405379-37606900-d07f-11e9-8a35-1a8389e6965c.png)

I checked that in the output from Babel. React.createElement(macro_1.Trans,xxxxx) is used. But in the output js,there is no import from "@lingui/react" since the Trans component comes from @lingui/react module. So has anyone tested the lingui configuration with typescript&babel? Looks like it's not working.  Thankss a lot.

**System information**
Operating system:Ubuntu 
Browser:Chrome

**Comment by yannterzi** [comment]
Hi,

You could take a look at this Linguijs issue:
https://github.com/lingui/js-lingui/issues/473

**Comment by nogrethumphrey** [comment]
> Hi,
> 
> You could take a look at this Linguijs issue:
> [lingui/js-lingui#473](https://github.com/lingui/js-lingui/issues/473)

Hi,The comment there  was made by me. Babel does not support export interface.  Only babel is not enough.
