### ISSUE TITLE
Refreshing Page - Basic Issue

### ISSUE THREAD

**Issue by giovannipiccinelli** [mirumee/saleor-storefront#469]
I am running my  shop at the following url https://www.storitalia.com I have a problem  when refreshing the page on a url  different from the home page url.
…

### Steps to reproduce the problem
1.  Go to https://www.storitalia.com
2. Navigate to any route on the home page(ie. >  Glasses)
3. Refresh the page (Command  + R)

### What I expected to happen
I  expect to see  the same  page with new data if database has  changed but instead the page just fails.

### Screenshots
<img width="1255" alt="Screen Shot 2019-09-19 at 7 08 07 PM" src="https://user-images.githubusercontent.com/7911077/65265283-dae65a80-db10-11e9-8228-2d22a619486a.png">
<img width="1255" alt="Screen Shot 2019-09-19 at 7 07 59 PM" src="https://user-images.githubusercontent.com/7911077/65265284-db7ef100-db10-11e9-96e1-afafde2fe4b5.png">

**System information**
Operating system: Deployed on Heroku Server
Browser: Google Chrome

**Comment by bogdal** [comment]
@giovannipiccinelli It's a matter of configuring your buildpacks. You need to set [custom routes](https://github.com/heroku/heroku-buildpack-static#custom-routes) to pass all request to the `index.html` file (support push-state URLs).

**Comment by giovannipiccinelli** [comment]
Hi Bogdal, thanks for your quick response. Can you be more specific on the file and settings I need to modify? I am almost 100% new to react.
This is an amazing project by the way!!

**Comment by bogdal** [comment]
@giovannipiccinelli Please add the `routes` section to your `<root>/static.json` file:
```
{
  "root": "dist/",
  "https_only": true,
  "routes": {
    "/**": "index.html"
  }
}
```

**Comment by giovannipiccinelli** [comment]
worked, thanks!
