### ISSUE TITLE
NPM START Hangs in ubuntu: Wait Until Bundle Finished

### ISSUE THREAD

**Issue by AbdulWaheedPasha** [mirumee/saleor-storefront#470]
### What I'm trying to achieve
…
NPM START Hangs in ubuntu: Wait Until Bundle Finished
### Steps to reproduce the problem
after Runing  npm i and npm start 
when i browse http://localhost:3000/
it get stuck to 
i ｢wdm｣: wait until bundle finished:
in the terminal.
and this happen in ubuntu, amazon linux and lubuntu.
But it works fine in MAC OS.

### What I expected to happen
…
Saleor PWA should run in the browser at http://localhost:3000/

### Screenshots

<img width="1139" alt="Screenshot 2019-09-20 at 9 43 36 AM" src="https://user-images.githubusercontent.com/15060608/65299133-d7dc8000-db8b-11e9-841f-b61741cb294a.png">

**System information**
Operating system: ubuntu, Amazon linux and lubuntu 
Browser: google Chrome

**Comment by petrukngantuk** [comment]
You need specific the env variable in the command...

**Comment by osama-usuf** [comment]
The same happens to me, however for me it is usually still compiling in the background. Give it some time and make sure the terminal isn't inactive. It normally takes around 5 minutes to compile on my machine; you'll see a green compiled successfully message if all goes well.
