### ISSUE TITLE
Failure at Checkout -- Can't proceed to "Shipping Method"

### ISSUE THREAD

**Issue by giovannipiccinelli** [mirumee/saleor-storefront#473]
I am trying to move to the second step "Shipping method" in the checkout process. I am unable to move to the next steps, because it looks like there is an error in the request even if no  error  is  shown  in the console on the left.
…

### Steps to reproduce the problem
1. Go to https://www.storitalia.com
2. Add some products to the bag and go to  the checkout.
3. Insert the shipping Address data in the checkout form.
4. Press Continue to  shipping.

### What I expected to happen
Move  to the next checkout step "Shipping Method"

### Screenshots
@bogdal 
![Screen Shot 2019-09-21 at 7 34 38 PM](https://user-images.githubusercontent.com/7911077/65377065-bffa1e80-dca7-11e9-80eb-54e99351b846.png)

**System information**
Operating system: Heroku Server
Browser: Chrome

**Comment by bogdal** [comment]
It seems your backend is not configured correctly. The `checkoutCreate` mutation should return the `checkout` object containing the list of available payments methods, but your mutation throws an exception.

```graphql
{
  "errors": [
    {
      "message": "Expected a value of type \"GatewaysEnum\" but received: BRAINTREE",
      "path": [
        "checkoutCreate",
        "checkout",
        "availablePaymentGateways",
        0
      ]
    }
  ],
  "data": {
    "checkoutCreate": {
      "checkout": {
        "availablePaymentGateways": [
          null
        ]
      }
    }
  }
}
```

**Comment by bogdal** [comment]
Since it's not this project issue, I'm going to close it. Feel free to create a new one if necessary or visit [Saleor's spectrum chat](https://spectrum.chat/saleor).

**Comment by giovannipiccinelli** [comment]
no problem. Thank you very much. I realized it was my fault in setting up the backend for  payments.
