### ISSUE TITLE
Add polifils

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor-storefront#48]

**Comment by maarcingebala** [comment]
@mociepka Is this issue still valid? If yes, then could you provide some more description so we can work on that?

**Comment by mociepka** [comment]
This issue is about adding babel polifils:
https://babeljs.io/docs/en/babel-polyfill#docsNav

**Comment by mahdikhosravi** [comment]
As of Babel 7.4.0, this package has been deprecated in favor of directly including core-js/stable (to polyfill ECMAScript features) and regenerator-runtime/runtime (needed to use transpiled generator functions)

**Comment by mociepka** [comment]
@bogdal did we tested storefront on browsers different that newest Chrome? Maybe we don't even need this polyfils?
