### ISSUE TITLE
pwa.getsaleor.com (saleor and saleor-storefront commit ID)

### ISSUE THREAD

**Issue by aref-mehran** [mirumee/saleor-storefront#481]
hi 
i want to know current pwa.getsaleor.com saleor and saleor-storefront git commit ID? (i think it is not updated with lastest master. i pulled latest version from master but have many bugs. i want to have exactly the same version of pwa.getsaleor.com )

**Comment by bogdal** [comment]
Hi @aref-mehran. Both applications `pwa.getsaleor.com` and `demo.getsaleor.com` are deployed after each new release. The version number and commit ID can be found in the [releases](https://github.com/mirumee/saleor-storefront/releases) section.
