### ISSUE TITLE
<Trans/>, Italian locale and language switcher

### ISSUE THREAD

**Issue by peekeesrl** [mirumee/saleor-storefront#482]
### What I'm trying to achieve
We should add additional locales to the new storefront and implement a language switcher as in Storefront 2.0. In addition, we should retrieve model translations from the backend.

### Describe a proposed solution
1. I have forked the repo and added the Italian locale; I have already started to insert the <Trans/> component to extract the strings.

2. I have already tried the switcher by following #399 advice and it works; _where could we include a standard component for the switcher_? I imagine a dropdown.

3. Finally, I can modify the querysets as per #307  to retrieve the correct translation for the model.

### Feedback
Please let me know what you think. Thanks!

**Comment by bogdal** [comment]
Definitely we need to work on translations and we would love ❤️  to see a PR from you.

As far as the language switcher is concerned we initially thought about page configuration dialog containing language dropdown, but on this step, any dropdown implementation will be well appreciated 👍 

An example:
![language](https://user-images.githubusercontent.com/1451824/65969222-b5d4de80-e464-11e9-929b-07f927886658.png)

**Comment by peekeesrl** [comment]
@bogdal We are starting to work on it today, according to our internal schedule, we should be finishing by the end of next week! 😃

**Comment by TranDinhKhang** [comment]
hello, any news on this guy ? :D

**Comment by peekeesrl** [comment]
Hi @TranDinhKhang , we should be ready by mid-november since we are working in parallel on storefront 1.0 and 2.0.
The switcher is also ready but it is not production ready yet.
We will update here when we have finished!

**Comment by petrukngantuk** [comment]
any trick to hardcode in index.tsx to our locale?

**Comment by jdivins** [comment]
It's planned to be released in some new storefront or demo version? 
Thanks!!

**Comment by giovannipiccinelli** [comment]
@bogdal 

Hi! Is this feature still being under development? Would really love to have this in the next saleor-frontend releases 👍

**Comment by wael-mohamed** [comment]
The team is moving to react-intl
