### ISSUE TITLE
Add Stripe integration

### ISSUE THREAD

**Issue by bogdal** [mirumee/saleor-storefront#485]
### What I'm trying to achieve

I want to be able to pay by credit card using `Stripe` payment method. 

Saleor already supports this gateway and we can configure it via the [plugin system](https://docs.saleor.io/docs/next/dashboard/configuration/plugins/).

### Describe a proposed solution

We should use https://github.com/stripe/react-stripe-elements components.

**Comment by jpc2350** [comment]
Hi @bogdal, 

I really need this stripe integration working ASAP, as both the old and new storefronts are no longer supporting either (I'm not clear what changes I need to make -- following the documentation to add it to the old storefront, I still get errors) and I have a site that needs to go live over the course of the next few days. Any help, or initial work you can provide on this would be really useful for me.

Thanks

**Comment by bogdal** [comment]
@jpc2350 Check [this](https://github.com/mirumee/saleor-storefront/pull/486) out. It's a complete implementation.

**Comment by jpc2350** [comment]
Hi @bogdal, thanks for the quick response! I've pulled a copy of it into my repo, but encountering a couple of issues, two with the SDK - Which I think is something else, but my main issue is that the app now doesn't load anything related to checkout or payment. Not sure whats causing it, but having difficulties diagnosing exactly what it is - Looks like it could be related to the changes in AddressPicker

**Comment by jpc2350** [comment]
HI @bogdal, All fixed on this side, there was a change I had to make to the Saleor server in saleor.payment.gateways.stripe.__init__.py to make it work - The old system used secret_key, the new plugin uses private_key.

**Comment by bogdal** [comment]
👌 This was already fixed a few days ago in Saleor.
