### ISSUE TITLE
Adapt the appearance of Stripe components to the current design

### ISSUE THREAD

**Issue by bogdal** [mirumee/saleor-storefront#487]
### What I'm trying to achieve

The current Stripe's components don't fit to the rest of our design.

![Zrzut ekranu 2019-10-7 o 12 38 46](https://user-images.githubusercontent.com/1451824/66305929-b7892100-e900-11e9-9316-907cbad8de09.png)

### Describe a proposed solution

We need to improve styles.

**Comment by fedonkin** [comment]
Need a suitable design to the Stripe ? Show me where these files are and I'll draw a design. Will issue Css and html.
