### ISSUE TITLE
Heroku Error 14 (Memory quota exceeded) - Server Optimization/Settings

### ISSUE THREAD

**Issue by giovannipiccinelli** [mirumee/saleor-storefront#492]
### What I'm trying to achieve
Premise: I am not experienced in heroku however i am not sure if the problem lays with heroku or with the app itself.
Anyhow I do not expect to receive memory server warnings from Heroku.

### Steps to reproduce the problem
1. Install the core application, the storefront and the dashboard. I have everything up and running at the following url: https://www.storitalia.com (backend available at https://marketplace.storitalia.com).
2. Pulling all the new commits from github HEAD so that I am even with the original repos.
3. I set the storefront  and dashboard applications to "Hobby" heroku plan and I upgraded the heroku core server to "Standard 1X" heroku plan.
4. Call the homepage https://www.storitalia.com from the browser.

### What I expected to happen
1. The homepage loads fine however I expect an error free  experience on the core server side "saleor". Instead I can see non-stop warnings popping up.

### Screenshots
Screenshot of the core application server logs.
![Screen Shot 2019-10-10 at 7 37 21 PM](https://user-images.githubusercontent.com/7911077/66592910-4498d800-eb96-11e9-9cb6-87b08d52ba33.png)

**System information**
Operating system: Heroku
Browser: Chrome

**Comment by korycins** [comment]
Hi @giovannipiccinelli 
I have the same problem for web and celery workers. My local `runserver` takes around 250 MB of RAM, so I don't know exactly why I am hitting into a 512MB limit. I don't know how heroku calculate te ram usage, I wasn't able to find any detailed information.
I found this section in docs - https://devcenter.heroku.com/articles/optimizing-dyno-usage#python.
There is an article about deploying python app with gunicorn. Maybe this will be helpfull. (https://devcenter.heroku.com/articles/python-gunicorn)

**Comment by korycins** [comment]
Hi @giovannipiccinelli ,

According to Saleor core. I have the same issue wiht Heroku. My local `runserver` takes around 250MB of RAM, so it is strange that I am hitting in the twice higher limit.  I couldn't find any detailed info how heroku calculated memory usage. Is it only app or app + server.
I found this docs - https://devcenter.heroku.com/articles/optimizing-dyno-usage#python Hope this will help you.  There is an article about deploying python app to gunicron (https://devcenter.heroku.com/articles/python-gunicorn) maybe this is the solution that we are looking for.

**Comment by giovannipiccinelli** [comment]
Found this article https://devcenter.heroku.com/articles/ruby-memory-use
Apparently too many concurrencies erode the RAM memory and cause the errors.

I set the "WEB_CONCURRENCY" variable in the heroku variables environment to a lower number `heroku config:set WEB_CONCURRENCY=2` 

It seems like it is fixing the issue.
