### ISSUE TITLE
Enable varriant attributes

### ISSUE THREAD

**Issue by Tiagorsa** [mirumee/saleor-storefront#495]
### What I'm trying to achieve
When I enable a variant attributes to the "Saleor Storefront" on "Saleor Dashboard" all category product page views the attribute

### What I expected to happen
… See on "Saleor Storefront" the product filters attribute on the category page like "Saleor Web"

### Screenshots

Config screen:

![Captura de tela de 2019-10-14 21-21-27](https://user-images.githubusercontent.com/8277086/66791576-2d762500-eecb-11e9-952e-f2572c35c0da.png)

Saleor Site:
![Captura de tela de 2019-10-14 21-20-54](https://user-images.githubusercontent.com/8277086/66791599-48489980-eecb-11e9-83bc-240aabe51945.png)

Saloer Storefront [WRONG CATEGORY FILTER]
![Captura de tela de 2019-10-14 21-21-17](https://user-images.githubusercontent.com/8277086/66791618-5f878700-eecb-11e9-84e1-1c5c33d6ac66.png)

**System information**
Operating system: Linux Ubuntu 
Browser: Chrome and Firefox

**Comment by maarcingebala** [comment]
I'm not sure I understand the problem here - can you explain what is not working as you expected @Tiagorsa ?
