### ISSUE TITLE
How to login with social ( facebook & google) for Saleor-storefront?

### ISSUE THREAD

**Issue by QuiLeVan** [mirumee/saleor-storefront#496]
### What I'm trying to achieve login with social ( facebook & google) for saleor-storefront (React JS)
- How can I implement login with facebook / google ?
- I implemented & login success with facebook on HTML source. But I could not find anything in saleor-storefront source. So could you help to instruct me to implement social login for saleor-storefront ( React JS) ?

### Screenshots or mockups

_HTML source_
<img width="973" alt="Screen Shot 2019-10-16 at 11 44 32 AM" src="https://user-images.githubusercontent.com/8458010/66889243-e04d9c80-f00b-11e9-9ca3-fd30f9b0fdac.png">

_React Source_
<img width="1433" alt="Screen Shot 2019-10-16 at 11 44 02 AM" src="https://user-images.githubusercontent.com/8458010/66889253-e80d4100-f00b-11e9-9d7a-24781388572d.png">

Thanks you,

**Comment by maarcingebala** [comment]
We don't support it yet but it's definitely something we want to look into.

**Comment by ace-han** [comment]
from the doc    
It seems missing to mention the settings about `Authorized redirect URL`  in `facebook` and `google` respectively.

Also would like to know how to integrate with other social media logins

Looking forward to see this feature fully supported

**Comment by ace-han** [comment]
@maarcingebala I've gone through the code base and found that `social-auth-app-django` and relevant stuff were gradually phased out.
Why is that?

And again, social media login is some feature I am so desperate to have!
