### ISSUE TITLE
Display product "Attributes" on product page

### ISSUE THREAD

**Issue by giovannipiccinelli** [mirumee/saleor-storefront#498]
I  am trying to print/display the attributes attached to the product in the backend on the products page https://storitalia.com/product/set-of-3-murano-glass-multicolor-bowls/146/
…

### Steps to reproduce the problem
1. I am working on the file ../src/views/Product/Page.tsx
2. I am try to call the product attributes by typing `<h1>{product.variants[0].attributes[0].value}</h1>`. I get no error for the first snippet however when I load the product page the page itself is blank)
3. In alternative, I try to call the product attributes by typing `<h1>product.attributes[0].name</h1>`.  I get an error for the second snippet "Property 'attributes' does not exist on type 'ProductDetails_product'.")

### What I expected to happen
I would like to print the attributes on the product page wherever I need to. This used to work in the core version of saleor (as diplayed below) but I am not able to make it  work in the new storefront. I need your help.

![Screen Shot 2019-10-20 at 7 38 47 PM](https://user-images.githubusercontent.com/7911077/67163632-6736a800-f371-11e9-9e20-00872f76f6e7.png)

### Screenshots
Application Backend 
![Screen Shot 2019-10-17 at 9 45 21 PM](https://user-images.githubusercontent.com/7911077/67042408-2009a680-f128-11e9-80d6-bd7f0027708f.png)
Display location 1
![Screen Shot 2019-10-17 at 9 47 45 PM](https://user-images.githubusercontent.com/7911077/67042435-27c94b00-f128-11e9-84b6-33c4ba786b82.png)
Display location 2
![Screen Shot 2019-10-17 at 9 47 54 PM](https://user-images.githubusercontent.com/7911077/67042436-27c94b00-f128-11e9-9140-8a15996434f1.png)

**System information**
Operating system: heroku
Browser: chrome

**Comment by giovannipiccinelli** [comment]
@bogdal 
@dominik-zeglen 

any update or suggestion on how  to handle this one? 
By the  way.. great application guys.. this stuff rocks 🚀

**Comment by bogdal** [comment]
@giovannipiccinelli To display additional product attributes, first of all, you need to ask for them the GraphQL endpoint by extending the [ProductDetails](https://github.com/mirumee/saleor-storefront/blob/master/src/views/Product/queries.ts#L95) query:
```graphql
...
attributes {
  attribute {
    id
    name
  }
  values {
    id
    name
  }
}
```
And then you can display all attributes using the following example:
```javascript
{product.attributes.map(({ attribute, values }) => (
  <dl key={attribute.id}>
    <dt>{attribute.name}</dt>
    <dd>
      {values.map(({ name }) => name).join(", ")}
    </dd>
  </dl>
))}
```

**Comment by giovannipiccinelli** [comment]
@bogdal 

Thank you very much for your fast reply! i tried to apply your solution and it works. However I have  one  attribute which is still not displaying "VideoId" (as you can see  below). 

<img width="770" alt="Screen Shot 2019-10-22 at 9 59 27 AM" src="https://user-images.githubusercontent.com/7911077/67267892-876e8000-f4b3-11e9-9fe3-9b918cfb2c52.png">
<img width="632" alt="Screen Shot 2019-10-22 at 9 59 37 AM" src="https://user-images.githubusercontent.com/7911077/67267894-876e8000-f4b3-11e9-9b73-82956c928f27.png">

Also, is there a way to display a specific attribute (filter by name or Id) instead of  all of them?

Thanks! 🙏

**Comment by bogdal** [comment]
@giovannipiccinelli Make sure that your dashboard and storefront talk to the same graphql endpoint.

If you want to get the values of a particular attribute, the best way is to rely on the slug field:

Query:
```graphql
product(id: "...") {
  id
  name
  attributes {
    attribute {
      id
      name
      slug
    }
...
```

An example snippet:
```javascript
const material = product.attributes.find(
  ({ attribute: { slug } }) => slug === "material"
);
const materialValues = material
  ? material.values.map(({ name }) => name).join(", ")
  : null;
```

**Comment by giovannipiccinelli** [comment]
thanks a lot! 👍
