### ISSUE TITLE
saleor-storefront doesn't work without data in saleor database

### ISSUE THREAD

**Issue by IKarbowiak** [mirumee/saleor-storefront#508]
### What I'm trying to achieve
When there is no data in saleor database saleor-storefront doesn't work. 

### Steps to reproduce the problem
1. Install saleor but skip step with 'populatedb'. 
2. Run saleor-storefront on your machine

### What I expected to happen
I expect that saleor-storefront works even without data in saleor database.

**Comment by petrukngantuk** [comment]
You need to createsuperuser first,
Then go to go to saleor-dashboard

Add at least:
1 product type
1 category,
1 product
1 collection,

And in collection check the feature on home page...

Hope it will help you
