### ISSUE TITLE
npm start does not work on Windows: 'cross-env' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by petedermott** [mirumee/saleor-storefront#510]
### What I'm trying to achieve
Run the storefront in Windows 10

### Steps to reproduce the problem
1. Download either the latest release or the current master
2. Start either Powershell or Cmder
3. Set an API_URI environment variable with `set API_URI=http://localhost:8000/graphql/` (windows)
4. Run `npm install`
5. Run `npm start`

### What I expected to happen
The storefront server to start

### What actually happens

```
λ npm start

> saleor-site@0.7.0 start C:\Users\Peter\Documents\projects\saleor-storefront
> cross-env NODE_ENV=develop webpack-dev-server --history-api-fallback --watch --port 3000 --mode development --hotOnly

'cross-env' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor-site@0.7.0 start: `cross-env NODE_ENV=develop webpack-dev-server --history-api-fallback --watch --port 3000 --mode development --hotOnly`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the saleor-site@0.7.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Peter\AppData\Roaming\npm-cache\_logs\2019-11-06T15_12_41_972Z-debug.log
```

**System information**
Operating system: Windows 10 Pro Version 10.0.18362 Build 18362
Node: v12.8.1
NPM: v10.6.2
Browser: Firefox 70.0.1

**Comment by tomaszszymanski129** [comment]
Works flawlessly on my machine with exactly same version of node and npm
![image](https://user-images.githubusercontent.com/12252472/71094475-51940200-21ab-11ea-8da5-ab7d48e8379b.png)
![image](https://user-images.githubusercontent.com/12252472/71094490-5a84d380-21ab-11ea-9bd1-32fbefad0931.png)

**Comment by tomaszszymanski129** [comment]
try removing the `node-modules` or reinstalling node.js as this seems it might be connected with windows PATH not appended correctly.

**Comment by sabbirshawon** [comment]
use this command `npm install -global cross-env`
