### ISSUE TITLE
Braintree payments broken with Firefox

### ISSUE THREAD

**Issue by petedermott** [mirumee/saleor-storefront#511]
### What I'm trying to achieve
Checkout using the Firefox browser

### Steps to reproduce the problem
1. Install Saleor and storefront
3. Populate the database
2. Add braintree API keys
4. Place order using the Firefox browser

### What I expected to happen
For the order to complete

### What actually happens
In the current Saleor storefront this order will take me back to the "Select payment method" area of the checkout with no error messages. Orders will complete OK with Chrome and Edge, I have also tried a different machine with the same FF version and a completely clean cache.

This also affects the Django powered storefront in addition to the PWA

**System information**
Operating system: Windows 10 Pro
Browser: Firefox 70.0.1 (64-bit)

**Comment by mateuszkula** [comment]
@petedermott could you check if this issue still occurs after following PR has been merged?
https://github.com/mirumee/saleor-storefront/pull/575
