### ISSUE TITLE
API_URL is not respected

### ISSUE THREAD

**Issue by darrist** [mirumee/saleor-storefront#516]
### What I'm trying to achieve
I am trying to use `API_URL` as env var to point to my API URL.

### Steps to reproduce the problem
1. Set `API_URL` in environment variable
2. Run build
3. Open website and diagnose network

### What I expected to happen
During build, `API_URL` should be respected.

**Comment by bogdal** [comment]
@darrist `API_URI` is the right parameter you need

**Comment by darrist** [comment]
You're right, my mistake. Do you happen to know about CORS as well? It seem to me I'm getting `Network Error: Failed to Fetch [CORS ERROR]` on the storefront.

No trace of `django-cors` being setup on backend, I assume that could fix it.

**Comment by bogdal** [comment]
**Saleor** supports CORS by default. You can set allowed hosts using [ALLOWED_GRAPHQL_ORIGINS](https://github.com/mirumee/saleor/blob/master/saleor/settings.py#L452) variable.
