### ISSUE TITLE
Asset directory

### ISSUE THREAD

**Issue by osama-usuf** [mirumee/saleor-storefront#517]
### What I'm trying to achieve
I've been fiddling around with the Storefront 2.0 app and my eventual aim is customization. However, I am unable to locate the assets that are pulled off by the app when it starts.

### Steps to reproduce the problem
1. Setup the storefront dependencies.
2. `npm start`

### What I expected to happen
I expected all assets that are displayed after the project starts (see screenshot below) to be located in the `src/images` directory, however, the directory does not contain any `favicon` folder. My issue is hence locating files such as `images/favicons/android-chrome-144x144.png`. Where/how exactly are files in this directory retrieved/generated from?

### Screenshots
![image](https://user-images.githubusercontent.com/35128083/69501448-ded69480-0f26-11ea-9ead-650a034d7592.png)

**System information**
Operating system: Win10 x64
Browser: Chrome

**Comment by osama-usuf** [comment]
Figured this out. Closing.

**Comment by mathur619** [comment]
> Figured this out. Closing.

Kindly provide the solution if you figured it out. Others (like me), might face the same issue.
Thank you!
