### ISSUE TITLE
Changing the default storefront layout

### ISSUE THREAD

**Issue by WilsonKolana** [mirumee/saleor-storefront#523]
Hi, May I please ask for some tips on where to start changing the default layout of the new storefront, a. After perfoming some search I found this [answer](https://github.com/mirumee/saleor/issues/1342#issuecomment-346343472) but it was for the old storefront and I realized that the code structure is a bit different, otherwise it would have been very helpful. I am sorry I am quite new to React and Ts. Thank you in advance😊

**Comment by acidlake** [comment]
Hello, you can begin by doing a private repo ( trust me, you may need one, in case you screw something ), after that, you can begin changing the homepage:
`src/views/home/Page.tsx`
then the footer, 
remember to add your fonts to the global sass file, and I recommend that when you are going to edit any Component, to duplicated the component just in case.

**Comment by WilsonKolana** [comment]
Okay thanks
