### ISSUE TITLE
Addresses from address book not showing up during checkout

### ISSUE THREAD

**Issue by zzzzasd** [mirumee/saleor-storefront#524]
### What I'm trying to achieve
I am trying to complete a checkout with a pre-added address in the address book. I've made a dummy purchase before but the address does not appear during checkout. Had to log out and log back in to see the saved address.

### Steps to reproduce the problem
1. Complete checkout with an address already saved in the address book.

### What I expected to happen
Expect to see previously entered address to appear during checkout.

### Screenshots
![20191209+0819:25:27](https://user-images.githubusercontent.com/24844424/70432262-cf745100-1ab9-11ea-957f-4dd95bc5aec8.png)

**Comment by maarcingebala** [comment]
Testing it on master and it seems to be working fine now.
