### ISSUE TITLE
Frontpage keeps loading 

### ISSUE THREAD

**Issue by svenvanlierde** [mirumee/saleor-storefront#535]
### What I'm trying to achieve
loading the front page 

### Steps to reproduce the problem
1. loading page

### What I expected to happen
Frontpage keeps loading state,

### Screenshots
![Screenshot 2019-12-15 at 00 02 51](https://user-images.githubusercontent.com/24588562/70855649-b232ee80-1ece-11ea-81fd-2f8040b5b3e8.png)

when i load the page, in saleor console (permission denied)
![Screenshot 2019-12-15 at 00 04 17](https://user-images.githubusercontent.com/24588562/70855653-c2e36480-1ece-11ea-80d6-a16416599e39.png)

screenshots of query in chrome dev tools
![Screenshot 2019-12-15 at 00 04 36](https://user-images.githubusercontent.com/24588562/70855655-ce369000-1ece-11ea-9006-ddec5fe60f52.png)
![Screenshot 2019-12-15 at 00 04 43](https://user-images.githubusercontent.com/24588562/70855657-d1318080-1ece-11ea-8ee5-915c27040184.png)

**System information**
Operating system:  mac os
Browser: chrome
saleor 2.9
saleor front: 0.7.0

**Comment by acidlake** [comment]
did you followed the steps when creating Saleor, and run the migration to create the superuser ?

**Comment by svenvanlierde** [comment]
> did you followed the steps when creating Saleor, and run the migration to create the superuser ?

Yes...

**Comment by acidlake** [comment]
> > did you followed the steps when creating Saleor, and run the migration to create the superuser ?
> 
> Yes...

Looks like an issue with your API, try to rebuild your docker image

**Comment by jonbern** [comment]
I had the same issue, and in my case it was because the database was empty. Running the "example data" import script fixed it: https://docs.saleor.io/docs/getting-started/example-data/

```sh
$ python manage.py populatedb --createsuperuser
```

**Comment by maarcingebala** [comment]
I am closing this since it's been fixed on `master` for some time already.
