### ISSUE TITLE
Invalid mutation name on account register

### ISSUE THREAD

**Issue by tomaszszymanski129** [mirumee/saleor-storefront#542]
### What I'm trying to achieve
Have the frontend send typo free data on customer register

### Steps to reproduce the problem
1. Create an account in storefront
2. Look on graphql POST in dev console

### What I expected to happen
`Customer` is send, not `Cutomer`. Quite few places to replace in the source code.

### Screenshots

![image](https://user-images.githubusercontent.com/12252472/71259180-1b37bd80-2338-11ea-9b2a-79eb66da444b.png)

**System information**
Operating system: MacOS Catalina
Browser: Chrome

**Comment by acidlake** [comment]
Now that I tested this I'm having the same issue on the StoreFront, I checked my Graphql server, but that mutation is not there.

**Comment by tomaszszymanski129** [comment]
@acidlake notice `customerRegister` inside the query which is the actual mutation that exists server-side. That is why it is working (or at least it works for me with newest storefront and saleor), the bug is just about the wrapper name that frontend sends, which has the typo (and is omitted server-side unlike the payload with proper mutation name)
