### ISSUE TITLE
User profile button is not available / mobile version

### ISSUE THREAD

**Issue by karolkielecki** [mirumee/saleor-storefront#548]
1. User profile button is only available on the desktop version
2. pwa.saleor.io

![image](https://user-images.githubusercontent.com/57907951/71516250-2a72ba00-28a8-11ea-8220-f32618447f1a.png)

![image](https://user-images.githubusercontent.com/57907951/71516261-3494b880-28a8-11ea-9402-8b55ed81b3d6.png)

**Comment by jfamousket** [comment]
That's how it was implemented, it's not an error, I think you change it depending your usecase, see:
https://github.com/mirumee/saleor-storefront/blob/master/src/components/MainMenu/MainMenu.tsx#L107
