### ISSUE TITLE
URL without IDs

### ISSUE THREAD

**Issue by Zyles** [mirumee/saleor-storefront#554]
Remove /category/ and /product/ in URLs and stop using ID numbers.

Wordpress figured this out 10 years ago, don't bring in bad habits.

URLs should be permanent, unique and have no ID numbers. The system should not need to distinguish a page, category or product using the url. That should be handled by the API router.

Saleor looks promising but there is no way we are 301 redirecting over 10k SKUs to worse URLs than we have today.

**Comment by Zyles** [comment]
You created an attack vector for malicious duplicate SEO content.

Is that informative enough?

https://demo.saleor.io/product/asodasjdojdajodiasijdo/81/
https://demo.saleor.io/product/sdfdgdgasdffdfsdfsdaf/81/
https://demo.saleor.io/product/sadfasdfwe4fawefaefaefasfsd/81/
https://demo.saleor.io/product/sadfasdfsdfsdfsdf3fsefsef/81/
https://demo.saleor.io/product/2434234rwe234234234234/81/


https://moz.com/learn/seo/duplicate-content

**Comment by Zyles** [comment]
More issues:

https://demo.saleor.io/product/ returns status code 200 while the page actually says 404

You created a page without any content. And all 404 pages will be the same, and return 200 status code across the page over long term when links get broken and products are taken out of stock.

The urls are hierarchical, but there is nothing at the top content. You may look at this as a small thing.

It also affects the breadcrumbs.

![image](https://user-images.githubusercontent.com/1741593/71553318-0e892880-2a0e-11ea-8561-3377ef533576.png)

Compared to:
![image](https://user-images.githubusercontent.com/1741593/71553338-82c3cc00-2a0e-11ea-891d-6142ea086dca.png)

You are also using duplicate content on the categories. Not sure if that is just because it is a demo, but you should write the category name and description uniquely, automatically.

You are using eBay as an example. But it is not really a good one. They are a HUGE company and they do not care about SEO as much as smaller businesses do.

Rather ask yourself the other way around, what value does /category/ and /product/ bring? Can't you do URL mapping to product/category without it?

**Comment by Pacu2** [comment]
@Zyles Thanks for pointing this out. All of those were resolved in the "old" version of Saleor, but the storefront is still beta quality and evolving. I have created related issues. 

Dropping "category" or "product" is a matter of preference, I suppose.

**Comment by NyanKiyoshi** [comment]
We could use JSON-LD for that, for example newegg does that:
```
{

    "@context":"http://schema.org",
    "@type":"BreadcrumbList",
    "itemListElement":[
        {
            "@type":"ListItem",
            "position":1,
            "item":{
                "@id":"https://www.newegg.com/",
                "name":"Home"
            }
        },
        {
            "@type":"ListItem",
            "position":2,
            "item":{
                "@id":"https://www.newegg.com/Components/Store/ID-1",
                "name":"Components"
            }
        },
        {
            "@type":"ListItem",
            "position":3,
            "item":{
                "@id":"https://www.newegg.com/Fans-PC-Cooling/Category/ID-11",
                "name":"Fans & PC Cooling"
            }
        },
        {
            "@type":"ListItem",
            "position":4,
            "item":{
                "@id":"https://www.newegg.com/Water-Liquid-Cooling/SubCategory/ID-575",
                "name":"Water \/ Liquid Cooling"
            }
        },
        {
            "@type":"ListItem",
            "position":5,
            "item":{
                "@id":"https://www.newegg.com/d/NZXT-Water-Liquid-Cooling/BrandSubCat/ID-2120-575",
                "name":"NZXT"
            }
        }
    ]
}
```

That is a possibility. It is well handled by Google.

The e-commerce website that I know/use are all using the structure `something/<name>` (`category`, `page`, etc.); it never bothered me (some are actually awful, like for example topachat.com showing on Google: `pages/detail2_cat_est_telephonie_puis_rubrique_est_wt_smartp_puis_ref_est_tl11003300.html`); it actually makes it more readable (to my eyes)–but as @Pacu2 said, that's a question of taste. SEO-wise, JSON-LD can easily be an answer for better SEO.

Right now, we are still yet to only have one kind of product architecture, (improved) collections instead of categories for more flexibility. Once we only have one kind, it will allow easy customization.

**Comment by NyanKiyoshi** [comment]
@Pacu2 could you edit https://github.com/mirumee/saleor-storefront/issues/553 to include:


> You created an attack vector for malicious duplicate SEO content.
> 
> Is that informative enough?
> 
> https://demo.saleor.io/product/asodasjdojdajodiasijdo/81/
> https://demo.saleor.io/product/sdfdgdgasdffdfsdfsdaf/81/
> https://demo.saleor.io/product/sadfasdfwe4fawefaefaefasfsd/81/
> https://demo.saleor.io/product/sadfasdfsdfsdfsdf3fsefsef/81/
> https://demo.saleor.io/product/2434234rwe234234234234/81/
> 
> https://moz.com/learn/seo/duplicate-content

As it is the _same_ issue and bug.

**Comment by NyanKiyoshi** [comment]
Tracking tickets:
- https://github.com/mirumee/saleor-storefront/issues/553
- https://github.com/mirumee/saleor-storefront/issues/552
