### ISSUE TITLE
Storefront doesn't show product details for a new Paint product without variant

### ISSUE THREAD

**Issue by IKarbowiak** [mirumee/saleor-storefront#555]
Storefront doesn't show product details from Paints category and with Paint Prodct Type after creating new one without ProductVariant.

### Steps to reproduce the problem
1. Open dashboard
2. Create product with Paint Product Type and Paint category
3. Open storefront and Paint category
4. Click on this product (you should get blank site)

### What I expected to happen
I would like to create product without variant or to be informed that I need to add product variant.

### Screenshots
Created product:
![image](https://user-images.githubusercontent.com/40886528/71585085-af164000-2b15-11ea-8075-4497b7773a9c.png)

Paint is visible on category page:
![image](https://user-images.githubusercontent.com/40886528/71585185-f6043580-2b15-11ea-9602-5870259a009a.png)

But when you try open it, there is a blank page
![image](https://user-images.githubusercontent.com/40886528/71585214-0caa8c80-2b16-11ea-9e6c-9a48b255db2f.png)

Errors:
![image](https://user-images.githubusercontent.com/40886528/71585227-16cc8b00-2b16-11ea-8d80-c397b95b2c2e.png)

**Comment by tboulogne** [comment]
@IKarbowiak in your product type, does "Product type use variants attributes" is off ?

![image](https://user-images.githubusercontent.com/6205275/71958616-050f7580-31f1-11ea-8ffd-dc1b828e0221.png)
