### ISSUE TITLE
Open Graph Protocol Not Working

### ISSUE THREAD

**Issue by cheewoei1997** [mirumee/saleor-storefront#558]
### What I'm trying to achieve
To have SMO capabilities when sharing a link on Facebook or Whatsapp. The link should generate a picture of the product along with the title.

### Steps to reproduce the problem
1. Run saleor and saleor-storefront normally
2. Copy and paste a link from one of the products from Saleor.

### What I expected to happen
The link should generate the product image and product title like in pwa.saleor.io.

### Screenshots
<img width="524" alt="Screenshot 2020-01-02 at 3 34 12 PM" src="https://user-images.githubusercontent.com/14294811/71656202-6492fe80-2d75-11ea-9e19-933312225b61.png">

**System information**
Operating system: MacOS Catalina 10.15.2
Browser: Google Chrome 79.0.3945.88 (Official Build) (64-bit)

**Comment by navenprasad** [comment]
#191 Seems to solve this problem with React Helmet, but I am having the same problem.
```
import * as React from "react";
import { Helmet } from "react-helmet";

import { Consumer as MetaConsumer } from "./context";

class Consumer extends React.Component {
  render() {
    return (
      <MetaConsumer>
        {({ title, description, image, type, url, custom }) => (
          <>
            <Helmet
              title={title}
              meta={[
                { name: "description", content: description },
                { property: "og:url", content: url },
                { property: "og:type", content: type },
                { property: "og:image", content: image },
                ...custom
              ]}
            />
            {this.props.children}
          </>
        )}
      </MetaConsumer>
    );
  }
}

export default Consumer;
```

@maarcingebala Is it being rendered server side?

**Comment by maarcingebala** [comment]
@navenprasad Our storefront is rendered client-side and it doesn't provide any SSR capabilities by default. With a project like this, you can use e.g. [Rendertron](https://github.com/GoogleChrome/rendertron) to prerender your client app for bots.

**Comment by mateuszkula** [comment]
This issue should be fixed by following merged PR https://github.com/mirumee/saleor-storefront/pull/607
