### ISSUE TITLE
Reset password does not work

### ISSUE THREAD

**Issue by tomaszszymanski129** [mirumee/saleor-storefront#559]
### What I'm trying to achieve
Have my password reset in storefront.

### Steps to reproduce the problem
1. Go to storefront
2. click in `Have you forgotten your password section`
3. enter your email and click `Reset password`
4. reset password screen disappears
5. in browser console you can see the error that is not being handled in any way
![image](https://user-images.githubusercontent.com/12252472/71658408-3a751880-2d44-11ea-94b7-0f2d834ad100.png)
Frontend sends hardcoded `""` as `redirectUrl` so that's probably why it breaks as it is validated on backend

### What I expected to happen
Password reset email should be sent and I get confirmation message to check my inbox or something similar.

**System information**
Operating system: MacOS Catalina
Browser: Chrome

**Comment by maarcingebala** [comment]
This seems to be resolved already.

**Comment by oteran92** [comment]
Hello, 
Im getting same error. Someone have solve this issue??
