### ISSUE TITLE
Heroku deployment - "photos unavailable"

### ISSUE THREAD

**Issue by raylooi** [mirumee/saleor-storefront#560]
anyone encountered the same issue? 

### What I'm trying to achieve
deploy storefront to heroku using the deployment button provided

### Steps to reproduce the problem
1. click on button "deploy to heroku"

### What I expected to happen
… saleor storefront with images

### Screenshots
![saleor](https://user-images.githubusercontent.com/42400783/71867032-6ed14600-3143-11ea-9589-a0f538462d6c.jpg)

**System information**
Operating system: heroku ubuntu
Browser:firefox

**Comment by maarcingebala** [comment]
Be default Heroku doesn't support storing media files unless you configure a backend for that. See our docs here: https://docs.getsaleor.com/docs/deployment/heroku/

> Heroku’s storage is volatile. This means that all instances of your application have separate disks and lose all changes made to the local disk each time the application is restarted. The best approach is to use cloud storage such as Amazon S3. See Storing Files on Amazon S3 for configuration details.

We can recommend configuring for example S3 for that purpose: https://docs.getsaleor.com/docs/deployment/s3/

**Comment by raylooi** [comment]
Hi Marcin, 

Thank you for replying. However, i have set up S3 (aws access key, secret access and bucket). 

you can see the screenshot below that i am able to upload the product image as well. 

![image](https://user-images.githubusercontent.com/42400783/71901639-5a209c80-319b-11ea-906d-c13c1baebe21.png)

however, it does not appear in the thumbnail (resizing does not happen) and it also does not appear in the storefront unless i click on the item. 

Hope you can give me more directions and insight into what i might have misconfigured. 

Thank you in advance.
Ray
