### ISSUE TITLE
Npm install don't work

### ISSUE THREAD

**Issue by gComet** [mirumee/saleor-storefront#561]
### What I'm trying to achieve
I'm trying to install the app

### Steps to reproduce the problem
1. npm i

### What I expected to happen
to install the storefront

### Screenshots
https://imgur.com/xVEIot6

**System information**
Operating system:  Ubuntu
Browser: Chrome

**Comment by karolkielecki** [comment]
@gComet Hi there! Please update Node.js. It requires 10.0+, but below 11. You can find more information here: https://github.com/mirumee/saleor-storefront#prerequisites

If you have more questions, let us know.
Best
