### ISSUE TITLE
Address get duplicated every checkout

### ISSUE THREAD

**Issue by darrist** [mirumee/saleor-storefront#562]
### Steps to reproduce the problem
1. Checkout once
2. Checkout twice, select the same address
3. Checkout again, you will see same address duplicated 2 times

### What I expected to happen
Saleor should check uniqueness of address before creating a new entry in database

**Comment by karolkielecki** [comment]
@darrist Hi there! Could you please send us some screenshots?

**Comment by darrist** [comment]
Sorry, I realize problem caused by myself having extra fields in the address form, so controller could not identify and create extra address in db. Closing this now.

**Comment by martinharyanto** [comment]
hi, I know this has been closed.
But can you explain what is the extra fields that makes it got duplicated? I have same issue but can't find what is the problem 🤔
