### ISSUE TITLE
HEAD of storefront and saleor

### ISSUE THREAD

**Issue by rosscdh** [mirumee/saleor-storefront#563]
### What I'm trying to achieve
get PWA working with backend at head master of both

saleor: e09d62bd4
storefront: 955b5f16

docker-compose up
and npm start

and i get on storefront when viewing a product or list

```
[{"errors": [{"message": "Cannot query field \"value\" on type \"SelectedAttribute\". Did you mean \"values\"?", "locations": [{"line": 56, "column": 5}], "extensions": {"exception": {"code": "GraphQLError", "stacktrace": ["graphql.error.base.GraphQLError: Cannot query field \"value\" on type \"SelectedAttribute\". Did you mean \"values\"?"]}}}, {"message": "Cannot query field \"availability\" on type \"Product\".", "locations": [{"line": 134, "column": 5}], "extensions": {"exception": {"code": "GraphQLError", "stacktrace": ["graphql.error.base.GraphQLError: Cannot query field \"availability\" on type \"Product\"."]}}}]}]
```

### Steps to reproduce the problem
1. docker-compose up 
2. npm start

### What I expected to happen
…

### Screenshots
![Screen Shot 2020-01-10 at 16 23 13](https://user-images.githubusercontent.com/397106/72164334-ca126b00-33c5-11ea-8cb4-77f461f3ca4c.png)

![Screen Shot 2020-01-10 at 16 25 42](https://user-images.githubusercontent.com/397106/72164379-e31b1c00-33c5-11ea-8291-054c7c34c88f.png)

**System information**
Operating system: 
Browser:

**Comment by maarcingebala** [comment]
Hey, currently Storefront's `master` is behind the latest changes on the `master` of Saleor backend. We recommend using [2.9.0](https://github.com/mirumee/saleor/releases/tag/2.9.0) version of Saleor backend with [0.7.0](https://github.com/mirumee/saleor-storefront/releases/tag/v0.7.0) release of the storefront which are stable versions.

**Comment by rosscdh** [comment]
Hi thanks i tried that as well but no success... ill try it again

**Comment by rosscdh** [comment]
Ah great! got it going as prescribed! thanks! weird it didnt work first time but now all good rebuilt the images and repopulated and perfect :)

**Comment by rosscdh** [comment]
And dashboard at v2.0.0 ?

**Comment by rosscdh** [comment]
Also are there currently plans to integrate with wagtail.io? As this cms would make an amazing addition
