### ISSUE TITLE
Unpublishing products led to blank storefront page

### ISSUE THREAD

**Issue by raylooi** [mirumee/saleor-storefront#572]
### What I'm trying to achieve
added my own products and tried to remove those in the demo using "unpublish" from the dashboard. however, unpublishing gives an error so i had to go into individual products and make them "hidden". 

### Steps to reproduce the problem
1. go to dashboard and go to individual products to make it 'hidden'. 

### What I expected to happen
1. products get hidden and only show those i want which are visible. 

### What error did i get
when i have completed putting to 'hidden' all the products i did not want to be shown, the site crashes. it shows only a blank page. when i click on chrome inspect element, i see the following errors:

react-dom.development.js:56 Uncaught Invariant Violation: Query(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at invariant (http://localhost:3000/js/app.js:5429:15)
    at reconcileChildFibers (http://localhost:3000/js/app.js:18010:13)
    at reconcileChildren (http://localhost:3000/js/app.js:19776:28)
    at finishClassComponent (http://localhost:3000/js/app.js:20132:5)
    at updateClassComponent (http://localhost:3000/js/app.js:20070:24)
    at beginWork (http://localhost:3000/js/app.js:21018:16)
    at performUnitOfWork (http://localhost:3000/js/app.js:24686:12)
    at workLoop (http://localhost:3000/js/app.js:24726:24)
    at HTMLUnknownElement.callCallback (http://localhost:3000/js/app.js:5523:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/js/app.js:5573:16)
invariant @ react-dom.development.js:56
reconcileChildFibers @ react-dom.development.js:12637
reconcileChildren @ react-dom.development.js:14403
finishClassComponent @ react-dom.development.js:14759
updateClassComponent @ react-dom.development.js:14697
beginWork @ react-dom.development.js:15645
performUnitOfWork @ react-dom.development.js:19313
workLoop @ react-dom.development.js:19353
callCallback @ react-dom.development.js:150
invokeGuardedCallbackDev @ react-dom.development.js:200
invokeGuardedCallback @ react-dom.development.js:257
replayUnitOfWork @ react-dom.development.js:18579
renderRoot @ react-dom.development.js:19469
performWorkOnRoot @ react-dom.development.js:20343
performWork @ react-dom.development.js:20255
performSyncWork @ react-dom.development.js:20229
requestWork @ react-dom.development.js:20098
scheduleWork @ react-dom.development.js:19912
dispatchAction @ react-dom.development.js:13600
(anonymous) @ I18nLoader.tsx:32
fulfilled @ index.ts:25
react-dom.development.js:17118 The above error occurred in the <Query> component:
    in Query
    in Unknown (created by ProductsFeatured)
    in ProductsFeatured (created by Page)
    in Page (created by Query)
    in Consumer (created by MetaWrapper)
    in MetaWrapper (created by Query)
    in Query
    in Unknown (created by View)
    in div (created by View)
    in View (created by Route)
    in Route
    in Switch
    in Unknown (created by App)
    in App (created by Route)
    in Route (created by Context.Consumer)
    in Switch (created by Context.Consumer)
    in CartProvider (created by Context.Consumer)
    in Unknown (created by Checkout)
    in Checkout
    in Provider (created by Route)
    in Route (created by withRouter(Provider))
    in withRouter(Provider)
    in Query
    in Unknown (created by ShopProvider)
    in ShopProvider
    in CredentialsProvider (created by SaleorProvider)
    in SaleorProvider
    in ApolloProvider
    in Route (created by QueryParamProvider)
    in QueryParamProvider
    in Router
    in Unknown (created by HotExportedComponent)
    in AppContainer (created by HotExportedComponent)
    in HotExportedComponent
    in Unknown
    in Provider
    in I18nProvider
    in Unknown
    in ThemeProvider

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
logCapturedError @ react-dom.development.js:17118
logError @ react-dom.development.js:17154
callback @ react-dom.development.js:18095
callCallback @ react-dom.development.js:16434
commitUpdateEffects @ react-dom.development.js:16473
commitUpdateQueue @ react-dom.development.js:16464
commitLifeCycles @ react-dom.development.js:17365
commitAllLifeCycles @ react-dom.development.js:18737
callCallback @ react-dom.development.js:150
invokeGuardedCallbackDev @ react-dom.development.js:200
invokeGuardedCallback @ react-dom.development.js:257
commitRoot @ react-dom.development.js:18949
(anonymous) @ react-dom.development.js:20419
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20418
performWorkOnRoot @ react-dom.development.js:20347
performWork @ react-dom.development.js:20255
performSyncWork @ react-dom.development.js:20229
requestWork @ react-dom.development.js:20098
scheduleWork @ react-dom.development.js:19912
dispatchAction @ react-dom.development.js:13600
(anonymous) @ I18nLoader.tsx:32
fulfilled @ index.ts:25
react-hot-loader.development.js:247 Invariant Violation: Query(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at invariant (http://localhost:3000/js/app.js:5429:15)
    at reconcileChildFibers (http://localhost:3000/js/app.js:18010:13)
    at reconcileChildren (http://localhost:3000/js/app.js:19776:28)
    at finishClassComponent (http://localhost:3000/js/app.js:20132:5)
    at updateClassComponent (http://localhost:3000/js/app.js:20070:24)
    at beginWork (http://localhost:3000/js/app.js:21018:16)
    at performUnitOfWork (http://localhost:3000/js/app.js:24686:12)
    at workLoop (http://localhost:3000/js/app.js:24726:24)
    at renderRoot (http://localhost:3000/js/app.js:24809:7)
    at performWorkOnRoot (http://localhost:3000/js/app.js:25716:7)
error @ react-hot-loader.development.js:247
componentDidCatch @ react-hot-loader.development.js:2183
callback @ react-dom.development.js:18096
callCallback @ react-dom.development.js:16434
commitUpdateEffects @ react-dom.development.js:16473
commitUpdateQueue @ react-dom.development.js:16464
commitLifeCycles @ react-dom.development.js:17365
commitAllLifeCycles @ react-dom.development.js:18737
callCallback @ react-dom.development.js:150
invokeGuardedCallbackDev @ react-dom.development.js:200
invokeGuardedCallback @ react-dom.development.js:257
commitRoot @ react-dom.development.js:18949
(anonymous) @ react-dom.development.js:20419
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20418
performWorkOnRoot @ react-dom.development.js:20347
performWork @ react-dom.development.js:20255
performSyncWork @ react-dom.development.js:20229
requestWork @ react-dom.development.js:20098
scheduleWork @ react-dom.development.js:19912
dispatchAction @ react-dom.development.js:13600
(anonymous) @ I18nLoader.tsx:32
fulfilled @ index.ts:25
react-dom.development.js:56 Uncaught Invariant Violation: Query(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at invariant (http://localhost:3000/js/app.js:5429:15)
    at reconcileChildFibers (http://localhost:3000/js/app.js:18010:13)
    at reconcileChildren (http://localhost:3000/js/app.js:19776:28)
    at finishClassComponent (http://localhost:3000/js/app.js:20132:5)
    at updateClassComponent (http://localhost:3000/js/app.js:20070:24)
    at beginWork (http://localhost:3000/js/app.js:21018:16)
    at performUnitOfWork (http://localhost:3000/js/app.js:24686:12)
    at workLoop (http://localhost:3000/js/app.js:24726:24)
    at renderRoot (http://localhost:3000/js/app.js:24809:7)
    at performWorkOnRoot (http://localhost:3000/js/app.js:25716:7)
invariant @ react-dom.development.js:56
reconcileChildFibers @ react-dom.development.js:12637
reconcileChildren @ react-dom.development.js:14403
finishClassComponent @ react-dom.development.js:14759
updateClassComponent @ react-dom.development.js:14697
beginWork @ react-dom.development.js:15645
performUnitOfWork @ react-dom.development.js:19313
workLoop @ react-dom.development.js:19353
renderRoot @ react-dom.development.js:19436
performWorkOnRoot @ react-dom.development.js:20343
performWork @ react-dom.development.js:20255
performSyncWork @ react-dom.development.js:20229
requestWork @ react-dom.development.js:20098
scheduleWork @ react-dom.development.js:19912
dispatchAction @ react-dom.development.js:13600
(anonymous) @ I18nLoader.tsx:32
fulfilled @ index.ts:25
react-dom.development.js:17118 The above error occurred in the <AppContainer> component:
    in AppContainer (created by HotExportedComponent)
    in HotExportedComponent
    in Unknown
    in Provider
    in I18nProvider
    in Unknown
    in ThemeProvider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:17118
logError @ react-dom.development.js:17154
update.callback @ react-dom.development.js:18066
callCallback @ react-dom.development.js:16434
commitUpdateEffects @ react-dom.development.js:16473
commitUpdateQueue @ react-dom.development.js:16461
commitLifeCycles @ react-dom.development.js:17384
commitAllLifeCycles @ react-dom.development.js:18737
callCallback @ react-dom.development.js:150
invokeGuardedCallbackDev @ react-dom.development.js:200
invokeGuardedCallback @ react-dom.development.js:257
commitRoot @ react-dom.development.js:18949
(anonymous) @ react-dom.development.js:20419
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20418
performWorkOnRoot @ react-dom.development.js:20347
performWork @ react-dom.development.js:20255
performSyncWork @ react-dom.development.js:20229
requestWork @ react-dom.development.js:20098
scheduleWork @ react-dom.development.js:19912
dispatchAction @ react-dom.development.js:13600
(anonymous) @ I18nLoader.tsx:32
fulfilled @ index.ts:25
react-dom.development.js:56 Uncaught (in promise) Invariant Violation: Query(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at invariant (http://localhost:3000/js/app.js:5429:15)
    at reconcileChildFibers (http://localhost:3000/js/app.js:18010:13)
    at reconcileChildren (http://localhost:3000/js/app.js:19776:28)
    at finishClassComponent (http://localhost:3000/js/app.js:20132:5)
    at updateClassComponent (http://localhost:3000/js/app.js:20070:24)
    at beginWork (http://localhost:3000/js/app.js:21018:16)
    at performUnitOfWork (http://localhost:3000/js/app.js:24686:12)
    at workLoop (http://localhost:3000/js/app.js:24726:24)
    at renderRoot (http://localhost:3000/js/app.js:24809:7)
    at performWorkOnRoot (http://localhost:3000/js/app.js:25716:7)
invariant @ react-dom.development.js:56
reconcileChildFibers @ react-dom.development.js:12637
reconcileChildren @ react-dom.development.js:14403
finishClassComponent @ react-dom.development.js:14759
updateClassComponent @ react-dom.development.js:14697
beginWork @ react-dom.development.js:15645
performUnitOfWork @ react-dom.development.js:19313
workLoop @ react-dom.development.js:19353
renderRoot @ react-dom.development.js:19436
performWorkOnRoot @ react-dom.development.js:20343
performWork @ react-dom.development.js:20255
performSyncWork @ react-dom.development.js:20229
requestWork @ react-dom.development.js:20098
scheduleWork @ react-dom.development.js:19912
dispatchAction @ react-dom.development.js:13600
(anonymous) @ I18nLoader.tsx:32
fulfilled @ index.ts:25
react-dom.development.js:507 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Unknown (created by Checkout)
    in Checkout
    in Provider (created by Route)
    in Route (created by withRouter(Provider))
    in withRouter(Provider)
    in Query
    in Unknown (created by ShopProvider)
    in ShopProvider
    in CredentialsProvider (created by SaleorProvider)
    in SaleorProvider
    in ApolloProvider
    in Route (created by QueryParamProvider)
    in QueryParamProvider
    in Router
    in Unknown (created by HotExportedComponent)
    in AppContainer (created by HotExportedComponent)
    in HotExportedComponent
    in Unknown
    in Provider
    in I18nProvider
    in Unknown
    in ThemeProvider
warningWithoutStack @ react-dom.development.js:507
warnAboutUpdateOnUnmounted @ react-dom.development.js:18476
scheduleWork @ react-dom.development.js:19892
dispatchAction @ react-dom.development.js:13600
onError @ useQuery.ts:65
(anonymous) @ index.ts:279
notifySubscription @ Observable.js:134
onNotify @ Observable.js:165
error @ Observable.js:224
(anonymous) @ bundle.esm.js:390
error @ bundle.esm.js:390
(anonymous) @ bundle.esm.js:1191
step @ tslib.es6.js:97
(anonymous) @ tslib.es6.js:78
(anonymous) @ tslib.es6.js:71
__awaiter @ tslib.es6.js:67
(anonymous) @ bundle.esm.js:1147
(anonymous) @ bundle.esm.js:1627
(anonymous) @ bundle.esm.js:1626
./node_modules/apollo-client/bundle.esm.js.QueryManager.broadcastQueries @ bundle.esm.js:1621
(anonymous) @ bundle.esm.js:1719
step @ tslib.es6.js:97
(anonymous) @ tslib.es6.js:78
(anonymous) @ tslib.es6.js:71
__awaiter @ tslib.es6.js:67
next @ bundle.esm.js:1676
notifySubscription @ Observable.js:130
onNotify @ Observable.js:165
next @ Observable.js:219
(anonymous) @ bundle.esm.js:32
next @ bundle.esm.js:32
notifySubscription @ Observable.js:130
onNotify @ Observable.js:165
next @ Observable.js:219
next @ index.js:41
notifySubscription @ Observable.js:130
onNotify @ Observable.js:165
next @ Observable.js:219
notifySubscription @ Observable.js:130
onNotify @ Observable.js:165
next @ Observable.js:219
RetryableOperation.onNext @ retryLink.js:74
notifySubscription @ Observable.js:130
onNotify @ Observable.js:165
next @ Observable.js:219
(anonymous) @ batching.js:106
(anonymous) @ batching.js:106
next @ batching.js:102
notifySubscription @ Observable.js:130
onNotify @ Observable.js:165
next @ Observable.js:219
(anonymous) @ batchHttpLink.js:95
Show 22 more frames
:3000/service-worker.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
…

### Screenshots

**System information**
Operating system: 
Browser:

**Comment by maarcingebala** [comment]
Thanks for reporting, we'll take a look at the issue!

**Comment by orzechdev** [comment]
Actually, I see there are two problems.
One is with occuring error, which as I see should be already fixed: https://github.com/mirumee/saleor-storefront/pull/551. Are you sure you are using latest storefront version with that fix?
The second one is not hiding unpublished products. I'll try to manage it.

**Comment by orzechdev** [comment]
The second problem is only occurring when user like an admin has privileges to see unpublished products, so it should work if the first one is fixed. We will try to mark unpublished products somehow for logged in privileged user in future.
