### ISSUE TITLE
Unable to Register or Add a new user

### ISSUE THREAD

**Issue by kaulonline** [mirumee/saleor-storefront#577]
Thank you team for putting this wonderful ecomm solution

### What I'm trying to achieve
Adding a new user or registering a new user

### Steps to reproduce the problem
1. Setup Saleor core + storefront + dashboard.
2. Environment Variables set and everything is up on http://38.240.17.193:3000/
3. Creating a new user, doesn't do anything. There is neither a successful message nor any confirmation. The database insertion doesn't happen as it is expected on a new user creation. 

### What I expected to happen
A successful message or a confirmation should be displayed. The database insertion should also happen as it is a new user creation. 

### Screenshots
Please try this on my demo portal : http://38.240.17.193:3000/

**System information**
Operating system: Mac
Browser: Chrome, Mac

Please suggest the root cause and anything I may have missed during the installation.

**Comment by karolkielecki** [comment]
@kaulonline Hi there! Thanks for your kind words about Saleor. Do the new users appear in the dashboard --> customers section? By the way, your demo portal is not working.

**Comment by Joash-star** [comment]
@ kaulonline  Did you solve?

**Comment by rawho** [comment]
I am also having the same issue. Nothing is happening while clicking the register button

**Comment by bharat22goyal** [comment]
Having the same issue. Any solutions?

**Comment by dipu1110** [comment]
having same issue? pls provide solution!
