### ISSUE TITLE
npm ERROR

### ISSUE THREAD

**Issue by Pichnyty** [mirumee/saleor-storefront#589]
### What I'm trying to achieve
Able to access " localhost:3000"
### Steps to reproduce the problem
1. After cloning my project from git 
2. I run " npm i " as instruction 
3. set environment variable as instruction
4. run "npm start"

### What I expected to happen
able to access "localhost:3000"
### Screenshots
![XXXXX](https://user-images.githubusercontent.com/54165288/73586535-4689fc80-44e1-11ea-9664-bba225c3f984.JPG)

**System information**
Operating system: Window 10 
Browser: Chrome

**Comment by maarcingebala** [comment]
Which version of Node and NPM are you using?

**Comment by Pichnyty** [comment]
Hi @maarcingebala I use 
Node : v12.14.1
npm : 6.13.6

**Comment by maarcingebala** [comment]
Can you share the full error? Versions seem OK. Sometimes removing `node_modules` and reinstalling everything again also helps.

**Comment by Pichnyty** [comment]
**1st thing**
I want to be the contributor of this project, i cloned all the repository
1. saleor branch (master)
2. saleor-storefront branch (master)
3. saleor-dashboard branch (master)
My environment
python 3.8.1, pip 20.0.2
Node 12.14.1, npm 6.13.7
Postgres 9.5
OS : Window 10
I follow all the instruction but still i cannot install on local success.(stuck on  installing python environment)

Question : Would u plz tell me every commit that the team push to master branch in (saleor, saleor-storefront,saleor-dashboard). Does it work synchronized all together ?

**2nd thing** 
about saleor (2.9.1) is it the latest version ?_(confirmation question)_

+using python3.8.1 to install pip as this command "python -m pip install -r requirements.txt" not success.
+ Until i uninstall python 3.8.1 and install python 3.7.6 then i run "python -m pip install -r requirements.txt" it works.

Could u please explain more ?

**Comment by amirulasyraf88** [comment]
Hi, how do you solve this problem?

`18 verbose node v10.14.1
19 verbose npm  v6.13.7
20 error code ELIFECYCLE
21 error errno 1
22 error saleor-site@0.7.0 start: `cross-env NODE_ENV=develop webpack-dev-server --history-api-fallback --watch --port 3000 --mode development --hotOnly`
22 error Exit status 1
23 error Failed at the saleor-site@0.7.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

here my error log. I already check for the graphql API_URI and it is ok.. when hit the npm start the error came out.

**Comment by egyping** [comment]
same here with the same logs

**Comment by marcin-stasiak** [comment]
Same here, full log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@6.13.7
3 info using node@v12.16.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle saleor-site@0.7.0~prestart: saleor-site@0.7.0
6 info lifecycle saleor-site@0.7.0~start: saleor-site@0.7.0
7 verbose lifecycle saleor-site@0.7.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle saleor-site@0.7.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/workspace/frontend/node_modules/.bin:/home/user/workspace/frontend/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle saleor-site@0.7.0~start: CWD: /home/user/workspace/frontend
10 silly lifecycle saleor-site@0.7.0~start: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env NODE_ENV=develop webpack-dev-server --history-api-fallback --watch --port 3000 --mode development --hotOnly'
10 silly lifecycle ]
11 silly lifecycle saleor-site@0.7.0~start: Returned: code: 1  signal: null
12 info lifecycle saleor-site@0.7.0~start: Failed to exec start script
13 verbose stack Error: saleor-site@0.7.0 start: `cross-env NODE_ENV=develop webpack-dev-server --history-api-fallback --watch --port 3000 --mode development --hotOnly`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid saleor-site@0.7.0
15 verbose cwd /home/user/workspace/frontend
16 verbose Linux 4.19.0-8-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v12.16.1
19 verbose npm  v6.13.7
20 error code ELIFECYCLE
21 error errno 1
22 error saleor-site@0.7.0 start: `cross-env NODE_ENV=develop webpack-dev-server --history-api-fallback --watch --port 3000 --mode development --hotOnly`
22 error Exit status 1
23 error Failed at the saleor-site@0.7.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by javadfarah** [comment]
same here

**Comment by maarcingebala** [comment]
We've created the [saleor-platform](https://github.com/mirumee/saleor-platform) repo to set up all components of Saleor at once, can you see if this works for you?

**Comment by javadfarah** [comment]
@maarcingebala  thanks for your reply .
i wounder why salor-storefront has same dependency with two diffrent versions. 
i can't install two diffret versions of same pckage

ok i will check saleor-platform !

**Comment by solafakhaled** [comment]
I have the same issue

**Comment by mehrdad-shokri** [comment]
Getting the same error here. with default Dockerfile on storefront

**Comment by solafakhaled** [comment]
I solved the problem by deleting the docker container and resetting it. Make sure all the components are available in the container before proceeding. You might be asked to use the ‘’ notation

**Comment by mehrdad-shokri** [comment]
@solafakhaled I've solved that for now. But now storefront(localhost:3000) returns error indicating graphql API(localhost:8000/graphql) isn't accessible. I've tried to give storefront the same network that api is on but no luck. api is running inside docker container and storefront and api are on the same network so I have no guess why it can't find graphql api

**Comment by mehrdad-shokri** [comment]
@solafakhaled I've solved that for now. But now storefront(localhost:3000) returns error indicating graphql API(localhost:8000/graphql) isn't accessible. I've tried to give storefront the same network that api is on but no luck. api is running inside docker container and storefront and api are on the same network so I have no guess why it can't find graphql api

**Comment by mehrdad-shokri** [comment]
@solafakhaled I've solved that for now. But now storefront(localhost:3000) returns error indicating graphql API(localhost:8000/graphql) isn't accessible. I've tried to give storefront the same network that api is on but no luck. api is running inside docker container and storefront and api are on the same network so I have no guess why it can't find graphql api

**Comment by mehrdad-shokri** [comment]
@solafakhaled I've solved that for now. But now storefront(localhost:3000) returns error indicating graphql API(localhost:8000/graphql) isn't accessible. I've tried to give storefront the same network that api is on but no luck. api is running inside docker container and storefront and api are on the same network so I have no guess why it can't find graphql api

**Comment by solafakhaled** [comment]
I’ve seen someone trying to solve this issue by creating an .env file and
configuring the 8000/graphql in it. Others were trying by changing docker
config, hope you find a solution in the following link :
https://spectrum.chat/saleor/saleor-storefront/localhost-3000-not-working-on-initial-setup~7eb8da70-739b-40f7-b148-c80d08f121c5?authed=true

في ثلاثاء، ٦ يوليو، ٢٠٢١ في ٣:١٩ م، كتب Mehrdad Shokri <
***@***.***>:
