### ISSUE TITLE
CORS error in Heroku demo

### ISSUE THREAD

**Issue by JesusPuga** [mirumee/saleor-storefront#594]
### What I'm trying to achieve
Deploy saleor-storefront demo to heroku,

### Steps to reproduce the problem
1. Got to https://github.com/mirumee/saleor-storefront and click in deploy to heroku
2. Wait until the process finish

### What I expected to happen
I should be able to see the saleor-frontend from my heroku account. 

### Screenshots
![Captura de pantalla 2020-02-05 a la(s) 17 02 05](https://user-images.githubusercontent.com/16035717/73891379-bed22400-4839-11ea-8cbe-dbfc09a854f1.png)

**System information**
Operating system: macOS Sierra
Browser:Google Chrome

**Comment by karolkielecki** [comment]
Hello @JesusPuga. Thanks for reporting this issue. We'll investigate what's causing this error. Maybe it's something on our side.

**Comment by JesusPuga** [comment]
@karolkielecki Thanks  :j

**Comment by karolkielecki** [comment]
@JesusPuga Hey there! If you would like to test it, please use this URL: https://pwa.demo.saleor.rocks/graphql/  

We should change it on our side, thanks for reporting! If you have any questions or feedback, don't hesitate to contact us. You can also reach me on Gitter or Spectrum (@karolkielecki)

**Comment by JesusPuga** [comment]
Hi @karolkielecki , yep it worked, but just starting a new project in heroku. I tried changing de variable in my old project and it did not work, it did not recognize the new value. I tried cleaning the cache and restarting the dyno from heroku.

Example changing the variable: 

![Captura de pantalla 2020-02-10 a la(s) 14 56 59](https://user-images.githubusercontent.com/16035717/74189249-ae44f380-4c15-11ea-98d2-368d89d75563.png)

![Captura de pantalla 2020-02-10 a la(s) 14 49 29](https://user-images.githubusercontent.com/16035717/74189268-b4d36b00-4c15-11ea-8e13-2af6a7b8339a.png)

Starting a new project:

![Captura de pantalla 2020-02-10 a la(s) 14 57 26](https://user-images.githubusercontent.com/16035717/74189352-d3396680-4c15-11ea-8dbb-e188c177eab3.png)


So, does it mean that there is an extra process when we change our API_URL?

**Comment by karolkielecki** [comment]
It seems you have only set up the environment variable, but that variable should be set up before you build the storefront. You have to run the command 'npm run build', and the environment variable should direct to new URL. That's why it works with the new dyno, because storefront has been rebuilt
