### ISSUE TITLE
 "Environment variable API_URI not set"

### ISSUE THREAD

**Issue by Ku3a** [mirumee/saleor-storefront#595]
I try starting the project but I have an issue with .env file. 
I created .env with API_URI=http://localhost:8000/graphql/ but after npm start I have an error: 

<img width="1093" alt="Zrzut ekranu 2020-02-6 o 00 39 22" src="https://user-images.githubusercontent.com/18117278/73893174-31aebf80-4879-11ea-939a-72ba5dc1a077.png">

P.S. In saleor-dashboard all works fine. 

**System information**
Operating system: macOS Catalina
node: v10.17.0

**Comment by maarcingebala** [comment]
Hey, from what I see there is a little inconsistency - saleor-dashboard uses `require("dotenv").config();` while I don't see it in this app. We'll fix this; in the meantime, you can add this line at the top of webpack.config.js or set the `API_URI` manually in the shell where you're running the app.

**Comment by maarcingebala** [comment]
Wow that was quick 😀
