### ISSUE TITLE
Problem setting API_URI

### ISSUE THREAD

**Issue by gabernalt** [mirumee/saleor-storefront#633]
### What I'm trying to achieve
After deploying Saleor, I want to run saleor-storefront and saleor-dashboard

### Steps to reproduce the problem
1. Successfully installed Saleor following the steps in: https://docs.saleor.io/docs/next/getting-started/installation-windows/
2. Started installing saleor-storefront following the steps in https://github.com/mirumee/saleor-storefront/
3. Installed NPM dependencies: npm i
4. Had previously (unsuccessfully) tried to to set the API_URI environment variable to point to http://localhost:8000/graphql/. Tried defining it in 1. saleor-storefront/app.json, 2. saleor/app.json, 3. saleor-storefront/config/webpack/config.base.js,

Might be a silly question but I'm an entrepreneur, not a developer, and I'm struggling a bit following the documentation, thanks.
btw, same thing is happening when trying to install saleor-dashboard

### What I expected to happen
Successfully running npm start and accessing the storefront on http://localhost:3000

### Log
(Saleor) C:\Users\Tavo\Dev\Saleor\saleor\saleor-storefront>npm start

    saleor-site@0.7.0 start C:\Users\Tavo\Dev\Saleor\saleor\saleor-storefront
    cross-env NODE_ENV=develop webpack-dev-server --history-api-fallback --watch --port 3000 --mode development --hotOnly

C:\Users\Tavo\Dev\Saleor\saleor\saleor-storefront\config\webpack\config.base.js:11
throw new Error("Environment variable API_URI not set");
^

Error: Environment variable API_URI not set
at Object. (C:\Users\Tavo\Dev\Saleor\saleor\saleor-storefront\config\webpack\config.base.js:11:9)
at Module._compile (internal/modules/cjs/loader.js:1158:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
at Module.load (internal/modules/cjs/loader.js:1002:32)
at Function.Module._load (internal/modules/cjs/loader.js:901:14)
at Module.require (internal/modules/cjs/loader.js:1044:19)
at require (internal/modules/cjs/helpers.js:77:18)
at Object. (C:\Users\Tavo\Dev\Saleor\saleor\saleor-storefront\webpack.config.js:6:20)
at Module._compile (internal/modules/cjs/loader.js:1158:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor-site@0.7.0 start: cross-env NODE_ENV=develop webpack-dev-server --history-api-fallback --watch --port 3000 --mode development --hotOnly
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the saleor-site@0.7.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Tavo\AppData\Roaming\npm-cache_logs\2020-02-27T20_35_00_021Z-debug.log

**System information**
Operating system: Windows 10
Python 3.8.1
Node.js version 12.14.1
PostreSQL 10.12
GTK3+ for Win64
Build Tools 2017 v 14.24

**Comment by Pyrross** [comment]
Hi Gabernalt. Why did you close the issue? Did you fix it? :)
I am having the same issue.

**Comment by abdulmuhaimin-work** [comment]
I solved it by creating the .env file in the root folder. in the file I just add this one line
API_URI=http://localhost:8000/graphql/

**Comment by WahabShah23** [comment]
I am getting error when running npm start. It says to Environment variable API_URI not set. In app.json i changed the value to the one mentioned but still error is there.

The value property of API_URI is what i have changed. Tell me if i need to do something differently or set the API_URI value somewhere else? Thank in advance.

  "env": {
    "API_URI": {
      "description": "URI of a running instance of Saleor GraphQL API",
      "value": "http://localhost:8000/graphql/"
    },
    "APP_MOUNT_URI": {
      "description": "URI at which the Dashboard app will be mounted",
      "value": "/"
    }
  },

**Comment by WahabShah23** [comment]
Never mind its resolved thanks to abdulmuhaimin's answer. Actually I tried his solution initially but what I was doing is that I created file environment.env file but it never worked. Later I removed the filename and set it to just the extension .env and viola, It worked!

**Comment by iamshrikantjha** [comment]
I have tired the command 
`export API_URI=http://localhost:8000/graphql/`

It worked for me for the first but when the next time I tried to setup everything again it is just throwing some error

> GraphQL error: Error decoding signature

The saleor and saleor-dashboard is working fine but only saleor frontstore is throwing this error.

![Screenshot from 2020-05-16 06-18-03](https://user-images.githubusercontent.com/22591983/82106462-c2c9e800-973e-11ea-953a-921cc65e9a2e.png)


The rest of the UI is loading fine but the places where frontend have to display images or data from backend. It is showing the following error

> GraphQL error: Error decoding signature

**Comment by nintran1995** [comment]
> I solved it by creating a .env file in the root folder. in the file I just add this one line:
> API_URI=http://localhost:8000/graphql/

Why we must add it but does not on the document.

**Comment by Unforgivenbad** [comment]
1- Add the lines bellow to: /root/.bashrc
2- run this command: source ~/.bashrc
3- try npm start if is not working then reboot your server

export ALLOWED_HOSTS=51.25.25.95
export ALLOWED_CLIENT_HOSTS=51.25.25.95
export DEBUG=True
export SECRET_KEY='ffffd7d8f78d7f878fd7@!!!'
export INTERNAL_IPS=127.0.0.1,51.25.25.95,
export DEFAULT_COUNTRY=US
export DEFAULT_CURRENCY=USD
export APP_MOUNT_URI=/dashboard/
export API_URI=http://51.25.25.95:8000/graphql/

**Comment by opticrew** [comment]
@abdulmuhaimin-work In which root folder do you create the ".env file" ? In the saleor-plaform folder or the saleor-storefront folder ?
