### ISSUE TITLE
Error while checking out as Guest

### ISSUE THREAD

**Issue by Dostonbek1** [mirumee/saleor-storefront#642]
### What I'm trying to achieve
I'm trying to do checkout as a guest without logging in.

### Steps to reproduce the problem
1. Add a product to the basket
2. Checkout as Guest
3. Fill out Shipping Address
4. Click Continue to Shipping

### What I expected to happen
I expected that it would take me to the Shipping Method (second part of the checkout), but it just stays there. I traced the error to the response from the backend, and it gives a "Permission Denied" error. 

### Screenshots
![Selectionshot_2020-03-05_09:54:39](https://user-images.githubusercontent.com/31990136/75995523-8d955400-5eca-11ea-97c2-02f1db17bd7f.png)
![Selectionshot_2020-03-05_09:54:57](https://user-images.githubusercontent.com/31990136/75995566-9e45ca00-5eca-11ea-8e97-105977288736.png)

**System information**
Operating system: Linux
Browser: Firefox and Chrome

**Comment by karolkielecki** [comment]
@Dostonbek1 Hello! Do you use a master branch or the latest stable version 2.9.1?

**Comment by Dostonbek1** [comment]
@karolkielecki 
Hey! I'm using the latest stable version 2.9.1.

**Comment by maarcingebala** [comment]
I can confirm that there is an issue if you're using Saleor 2.9.1 with Storefront 0.7.0. What I could suggest is upgrading the Storefront version to `master` as it seems to be working fine there (with 2.9.1 on the backend side).

**Comment by Dostonbek1** [comment]
@maarcingebala I tried on the master branch and it works there fine, and I was able to do a complete checkout. Thank you.
