### ISSUE TITLE
 the dialog disappeared when you click out of dialog

### ISSUE THREAD

**Issue by appleyuchi** [mirumee/saleor-storefront#643]
when you click out of dialog of "address"
then the dialog disappeared.
This is bad experience.

I hope I can make a decision whether to make this diaglog `turn off` or `turn on`
by clicking "X" on the top-right of the dialog
![湖北升分](https://user-images.githubusercontent.com/27613483/76187847-6cf23480-6211-11ea-8356-edf05aa66270.png)

**Comment by appleyuchi** [comment]
@karolkielecki Thanks for your help.it works.
besides,could you tell me how to change the settings if
I don't want the dialog disappear when I click out of the dialog?
Thanks

**Comment by karolkielecki** [comment]
As far as I know, it's not possible to change it for now. We'll discuss it. If you have any questions or feedback, don't hesitate to let us know.

**Comment by krzysztofwolski** [comment]
We are not planning to implement this soon - all models share their behavior.
