### ISSUE TITLE
Why we need to "ADD NEW ADDRESS"again and again?

### ISSUE THREAD

**Issue by appleyuchi** [mirumee/saleor-storefront#645]
### What I'm trying to achieve
…
**Thanks for your huge work,this project is really an artwork.**
I don't want to input my address again and again after I have `fully charged` many orders
could I require such a feature from you geniuses~?

### Describe a proposed solution
could you add an button in the picture such as "use previous address" 
if it's convenient to you or when you have time?
Much Thanks

### Other solutions I've tried and won't work
…

### Screenshots or mockups

![需要增加新地址](https://user-images.githubusercontent.com/27613483/76325472-4c65cf80-6322-11ea-8c4d-0c27831a324a.png)

**Comment by maarcingebala** [comment]
It's implemented, but you need to log in to a user account to use that feature. 

Here you can log in:
![image](https://user-images.githubusercontent.com/5421321/76326563-18ba8380-62e9-11ea-8edd-326d4eba6907.png)

After placing an orders as a registered customer your addresses will be saved and you'll be able to reuse them later:

![image](https://user-images.githubusercontent.com/5421321/76326528-0b9d9480-62e9-11ea-9eec-592e6b6e077e.png)

**Comment by appleyuchi** [comment]
@maarcingebala 
Thanks for your replies.
To test it,I create a new account....
I found:
**after the new account make an order(status:charged in saleor-front and fufiled  in saleor-dashboard)**
then,
**the new account must log out,otherwise,previous address will not occur after I press F5 buttion many times**,is this my false impression?

**Comment by karolkielecki** [comment]
@appleyuchi Thanks for reporting. We'll investigate it as soon as we can. Once I have more information regarding this issue, I will update you.

**Comment by appleyuchi** [comment]
Thank you ~

**Comment by orzechdev** [comment]
@appleyuchi We have recently released new checkout, and I have verified it fixed the issue, logout and login is now not required to update available addresses in checkout.
