### ISSUE TITLE
Integrating Saleor Storefront into an existing static site

### ISSUE THREAD

**Issue by thewjones** [mirumee/saleor-storefront#650]
### What I'm trying to achieve

Integration of Saleor Storefront into an existing static site (eg Hugo)

### Describe a proposed solution

I think one particular use-case of storefront is to extend an existing site with an ecommerce system. An online business / brand may want to manage a lot extra content like blogs, testimonials, form inputs, other supporting information. I know it's possible to add static pages to Saleor but this functionality is limited.

Could integration into existing sites or other static generators be supported / documented?

**Comment by karolkielecki** [comment]
@thewjones Hi there! Thank you for your feedback. Currently, there are no docs related to this topic. I'll pass your suggestion to the team, and we'll discuss it. If I have any news, I'll let you know.
