### ISSUE TITLE
what's the error about dclog.qly360.com/

### ISSUE THREAD

**Issue by appleyuchi** [mirumee/saleor-storefront#651]
### What I'm trying to achieve
…

### Steps to reproduce the problem
1. saleor-storefront in VPS deployment
2. when I want to register,I press F12
I get ERROR in my webpage:
ERR:
dclog.qly360.com/statistics.do?updated=false&browser=chrome&guid=9a14b9b7-5b86-02e3-5d83-43c3c0a421cc&version=1.1.6_2020%2F1%2F28&systemName=qly_pv&shopName=&visitName=&ref=&href=http%253A%252F%252F106.14.24.151%253A3000%252F&state=&life=&show_plugin=0&isSeller=&plugin_type=qly&timestamp=1584263819716:1 GET http://dclog.qly360.com/statistics.do?updated=false&browser=chrome&guid=9a14b9b7-5b86-02e3-5d83-43c3c0a421cc&version=1.1.6_2020%2F1%2F28&systemName=qly_pv&shopName=&visitName=&ref=&href=http%253A%252F%252F106.14.24.151%253A3000%252F&state=&life=&show_plugin=0&isSeller=&plugin_type=qly&timestamp=1584263819716 net::ERR_EMPTY_RESPONSE

### What I expected to happen
…

### Screenshots

![复杂](https://user-images.githubusercontent.com/27613483/76698695-040f2e80-66e1-11ea-8ee5-f9231861e080.png)

**System information**
Operating system: 
Browser:

**Comment by appleyuchi** [comment]
Where am I wrong?
and which file did I miss for configuration?
Thanks for your help in advance.

**Comment by karolkielecki** [comment]
I think it's not on our side. Maybe the issue comes from qly360.com.

**Comment by appleyuchi** [comment]
> I think it's not on our side. Maybe the issue comes from qly360.com.

test ip is in CHINA,maybe it's  because of the Internet Wall of Government
