### ISSUE TITLE
trying to show payment options

### ISSUE THREAD

**Issue by jkain88** [mirumee/saleor-storefront#653]
![saleor](https://user-images.githubusercontent.com/36409853/76819093-42702f00-6842-11ea-8a32-ed2a4975b914.png)

**Comment by maarcingebala** [comment]
This is actually not fully implemented yet and in my opinion, navigation to this view should be hidden for now. We have all the components and API can return this data if you're using Stripe, so it's actually not that much work to get it all working. We'll try to fix it as soon as we can.

**Comment by olythy** [comment]
we are looking forward to having it ... :)

**Comment by krzysztofwolski** [comment]
Section will be activated again when all features will be available
