### ISSUE TITLE
Translations Management

### ISSUE THREAD

**Issue by olythy** [mirumee/saleor-storefront#656]
### What I'm trying to achieve
Hi there, the README contains information regarding with the translation but I did not see this functionality.
In the near future there will be any changes regarding the translations management?

**Comment by karolkielecki** [comment]
Hello @olythy. Thank you for pointing this out. Currently, that function is not available. I'll pass the issue to the team and we'll discuss it. If I have any news, I'll let you know.

**Comment by giovannipiccinelli** [comment]
@karolkielecki 
Hey! I have a live shop running on saleor. Would like to know whether this is a feature that will be implemented in the near future or whether I can rely on #399 to accomplish it on my own. 

Thanks!
