### ISSUE TITLE
The actual totalPrice is not returned from CartProvider/utils 

### ISSUE THREAD

**Issue by konstantinoschristomanos** [mirumee/saleor-storefront#663]
### What I'm trying to achieve
…
Changing totalPrice after adding quantity to a cartItem    
### Steps to reproduce the problem
1. Add a product to the cart and go to view bag
2. Change the product quantity

### What I expected to happen
Total price will have to change to Price*quantity

The problem is  on the CartProvider utils. The calculation of total price gets overridden

### Screenshots

![Screenshot from 2020-04-17 12-32-12](https://user-images.githubusercontent.com/42765075/79555009-966f6d00-80a7-11ea-8f73-cf488c89f7f9.png)
![Screenshot from 2020-04-17 12-34-08](https://user-images.githubusercontent.com/42765075/79555366-24e3ee80-80a8-11ea-9c49-b0d9fffeb55d.png)

**System information**
Operating system: 
Browser:

**Comment by konstantinoschristomanos** [comment]
#664

**Comment by orzechdev** [comment]
Thank you for contribution

**Comment by konstantinoschristomanos** [comment]
My pleasure
