### ISSUE TITLE
Adding to basket not possible - button is dimmed 

### ISSUE THREAD

**Issue by PiotrLaszczyk** [mirumee/saleor-storefront#666]
### Steps to reproduce the problem
I'm logged as user, user is activated. 
Issue: Cannot add any product in to basket - button is dimmed like on picture:
![Zrzut ekranu z 2020-04-21 00-58-59(4)](https://user-images.githubusercontent.com/19570394/79808267-9902e880-836d-11ea-984f-31bb63670e33.png)

1. I used tagged configuration: saleor:0.7.0 + storefront:2.9.0 + dashboard:2.0.0  -> issue was not visible
2. I switched in to: saleor:master + storefront:master + dashboard:master -> issue visible

**System information**
Operating system: localhost and heroku deployment
Browser: chrome, mozilla

Quick idea: 
As I'm creating products by api maybe I forgot to set some required params?
Maybe problem is that something need to be set like payments, quantity, some customer settings... just guessing,
Where should I look to enable this option? I'm quite confused now.

**Comment by orzechdev** [comment]
Do you have stock quantity > 0 for product set?

**Comment by PiotrLaszczyk** [comment]
There was no 'variant' created, only quantity set in product.
