### ISSUE TITLE
service-worker.js is missing

### ISSUE THREAD

**Issue by elcolie** [mirumee/saleor-storefront#674]
### What I'm trying to achieve
First run `storefront`

### Steps to reproduce the problem
1. Checkout `master` with `3cfdeef41e7f1ca60a50fb53a4ef8c7d3f89bf4f` commit
2. `npm start -- --host 0.0.0.0`

### What I expected to happen
No error message

### Screenshots
<img width="1273" alt="Pasted_Image_26_4_20_21_56" src="https://user-images.githubusercontent.com/18206728/80311315-31cfb300-8809-11ea-8dd4-3bd7ff198f15.png">

**System information**
Operating system: `node:10` docer image
Browser: Chrome `Version 81.0.4044.122 (Official Build) (64-bit)`

**Comment by elcolie** [comment]
Manually copy&paste to top most level

**Comment by maarcingebala** [comment]
Reopening as it's broken on `master`.
