### ISSUE TITLE
Add to cart button disabled because of cookies state

### ISSUE THREAD

**Issue by PiotrLaszczyk** [mirumee/saleor-storefront#682]
### What I'm trying to achieve
Im almost ready to put my shop under regular operation and during my internal testing stage I observed that:

on few tested pc: http:// and https:// working
on few tested pc: www.my.custom also was working but **on one browser  'add to cart' button was dimmed** - it was dimmed on all products

Thats tricky... why in some situations 'add to chart' button may be dimmed on unlogged user? I go deeper and discover that its because of cookies. After removal all tested pc/browsers start to behave in same manner.

So the question. Why cookies stored in web browser makes all products 'add to cart' buttons dimmed? Typical user never figure out that cookies need to be cleaned... what I changed in mean time was adding some new attributes to products, so information stored in cookies may be different than those actually available - but its just my suspicion.  Case is that it will be changed all the time, so users may face this issue. 

Operating system: 
Browser: Chrome 81.0.4044.129

**Comment by maarcingebala** [comment]
I believe this is fixed in 2.10.x
