### ISSUE TITLE
Shipping methods and warehouses

### ISSUE THREAD

**Issue by PiotrLaszczyk** [mirumee/saleor-storefront#684]
### What I'm trying to achieve
I configured 9 warehouses. Different products comes from different warehouses.
Each warehouse have its own 4 groups of shipping methods relevant to order size: S, M, L, XL. I select it by total order weight.

### Steps to reproduce the problem
Selecting product

### What I expected to happen
I should have only one option: shipping method related with warehouse connected with product (in stock). Based on weight one of option should be available 

Issue. All shipping methods from all warehouses are visible and available for customer. 
Selecting by weight works. Its 9 time S size available.

### Screenshots

![obraz](https://user-images.githubusercontent.com/19570394/80914502-48679400-8d4c-11ea-8d57-f462e986e1d4.png)

**Comment by PiotrLaszczyk** [comment]
Any plans to fix that? Its become problematic. Only shipping methods related with selected products(its warehouses) should be available..

**Comment by fowczarek** [comment]
Why are you create a new shipping zone for each warehouse? 
I think that in your case you should create one shipping zone and assign all warehouses to it.

**Comment by PiotrLaszczyk** [comment]
Imagine that there is one seller - company X. Company takes products from Y different external sources/other companies (warehouses) and ship directly from this company to customer. Its dropshipping... . 

So If You take 2 products from 2 warehouses You should have 2 delivery methods, 2 payments for it etc..

Second, 2 different warehouses may different delivery cost even for same type of delivery. 

So to implement typical dropshipping mode in to saleor I create warehouse to represent external vendor company and each of warehouse have few assigned shipping zones with delivery methods covering different package size. In fact there is few delivery methods per zone for S, M, L, XL package sizes... 

But actual sailor has a bug (in my opinion) as should only allow to select delivery method related with shipping zone assigned to its warehouse, not all  possible options .

**Comment by maarcingebala** [comment]
Adding dropshipping in Saleor would probably require a bit more work and it wasn't in the scope of the multi-warehouses feature. Also, the available shipping method in checkout don't depend on the number of warehouses so I'm not sure it's a bug, it's rather an assumption. If there are multiple warehouses shipping products to the same countries (zones), the shipping prices should be set to reflect this fact.

**Comment by PiotrLaszczyk** [comment]
Its not so many work to do to enable this in drop mode. Your multi-warehouse implementation opens that doors to be honest. 

What really left is handling delivery (different warehouse - different group of delivery methods) and summarizing cost of those. One vendor wants X.xx and anther Y.yy for sending similar package using same shipping company.. Those are different companies so have different policies.. that's why in general in drop You cannot use one common shipping zone for all warehouses. 

Anyway, really need that, so I will try to do this by my own.
