### ISSUE TITLE
When product is unavailable I shouldn't get message about max quantity

### ISSUE THREAD

**Issue by IKarbowiak** [mirumee/saleor-storefront#692]
### What I'm trying to achieve
When a specific variant is unavailable and you choose it from the sidebar, you get a message: `Maximum quantity is 0` and at the same time insert 0 is forbidden (of course inserting 0 doesn't have any sense). So info should be probably different. For example, informing that product is unavailable.

### Steps to reproduce the problem
On clear data, after running populatedb
1. Got to Footwear/White Plimsolls
2. Choose Shoes Size 40

### What I expected to happen
In this case, info about the max quantity shouldn't appear. Instead, I should get the info that the product is unavailable.

### Screenshots

![image](https://user-images.githubusercontent.com/40886528/81066883-19812780-8ede-11ea-8471-c1aa893c0abd.png)

**Comment by wael-mohamed** [comment]
I think it should be invisible automatically or marked as out of stock

**Comment by subhadeepdas91** [comment]
Facing similar issue, even after maintaining stock at warehouse
please find the screenshot for reference
![Screenshot_20200512_004119](https://user-images.githubusercontent.com/29140664/81602023-7f434700-93e9-11ea-980d-17144cb26542.png)

**Comment by thewjones** [comment]
> Facing similar issue, even after maintaining stock at warehouse
> please find the screenshot for reference
> ![Screenshot_20200512_004119](https://user-images.githubusercontent.com/29140664/81602023-7f434700-93e9-11ea-980d-17144cb26542.png)

Trying configuring your Shipping Zones in Configuration > Shipping Methods. Then ensure that a Warehouse is associated with the Shipping Zone.

**Comment by krzysztofwolski** [comment]
Fixed
![image](https://user-images.githubusercontent.com/5188636/87168836-5d721d80-c2cf-11ea-8981-af162b50169b.png)

**Comment by ramirovazq** [comment]
So, the correct answer is: "Trying configuring your Shipping Zones in Configuration > Shipping Methods. Then ensure that a Warehouse is associated with the Shipping Zone." ? right?
