### ISSUE TITLE
dashboard has bold, storefront does not

### ISSUE THREAD

**Issue by elcolie** [mirumee/saleor-storefront#695]
### What I'm trying to achieve
Change content of `About` page

### Steps to reproduce the problem
1. dashboard `8f21681389f04834692677caf5cf7e9c72dab4db`
2. storefront `21f567085c40c8328f2e09126a10483be3a2db5c`
3. saleor `606f451877e278b5de542d8fd94f0debbf336ed1`

### What I expected to happen
Bold and line is match with `dashboard`

### Screenshots
![Pasted_Image_6_5_20_18_27](https://user-images.githubusercontent.com/18206728/81171817-43624900-8fc7-11ea-8a5a-8de08669b3ba.png)

![Pasted_Image_6_5_20_18_27](https://user-images.githubusercontent.com/18206728/81171875-65f46200-8fc7-11ea-8f78-6b4661b4149c.png)

**System information**
Operating system: Dockerfile node 10
Browser:`Version 81.0.4044.129 (Official Build) (64-bit)`

**Comment by krzysztofwolski** [comment]
@elcolie thanks for adding exact commit hashes, info and screenshots. It helps with debugging a lot :)
