### ISSUE TITLE
Razorpay integration in storefront is missing, though available in backend

### ISSUE THREAD

**Issue by ilanosm** [mirumee/saleor-storefront#702]
### What I'm trying to achieve
Enabling Razorpay in plugins, but it doesn't show in the payment options while checkout

**Comment by niteshldd** [comment]
Hi @ilanosm,

I think we have already fix available

https://github.com/mirumee/saleor-storefront/issues/147#issuecomment-612495444

 #147 this implementation is good for indian market. Can someone add this feature  in next  release ?

**Comment by ameendeerom** [comment]
I have the same issue

**Comment by parthlawate** [comment]
I've seen the same issue. While i see the Razor Pay gateway is available in saleor core repository and it can be configured from the saleor dashboard.. i cant get it to work in saleor-storefront.. 

Not sure it works in the new react-storefront either.. 

Is the backend feature complete & just needs to be implemented in the frontend ?
