### ISSUE TITLE
JSON-LD schema.org for pages / categories etc

### ISSUE THREAD

**Issue by Boquete** [mirumee/saleor-storefront#706]
Right now, google crawls correctly only product details, main page content.
It does not crawl categories, pages (for example About). 

Problem is, all those pages which are crawled by google are using schema.org , others are not.

Tool used to find what's the reason behind not indexing some pages by google correctly:
https://technicalseo.com/tools/mobile-first-index/
paste url of pages and all pages without structured data are not crawled as they should be.

**Comment by krzysztofwolski** [comment]
Seems to be easy to implement. API already has fields for that data.

**Comment by maarcingebala** [comment]
I think this should remain open @krzysztofwolski ?
