### ISSUE TITLE
Error - Maximum quantity is 0

### ISSUE THREAD

**Issue by sebasgoldberg** [mirumee/saleor-storefront#714]
### What I'm trying to achieve
Add a product to the cart in the storefront.
The product has stock in the default warehouse.

### Steps to reproduce the problem
1. Open a product page.
2. The message "Maximum quantity is 0" is there and it is not possible to add the product to the cart.

### What I expected to happen
Should be possible to add a product to the cart.

### Screenshots
![image](https://user-images.githubusercontent.com/1379852/82090637-51515180-96cc-11ea-9019-c36b2457ddc9.png)

**System information**
Operating system: Linux
Saleor: 2.10

**Comment by Ulisses1478** [comment]
Same here

**Comment by Ulisses1478** [comment]
tested and it is for sure using the stockQuantity

**Comment by fowczarek** [comment]
@sebasgoldberg 
Is your warehouse assigned to shipping zone that contains `DEFAULT_COUNTRY` from saleor `settings.py`?
 StockQuantit depends on `DEFAULT_COUNTRY` from saleor `settings.py`.

**Comment by krzysztofwolski** [comment]
Should be fixed by  #732
