### ISSUE TITLE
Saleor blank website when checkout

### ISSUE THREAD

**Issue by MartinSchere** [mirumee/saleor-storefront#725]
### What I'm trying to achieve
I'm trying to complete a checkout with an authorized user.

### Steps to reproduce the problem
1. Login as an user
2. Add an item to basket
3. Go to checkout
4. Add an adress
5. Click on "Add"

### What I expected to happen
Just the normal checkout. Instead, it returns a blank website with the URL of https://demo.saleor.io/checkout/address (in the demo)

### Screenshots

**System information**
Operating system: Windows 10 
Browser: Chrome

**Comment by krzysztofwolski** [comment]
![image](https://user-images.githubusercontent.com/5188636/87171616-34538c00-c2d3-11ea-930e-273d5b83b502.png)

@Elrocho does the issue still occurs? I cannot reproduce it

**Comment by Metastasis** [comment]
@krzysztofwolski yes, just click "Add" when address form is not filled

You will see then

![image](https://user-images.githubusercontent.com/4483522/91204379-ab6ea380-e70c-11ea-83e8-49cce9ab8bdc.png)
