### ISSUE TITLE
Unable to load product in cart.. error thrown

### ISSUE THREAD

**Issue by giovannipiccinelli** [mirumee/saleor-storefront#732]
### What I'm trying to achieve
Hello, after the latest realease I have been trying to merge the most recent changes without success. Once I add products to the cart the sidebar is unable to show them.. I get the following error "Fields "quantityAvailable" conflict because they have differing arguments"

### Steps to reproduce the problem
1. Merge the most recent changes
2. Add products to cart
3. Click on the cart sidebar to display the added products

### What I expected to happen
1. See the added products

### Screenshots
![Schermata 2020-05-23 alle 12 19 28](https://user-images.githubusercontent.com/7911077/82728380-254b5700-9cf0-11ea-9e1a-32c85974317e.png)

**System information**
Operating system: Os
Browser: Chrome

**Comment by orzechdev** [comment]
Thank you for opened issue. From what I see, we use sometimes `quantityAvailable(countryCode: $countryCode)` with countryCode argument, and sometimes `quantityAvailable` without. Moreover sometimes this field is defined in fragment and sometimes outside. So, to fix it, I guess quantityAvailable field should be defined only once for each query and mutation, and have always countryCode as an argument.

**Comment by advanisunny3** [comment]
Sorry Dawid, I don't understand what changes are necessary to have quantityAvailable fields defined only once. I have defined DEFAULT_COUNTRY=IN, it that needed to be removed?
Or any other config changes are required? Please advice.

**Comment by kkx** [comment]
got the same error, unable to get cart drawable open because cart products are not correctly added. pretty frustrated, specially for newbie like me who want to set up the environment locally to evaluate the project comparing it with other products in the market.

**Comment by ridiaz** [comment]
Got the same error too.  Super rare.  I can't even found the text of that error.  Seems that come from the server, but I can't find the line.  Any help will be appreciated

**Comment by maarcingebala** [comment]
Hey, this issue should be fixed by PR https://github.com/mirumee/saleor-storefront/pull/738. Can you pull the latest master and confirm it is fixed now @ridiaz @kkx @giovannipiccinelli?

**Comment by maarcingebala** [comment]
We tested it and it seems to be working fine now. We'll release this fix as `2.10.2` version of the storefront.
