### ISSUE TITLE
Unable to view the cart sidebar

### ISSUE THREAD

**Issue by mridang** [mirumee/saleor-storefront#734]
### What I'm trying to achieve
I'm trying to view the cart/minicart

### Steps to reproduce the problem
1. Add a product to the cart
2. Click the minicart button on the top-right

### What I expected to happen
I expect to be on the cart page with an itemised listing of the products in the cart

### Screenshots
<img width="1439" alt="Screenshot 2020-05-26 at 10 16 20" src="https://user-images.githubusercontent.com/327432/82861343-f7f1e980-9f39-11ea-9a30-ceef2886f092.png">

**System information**
Operating system: MacOS Mojava
Browser: Chrome 81
Saleor-Storefront: 2.10.1

**Comment by mridang** [comment]
I just noticed that when adding the product to the cart, there is an error in the console. 
`graphql.error.base.GraphQLError: Fields "quantityAvailable" conflict because they have differing arguments. Use different aliases on the fields to fetch both if this was intentional."
`

**Comment by Aminyazdanshenas** [comment]
hey I have some sort of the same issue. 
whenever I add Item to my shopping web respone is kind of wired (the border of price tag became red) and when I click the basket I end up with loading dots and nothing comes up. 
can anyone help me with this issue


 
![Annotation 2020-05-26 144358](https://user-images.githubusercontent.com/30069462/82889147-8dec3b00-9f5f-11ea-834a-8f2211dcd065.png)

**Comment by krzysztofwolski** [comment]
#732 should address those issues, any changes?

**Comment by Sanaj2060** [comment]
This issue has been resolved on the latest commit. Check out the Saleor-Storefront master.

> Personal verification performed on local deployment.

**Comment by mridang** [comment]
I think #732 covers it. Thx everyone.
