### ISSUE TITLE
saleor cart doen't work

### ISSUE THREAD

**Issue by Aminyazdanshenas** [mirumee/saleor-storefront#736]
whenever I add Item to my shopping list , the web response is kind of weird  (the border of price tag became red) and when I click the basket I end up with loading dots and nothing comes up. 
can anyone help me with this issue

 
![Annotation 2020-05-26 144358](https://user-images.githubusercontent.com/30069462/82889147-8dec3b00-9f5f-11ea-834a-8f2211dcd065.png)

_Originally posted by @Aminyazdanshenas in https://github.com/mirumee/saleor-storefront/issues/734#issuecomment-633938943_

**Comment by krzysztofwolski** [comment]
Any errors at browser console?
how did u install saleor? Was anything modified?

**Comment by Sanaj2060** [comment]
It has been solved, please closed the issue.
