### ISSUE TITLE
Whats the best place for adding EAN/GTIN/MPN/ISBN

### ISSUE THREAD

**Issue by PiotrLaszczyk** [mirumee/saleor-storefront#758]
### What I'm trying to achieve
I would like to add numbers like EAN/GTIN... in to my products but in that way that it would be visible in storefront but also prepared for google bots.. 

Whats the best approach in case of storefront. Put it as attribute? Or maybe in description? Do You plan to add this parameter somehow?

**Comment by maarcingebala** [comment]
One solution is to use Metadata API - the issue with this is now that it's only supported in GraphQL (that's primary use-case) and there is no dashboard UI. Other option would be to create dedicated product attributes for these values, assume constant attribute slugs that could be later fetched in JS and used for bots.

**Comment by PiotrLaszczyk** [comment]
Thx for suggestions.
