### ISSUE TITLE
Is it possible to run storefront website via aws S3 site hosting feature. 

### ISSUE THREAD

**Issue by neerajgupta2407** [mirumee/saleor-storefront#764]
### What I'm trying to achieve
Build the project and upload build(html, css, images and everything) on Aws S3 so that we can utilize the AWS bucket site hosting feature.

### Describe a proposed solution
...

### Other solutions I've tried and won't work
…

**Comment by neerajgupta2407** [comment]
@karolkielecki Thanks. It does work with `npm run build`.  I deployed to s3 and site was working fine. The only issue is with  dynamic url support since S3 is CDN and not a webhosting.
So i deployed the storefront on my EC2 apache with enabling  mod_rewrite and its perfectly working fine.

**Comment by dominik-zeglen** [comment]
Good to hear everything's working!
