### ISSUE TITLE
Autocomplete form Chrome is on the top of the country selector.

### ISSUE THREAD

**Issue by fowczarek** [mirumee/saleor-storefront#768]
Autocomplete form Chrome is on the top of the country selector.

### Screenshots
![image](https://user-images.githubusercontent.com/43955230/84253495-4db8bb00-ab10-11ea-86e7-203b7e9a35d9.png)

**System information**
Operating system:  Ubuntu 18.04
Browser: Chrome

**Comment by krzysztofwolski** [comment]
Turned off autocomplete for this field.
