### ISSUE TITLE
Autocomplete form Chrome has swapped values between `City` and `State`.

### ISSUE THREAD

**Issue by fowczarek** [mirumee/saleor-storefront#769]
Auto-complete form Chrome has swapped values between `City` and `State`.

### Steps to reproduce the problem
1. Configure Chrome auto-complete.(chrome://settings/addresses)
2. Fill any storefront form using auto-complete.

### Screenshots
![image](https://user-images.githubusercontent.com/43955230/84253591-6b862000-ab10-11ea-94bb-1a633a7650ed.png)

![image](https://user-images.githubusercontent.com/43955230/84253617-76d94b80-ab10-11ea-8f85-d5165a9dd01f.png)

**System information**
Operating system: Ubuntu 18.04
Browser: Chrome

**Comment by krzysztofwolski** [comment]
Fixed in #777
