### ISSUE TITLE
Language selector

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor-storefront#798]
### What I'm trying to achieve
Have a way to select the language for the storefront.

### Definition of Done

- [ ] modal for language selector should be working both on mobile and desktop
- [ ] footer displays currently chosen language 
- [ ] clicking on `change` located in footer launches language selection modal
- [ ] as default use the English language - we'll switch to browsers default language when translations will be complete
- [ ] when language is changed, save this preference in localStorage 

### Screenshots or mockups

Desktop design for the modal window:
![image](https://user-images.githubusercontent.com/5188636/86371177-e14d5980-bc80-11ea-9366-2bbf449f3b46.png)

Mobile design for the modal window:
![image](https://user-images.githubusercontent.com/5188636/86371935-d646f900-bc81-11ea-80b0-bf3b99ccfa67.png)

Design for footer section:
![image](https://user-images.githubusercontent.com/5188636/86373597-dd6f0680-bc83-11ea-8bc4-26958db53324.png)

Figma:
https://www.figma.com/file/l4s9dKj8Ch356prygQAxrv/STOREFRONT-CHANGE-LANGUAGE?node-id=0%3A1

Flag icons:
https://github.com/yammadev/flag-icons

**Comment by krzysztofwolski** [comment]
Note: We are going to use flags as language icons in the initial implementation of this modal. Later on, it will be modified and we will also introduce region (country) selection where the footer flag icon will be moved. 

For curious, why `flag !== language`:
https://localizejs.com/articles/why-using-flag-icons-can-confuse-your-users/

**Comment by przlada** [comment]
@krzysztofwolski thanks for materials. I'll try to tackle this "Language selector" feature next week because now I'm in the middle of model translations.

**Comment by goldenMetteyya** [comment]
hi has progress been made on this ?

**Comment by przlada** [comment]
Not yet, it is still work in progress. Unfortunately, I couldn't find time for it this week. I plan to make PR next week

**Comment by maarcingebala** [comment]
Not stale I guess? cc @krzysztofwolski
