### ISSUE TITLE
Unable to set API_URI

### ISSUE THREAD

**Issue by patrykwegrzyn** [mirumee/saleor-storefront#837]
### What I'm trying to achieve
I am unable to set API_URI via env variable it always defaults to localhost

### Steps to reproduce the problem
1. set `API_URI="http://saleor-api.default:8000/graphql/"`
2. deploy container 
3. check env var inside of  container `echo $API_URI > http://saleor-api.default:8000/graphql/`
4. open js console in the browser all api requests points to `http://localhost:8000/graphql/`

### What I expected to happen
`API_URI` env variable to be respected  and points to `http://saleor-api.default:8000/graphql/`

All containers are build from Dockerfile provided in  `2.10.4.zip`
I'm also experiencing the same issue with Dash container `2.10.0.zip`

I am using k8s internal dns

**Comment by Swanhtet-grc** [comment]
Did you fix API_URI in Dockerfile.dev?
I fixed in Dockerfile.dev and run docker compose build again.
And API_URI changed.

**Comment by patrykwegrzyn** [comment]
I do not try  Dokerfile.dev assumed its not for production use

**Comment by patrykwegrzyn** [comment]
`Dockerfile.dev` does not do build phase, I suspect there is something wrong with `npm run build` ?

**Comment by Swanhtet-grc** [comment]
Oh okay. Never mind. You used Dockerfile file. 
Did you fix API_URI in the Dockerfile and build the image?
I faced a problem similar to yours. What I did is I built the docker image again after changing API_URI.

**Comment by patrykwegrzyn** [comment]
Looks like it was caching issue works now
