### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by nalimhahs** [mirumee/saleor-storefront#839]
### What I'm trying to achieve
To deploy the storefront using netlify. Netlify deploy fails saying build failed. Tried the build locally on both master and 2.10 both fails. Npm logs below. BUT a dist folder is created which can be served via a local server (and works fine so far). So I'm guessing some script after the build fails?

### Steps to reproduce the problem
1. Set the API_URI env
2. `npm run build`

### What I expected to happen
Execute a successful build.

### Screenshots
https://pastebin.com/EwfSe5rU (Log from console).

npm debug logs

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/milan/.nvm/versions/node/v12.16.0/bin/node',
1 verbose cli   '/home/milan/.nvm/versions/node/v12.16.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle saleor-site@2.10.0~prebuild: saleor-site@2.10.0
6 info lifecycle saleor-site@2.10.0~build: saleor-site@2.10.0
7 verbose lifecycle saleor-site@2.10.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle saleor-site@2.10.0~build: PATH: /home/milan/.nvm/versions/node/v12.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/milan/Projects/saleor-platform/saleor-storefront/node_modules/.bin:/home/milan/.nvm/versions/node/v12.16.0/bin:/home/milan/.yarn/bin:/home/milan/.config/yarn/global/node_modules/.bin:/home/milan/anaconda3/bin:/home/milan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/default-java/bin:/home/user_directory/Android/Sdk/tools:/home/user_directory/Android/Sdk/platform-tools
9 verbose lifecycle saleor-site@2.10.0~build: CWD: /home/milan/Projects/saleor-platform/saleor-storefront
10 silly lifecycle saleor-site@2.10.0~build: Args: [ '-c', 'webpack -p' ]
11 silly lifecycle saleor-site@2.10.0~build: Returned: code: 2  signal: null
12 info lifecycle saleor-site@2.10.0~build: Failed to exec build script
13 verbose stack Error: saleor-site@2.10.0 build: `webpack -p`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/home/milan/.nvm/versions/node/v12.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/milan/.nvm/versions/node/v12.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid saleor-site@2.10.0
15 verbose cwd /home/milan/Projects/saleor-platform/saleor-storefront
16 verbose Linux 4.15.0-112-generic
17 verbose argv "/home/milan/.nvm/versions/node/v12.16.0/bin/node" "/home/milan/.nvm/versions/node/v12.16.0/bin/npm" "run" "build"
18 verbose node v12.16.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 2
22 error saleor-site@2.10.0 build: `webpack -p`
22 error Exit status 2
23 error Failed at the saleor-site@2.10.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**System information**
Operating system: Ubuntu 18.04
Browser: Chrome

**Comment by nalimhahs** [comment]
I fixed the issue by fixing some import-ordering errors. Correct me if I'm wrong, but i don't think the order of imports should affect the final build. Hence the build shouldn't fail for import ordering and other code cosmetic issues (especially for something trivial like alphabetical ordering of imports). Also if this is an issue, shouldn't it also be flagged while running the dev-server?

**Comment by umair-ilyas** [comment]
I am also facing the same problem:
i am new to javascript and currently i am working on open source project of **saleor.io**
When i run this command of `npm run build` , i got the below error in output and the app run perfectly on `npm start`:

    npm ERR! code ELIFECYCLE
    npm ERR! errno 2
    npm ERR! saleor-site@2.10.3 build: `webpack -p`
    npm ERR! Exit status 2
    npm ERR! 
    npm ERR! Failed at the saleor-site@2.10.3 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/umair/.npm/_logs/2020-08-06T09_09_26_905Z-debug.l


**The output of log is this:**

    17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
    18 verbose node v12.18.3
    19 verbose npm  v6.14.6
    20 error code ELIFECYCLE
    21 error errno 2
    22 error saleor-site@2.10.3 build: `webpack -p`
    22 error Exit status 2
    23 error Failed at the saleor-site@2.10.3 build script.
    23 error This is probably not a problem with npm. There is likely additional logging output above.
    24 verbose exit [ 2, true ]

Can you please help me out in this where i am doing wrong.

**Comment by nalimhahs** [comment]
@umair-ilyas hey, can you send me the full log that was shown in the terminal? Maybe I could help you.

**Comment by umair-ilyas** [comment]
@nalimhahs are you using master branch or any other branch?

**Comment by nalimhahs** [comment]
I've used the master, 2.10.4 and 2.10.0 (current).

**Comment by umair-ilyas** [comment]
https://github.com/mirumee/saleor-dashboard/issues/633
Can you please check this error too

**Comment by ShahrearBinAmin** [comment]
@nalimhahs  I'm also facing same error

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle saleor-site@2.10.4~prebuild: saleor-site@2.10.4
6 info lifecycle saleor-site@2.10.4~build: saleor-site@2.10.4
7 verbose lifecycle saleor-site@2.10.4~build: unsafe-perm in lifecycle true
8 verbose lifecycle saleor-site@2.10.4~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/shahrear/Projects/Sealor/Test/saleor-platform/saleor-storefront/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/shahrear/Android/Sdk/emulator:/home/shahrear/Android/Sdk/platform-tools:/usr/lib/jvm/jdk-11.0.8:/home/shahrear/Android/Sdk:/home/shahrear/Documents/BeneratorResource/databene-benerator-0.9.8-dist/databene-benerator-0.9.8:/home/shahrear/Android/Sdk:http://localhost:8000/graphql/:/usr/lib/jvm/jdk-11.0.8/bin
9 verbose lifecycle saleor-site@2.10.4~build: CWD: /home/shahrear/Projects/Sealor/Test/saleor-platform/saleor-storefront
10 silly lifecycle saleor-site@2.10.4~build: Args: [ '-c', 'webpack -p' ]
11 silly lifecycle saleor-site@2.10.4~build: Returned: code: 2  signal: null
12 info lifecycle saleor-site@2.10.4~build: Failed to exec build script
13 verbose stack Error: saleor-site@2.10.4 build: `webpack -p`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid saleor-site@2.10.4
15 verbose cwd /home/shahrear/Projects/Sealor/Test/saleor-platform/saleor-storefront
16 verbose Linux 5.4.0-42-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 2
22 error saleor-site@2.10.4 build: `webpack -p`
22 error Exit status 2
23 error Failed at the saleor-site@2.10.4 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by siphon-app** [comment]
Any fix for this?

**Comment by elkd** [comment]
This issue is still here on 2.11. npm version 8, node version 16 running on Ubuntu 20.
