### ISSUE TITLE
Can't enable Stripe Integration

### ISSUE THREAD

**Issue by nalimhahs** [mirumee/saleor-storefront#841]
I would like to know how to enable the stripe payment gateway in the storefront. I can see almost everything is implemented but can't seem to figure out how to enable it. I have enabled the toggle in the dashboard.

**Comment by krzysztofwolski** [comment]
Can't reproduce issue. Steps I've taken:

1. Go to http://localhost:9000/dashboard/plugins/mirumee.payments.stripe/
2. Set up keys / set as active 
![image](https://user-images.githubusercontent.com/5188636/89429818-53143980-d73e-11ea-947b-cdb5860370ea.png)
3. ![image](https://user-images.githubusercontent.com/5188636/89429917-6f17db00-d73e-11ea-80f3-e67dca3939fd.png)
4. Did checkout with stripe gateway, used test card from https://stripe.com/docs/testing
5. Completed order

Ive noticed interface in dashboard does not refresh after key set up, I've notified our team about the issue.



@nalimhahs how do you run saleor? Which version of api/dashboard you have?

**Comment by nalimhahs** [comment]
Hi, I'm using Saleor core deployed on a server (2.10.2). As for the dashboard I've hosted it on netlify (2.10). The storefront I'm using version 2.10.0 and am running it locally. I have done some modifications to the storefront, mostly styling, and I believe I haven't touched anything related to payments. Although I've enabled both the dummy and stripe payment options on the dashboard, neither shows up in the storefront. I have tried the same the unmodified version of the storefront (2.10.4) and still nothing shows up. But if you want to check the code of the storefront, it's here https://github.com/nalimhahs/nether-storefront.

![Screenshot from 2020-08-05 21-11-25](https://user-images.githubusercontent.com/42489509/89436189-84ebc700-d763-11ea-9107-d8cd947d6316.png)
This is the dashboard showing stripe being enabled.

![Screenshot from 2020-08-05 21-11-41](https://user-images.githubusercontent.com/42489509/89436370-c3818180-d763-11ea-95f2-806862d105b8.png)
This explains my problem. Both dummy and stripe don't show up here.

https://52.169.47.197/graphql/ This is my endpoint URL of saleor core if you need to use it for debugging.

Do let me know if you need any additional logs.

**Comment by nalimhahs** [comment]
Hey @krzysztofwolski, I figured out the issue. I was digging through the server logs and found an ImproperlyConfigured error being thrown by the braintree plugin, which was activated by default but not configured with the api keys. This casued the query which fetches all the payment gateways to crash resulting in none being shown at all. So for anyone facing this issue just check if any unconfigured plugins are enabled. I'm not sure if this is a bug or not but if it is I hope you do the needful. Thanks.
