### ISSUE TITLE
Can't resolve '@saleor/sdk' during docker build

### ISSUE THREAD

**Issue by yannterzi** [mirumee/saleor-storefront#843]
### What I'm trying to achieve

I'm trying to docker build my storefront by runing:
`docker build --build-arg API_URI=https://backend.mysite.com/graphql/ -f Dockerfile -t myrepo/frontend .`

But during step 14 ( `RUN API_URI=${API_URI} npm run build` ), I got a lot of errors about @saleor/sdk:

`ERROR in ./src/index.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src'
 @ ./src/index.tsx 30:14-36

ERROR in ./src/@next/components/molecules/AccountTabTiles/PasswordTile.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/@next/components/molecules/AccountTabTiles'
 @ ./src/@next/components/molecules/AccountTabTiles/PasswordTile.tsx 18:14-36
 @ ./src/@next/components/molecules/AccountTabTiles/AccountTabTiles.tsx
 @ ./src/@next/components/molecules/AccountTabTiles/index.ts
 @ ./src/@next/components/molecules/index.ts
 @ ./src/components/ProductListItem/index.tsx
 @ ./src/components/index.ts
 @ ./src/index.tsx

ERROR in ./src/@next/components/molecules/AccountTabTiles/AccountTile.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/@next/components/molecules/AccountTabTiles'
 @ ./src/@next/components/molecules/AccountTabTiles/AccountTile.tsx 17:14-36
 @ ./src/@next/components/molecules/AccountTabTiles/AccountTabTiles.tsx
 @ ./src/@next/components/molecules/AccountTabTiles/index.ts
 @ ./src/@next/components/molecules/index.ts
 @ ./src/components/ProductListItem/index.tsx
 @ ./src/components/index.ts
 @ ./src/index.tsx

ERROR in ./src/@next/components/organisms/AddressFormModal/AddressFormModal.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/@next/components/organisms/AddressFormModal'
 @ ./src/@next/components/organisms/AddressFormModal/AddressFormModal.tsx 11:14-36
 @ ./src/@next/components/organisms/AddressFormModal/index.ts
 @ ./src/@next/components/organisms/index.ts
 @ ./src/components/ProductDescription/index.tsx
 @ ./src/components/index.ts
 @ ./src/index.tsx

ERROR in ./src/@next/pages/CartPage/CartPage.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/@next/pages/CartPage'
 @ ./src/@next/pages/CartPage/CartPage.tsx 8:14-36
 @ ./src/@next/pages/CartPage/index.ts
 @ ./src/@next/pages/index.ts
 @ ./src/app/routes/AppRoutes.tsx
 @ ./src/app/routes/index.ts
 @ ./src/app/App.tsx
 @ ./src/app/index.ts
 @ ./src/index.tsx

ERROR in ./src/@next/pages/CheckoutPage/CheckoutPage.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/@next/pages/CheckoutPage'
 @ ./src/@next/pages/CheckoutPage/CheckoutPage.tsx 23:14-36
 @ ./src/@next/pages/CheckoutPage/index.ts
 @ ./src/@next/pages/index.ts
 @ ./src/app/routes/AppRoutes.tsx
 @ ./src/app/routes/index.ts
 @ ./src/app/App.tsx
 @ ./src/app/index.ts
 @ ./src/index.tsx

ERROR in ./src/@next/pages/CheckoutPage/subpages/CheckoutShippingSubpage.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/@next/pages/CheckoutPage/subpages'
 @ ./src/@next/pages/CheckoutPage/subpages/CheckoutShippingSubpage.tsx 21:14-36
 @ ./src/@next/pages/CheckoutPage/subpages/index.ts
 @ ./src/@next/pages/CheckoutPage/CheckoutPage.tsx
 @ ./src/@next/pages/CheckoutPage/index.ts
 @ ./src/@next/pages/index.ts
 @ ./src/app/routes/AppRoutes.tsx
 @ ./src/app/routes/index.ts
 @ ./src/app/App.tsx
 @ ./src/app/index.ts
 @ ./src/index.tsx

ERROR in ./src/@next/pages/CheckoutPage/subpages/CheckoutAddressSubpage.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/@next/pages/CheckoutPage/subpages'
 @ ./src/@next/pages/CheckoutPage/subpages/CheckoutAddressSubpage.tsx 24:14-36
 @ ./src/@next/pages/CheckoutPage/subpages/index.ts
 @ ./src/@next/pages/CheckoutPage/CheckoutPage.tsx
 @ ./src/@next/pages/CheckoutPage/index.ts
 @ ./src/@next/pages/index.ts
 @ ./src/app/routes/AppRoutes.tsx
 @ ./src/app/routes/index.ts
 @ ./src/app/App.tsx
 @ ./src/app/index.ts
 @ ./src/index.tsx

ERROR in ./src/@next/pages/CheckoutPage/subpages/CheckoutReviewSubpage.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/@next/pages/CheckoutPage/subpages'
 @ ./src/@next/pages/CheckoutPage/subpages/CheckoutReviewSubpage.tsx 23:14-36
 @ ./src/@next/pages/CheckoutPage/subpages/index.ts
 @ ./src/@next/pages/CheckoutPage/CheckoutPage.tsx
 @ ./src/@next/pages/CheckoutPage/index.ts
 @ ./src/@next/pages/index.ts
 @ ./src/app/routes/AppRoutes.tsx
 @ ./src/app/routes/index.ts
 @ ./src/app/App.tsx
 @ ./src/app/index.ts
 @ ./src/index.tsx

ERROR in ./src/@next/pages/CheckoutPage/subpages/CheckoutPaymentSubpage.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/@next/pages/CheckoutPage/subpages'
 @ ./src/@next/pages/CheckoutPage/subpages/CheckoutPaymentSubpage.tsx 24:14-36
 @ ./src/@next/pages/CheckoutPage/subpages/index.ts
 @ ./src/@next/pages/CheckoutPage/CheckoutPage.tsx
 @ ./src/@next/pages/CheckoutPage/index.ts
 @ ./src/@next/pages/index.ts
 @ ./src/app/routes/AppRoutes.tsx
 @ ./src/app/routes/index.ts
 @ ./src/app/App.tsx
 @ ./src/app/index.ts
 @ ./src/index.tsx

ERROR in ./src/@next/pages/PasswordReset/PasswordReset.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/@next/pages/PasswordReset'
 @ ./src/@next/pages/PasswordReset/PasswordReset.tsx 14:14-36
 @ ./src/@next/pages/PasswordReset/index.ts
 @ ./src/@next/pages/index.ts
 @ ./src/app/routes/AppRoutes.tsx
 @ ./src/app/routes/index.ts
 @ ./src/app/App.tsx
 @ ./src/app/index.ts
 @ ./src/index.tsx

ERROR in ./src/account/AddressBook/AddressBook.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/account/AddressBook'
 @ ./src/account/AddressBook/AddressBook.tsx 15:14-36
 @ ./src/views/Account/Account.tsx
 @ ./src/views/Account/index.ts
 @ ./src/app/routes/AppRoutes.tsx
 @ ./src/app/routes/index.ts
 @ ./src/app/App.tsx
 @ ./src/app/index.ts
 @ ./src/index.tsx

ERROR in ./src/components/CheckoutLogin/index.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/components/CheckoutLogin'
 @ ./src/components/CheckoutLogin/index.tsx 16:14-36
 @ ./src/components/index.ts
 @ ./src/index.tsx

ERROR in ./src/components/LoginForm/index.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/components/LoginForm'
 @ ./src/components/LoginForm/index.tsx 21:14-36
 @ ./src/components/index.ts
 @ ./src/index.tsx

ERROR in ./src/components/MainMenu/MainMenu.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/components/MainMenu'
 @ ./src/components/MainMenu/MainMenu.tsx 17:14-36
 @ ./src/components/MainMenu/index.ts
 @ ./src/components/index.ts
 @ ./src/index.tsx

ERROR in ./src/components/OverlayManager/Cart/Cart.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/components/OverlayManager/Cart'
 @ ./src/components/OverlayManager/Cart/Cart.tsx 20:14-36
 @ ./src/components/OverlayManager/Cart/index.ts
 @ ./src/components/OverlayManager/Manager.tsx
 @ ./src/components/OverlayManager/index.ts
 @ ./src/components/index.ts
 @ ./src/index.tsx

ERROR in ./src/components/ShopProvider/index.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/components/ShopProvider'
 @ ./src/components/ShopProvider/index.tsx 11:14-36
 @ ./src/index.tsx

ERROR in ./src/userAccount/views/OrderDetails/View.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/userAccount/views/OrderDetails'
 @ ./src/userAccount/views/OrderDetails/View.tsx 16:14-36
 @ ./src/userAccount/views/index.ts
 @ ./src/app/routes/AppRoutes.tsx
 @ ./src/app/routes/index.ts
 @ ./src/app/App.tsx
 @ ./src/app/index.ts
 @ ./src/index.tsx

ERROR in ./src/views/Account/Account.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/views/Account'
 @ ./src/views/Account/Account.tsx 18:14-36
 @ ./src/views/Account/index.ts
 @ ./src/app/routes/AppRoutes.tsx
 @ ./src/app/routes/index.ts
 @ ./src/app/App.tsx
 @ ./src/app/index.ts
 @ ./src/index.tsx

ERROR in ./src/views/Product/View.tsx
Module not found: Error: Can't resolve '@saleor/sdk' in '/app/src/views/Product'
 @ ./src/views/Product/View.tsx 17:14-36
 @ ./src/views/Product/index.tsx
 @ ./src/app/routes/AppRoutes.tsx
 @ ./src/app/routes/index.ts
 @ ./src/app/App.tsx
 @ ./src/app/index.ts
 @ ./src/index.tsx

ERROR in ./src/@next/pages/OrdersHistory/OrdersHistory.tsx
Module not found: Error: Can't resolve '@saleor/sdk/' in '/app/src/@next/pages/OrdersHistory'
 @ ./src/@next/pages/OrdersHistory/OrdersHistory.tsx 13:14-37
 @ ./src/@next/pages/OrdersHistory/index.ts
 @ ./src/@next/pages/index.ts
 @ ./src/app/routes/AppRoutes.tsx
 @ ./src/app/routes/index.ts
 @ ./src/app/App.tsx
 @ ./src/app/index.ts
 @ ./src/index.tsx

ERROR in ./src/account/AddressBook/AddressBook.tsx
Module not found: Error: Can't resolve '@saleor/sdk/lib/gqlTypes/globalTypes' in '/app/src/account/AddressBook'
 @ ./src/account/AddressBook/AddressBook.tsx 16:22-69
 @ ./src/views/Account/Account.tsx
 @ ./src/views/Account/index.ts
 @ ./src/app/routes/AppRoutes.tsx
 @ ./src/app/routes/index.ts
 @ ./src/app/App.tsx
 @ ./src/app/index.ts
 @ ./src/index.tsx`

### Steps to reproduce the problem
1. `git clone https://github.com/mirumee/saleor-storefront.git`
2. `npm i`
3. `docker build --build-arg API_URI=https://backend.mysite.com/graphql/ -f Dockerfile -t myrepo/frontend .`

### What I expected to happen

Succesfuly pass the `npm run build` step

**System information**
Operating system: Windows 10 with WSL2 feature
Docker: 2.3.0.4 with WSL2 based engine enabled

**Comment by sal-git** [comment]
Same issue when building from the saleor-platform repo.

**System info**
OS: Ubuntu 19.10

**Comment by pmontanaro** [comment]
Same as me when building from the saleor-platform Repo. 

I found that with the saleor-platform repo I had to manually clone the app, storefront and dashboard into their respective folders too. 

**System:**
OS: macOS Mojave 10.14

**Comment by Zaelyth** [comment]
Same and this doesn't apply only on the docker side. When I `npm start` a released version (2.10.4), then the same error is happening at runtime for every component and nothing is shown

**Comment by forestmedina** [comment]
It looks like the lib folder under node_modules/@saleor/sdk/ is not being created, that is the main difference i see with the build in the host system, also when i build directly in the build system it stop when it found the file

**Comment by psdon** [comment]
Any workaround?

**Comment by frozenpixel** [comment]
> 
> 
> Any workaround?

Do what I did here: https://github.com/mirumee/saleor-storefront/pull/849

That will successfully build in 2.10.4 with npm run build

**Comment by yannterzi** [comment]
Working since 20.11 rc-1
