### ISSUE TITLE
Use properly cursor-based pagination

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor-storefront#85]
ATM product list query requests first 8 products, then load more function requests first 16 products. It should be optimized to request first 8 products after previous pagination last cursor.

**Comment by maarcingebala** [comment]
@piotrgrundas Can we rework that during the implementation of #129? Seems related as both category and collection views would probably use the same product list component underneath.

**Comment by maarcingebala** [comment]
Resolved in #128
