### ISSUE TITLE
"npm run build" errors

### ISSUE THREAD

**Issue by hkbluesky** [mirumee/saleor-storefront#856]
### What I'm trying to achieve
I tried to build this repo by running "npm run build". But it failed. However, "npm start" works fine

### Steps to reproduce the problem
1. npm run build

### Screenshots
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/ABC/.nvm/versions/node/v12.18.2/bin/node',
1 verbose cli   '/Users/ABC/.nvm/versions/node/v12.18.2/bin/npm',
1 verbose cli   'run-script',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle saleor-site@2.11.0-a.0~prebuild: saleor-site@2.11.0-a.0
6 info lifecycle saleor-site@2.11.0-a.0~build: saleor-site@2.11.0-a.0
7 verbose lifecycle saleor-site@2.11.0-a.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle saleor-site@2.11.0-a.0~build: PATH: /Users/ABC/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/private/var/www/e_commerce/saleor-platform/saleor-storefront/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/opt/openssl/bin:/Users/ABC/opt/anaconda3/condabin:/Users/ABC/.nvm/versions/node/v12.18.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
9 verbose lifecycle saleor-site@2.11.0-a.0~build: CWD: /private/var/www/e_commerce/saleor-platform/saleor-storefront
10 silly lifecycle saleor-site@2.11.0-a.0~build: Args: [ '-c', 'webpack -p' ]
11 silly lifecycle saleor-site@2.11.0-a.0~build: Returned: code: 2  signal: null
12 info lifecycle saleor-site@2.11.0-a.0~build: Failed to exec build script
13 verbose stack Error: saleor-site@2.11.0-a.0 build: `webpack -p`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/Users/ABC/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/ABC/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid saleor-site@2.11.0-a.0
15 verbose cwd /private/var/www/e_commerce/saleor-platform/saleor-storefront
16 verbose Darwin 19.6.0
17 verbose argv "/Users/ABC/.nvm/versions/node/v12.18.2/bin/node" "/Users/ABC/.nvm/versions/node/v12.18.2/bin/npm" "run-script" "build"
18 verbose node v12.18.2
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 2
22 error saleor-site@2.11.0-a.0 build: `webpack -p`
22 error Exit status 2
23 error Failed at the saleor-site@2.11.0-a.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by EdenWoo** [comment]
Same happens to me.

**Comment by cyberdemic** [comment]
I'm having a similar issue as well. Any word if you were able to fix the problem?

Screenshots for my issue are [here](https://spectrum.chat/saleor/general/errors-running-npm-run-build-using-production-dockerfile~555a7df8-35c0-4efe-b44d-b47893aa20cf).

**Comment by cyberdemic** [comment]
@ApathyElement I ended up figuring it out, and the typescript warnings were the cause. Thank you!

**Comment by hkbluesky** [comment]
I simply downloaded the latest version and it works.
