### ISSUE TITLE
Images are served via http 

### ISSUE THREAD

**Issue by patrykwegrzyn** [mirumee/saleor-storefront#860]
### What I'm trying to achieve
Store runs on https but images are loaded via http

### What I expected to happen
Images load via https 

![image](https://user-images.githubusercontent.com/7962796/90343403-f6e7ca00-e007-11ea-95fb-9387c7d43bee.png)

**Comment by IvanPLoza** [comment]
Hi, same issue here. Did you fix it?

**Comment by Anyman552** [comment]
A workaround is to store the images on S3. https://docs.saleor.io/docs/developer/running-saleor/s3/

**Comment by krzysztofwolski** [comment]
Images should be hosted on a dedicated cloud platform (like s3 from AWS) which delivers https connection. 
More info: https://docs.saleor.io/docs/developer/running-saleor/s3
