### ISSUE TITLE
Can't configure memory limit for my node server. Default is 2048MB, want to change it to 1024MB.

### ISSUE THREAD

**Issue by Ahzam-Lathiya** [mirumee/saleor-storefront#867]
Hi. I'm trying to run the storefront on the node server with the **npm start** command. Before compiling it says **Using 1 worker with 2048MB memory limit**. The storefront is connected to the django graphql api successfully and everything checks out fine. The thing is my system only has 4GB of memory and when the server runs with 2GB, the system hangs after a couple minutes. I want to restrict this memory limit to 1GB or maybe less. I tried all the options **npm run start --node-flags --max-old-space-size=512 --no-warnings**, **export NODE_OPTIONS==--max-old-space-size=<value>** even tried to set the max-old-space-size value in the package.json. I've also created a .npmrc file in which I have included:

`node-options=--max_old_space_size=<value>`

But every time I hit **npm start** with all of these settings it still starts with 2048MB memory limit.
I'm not getting any luck with this.

my npm version:  6.13.4
my node version: 12.16.1

**Comment by frozenpixel** [comment]
The default memory limit is actually from the ForkTsCheckerWebpackPlugin. If you really want to do this, then in ./config/webpack/config.base.js change:

`new ForkTsCheckerWebpackPlugin({
      tslint: true,
      exclude: "node_modules",
    }),`

to:

`new ForkTsCheckerWebpackPlugin({
      tslint: true,
      exclude: "node_modules",
      memoryLimit: 1024,
    }),`

The storefront and dashboard take up a lot of memory when compiling, so you will likely run into resource problems, but that is how you change the memory limit.
