### ISSUE TITLE
Editing saleor-storefront 

### ISSUE THREAD

**Issue by tantotea** [mirumee/saleor-storefront#896]
This is my first time trying Saleor, I installed using Docker on Windows, to localhost, then start customizing saleor-storefront. 
But whenever a change is made in saleor-storefront, then the browser is refreshed, the change is not applied instantly. 
The change seems to be applied only after restarting docker-compose.

Is there a way to allow me see changes without needing to restart docker-compose?

Thanks!

**Comment by HarisSpahija** [comment]
You could always try to just use `npm start`, though rebuilding has to be done due to the usage of TS

**Comment by krzysztofwolski** [comment]
Personally, I like to run frontend dev environment locally and only start API from the platform docker. Notes from Haris are added to the readme.
