### ISSUE TITLE
Adding product to cart shows wrong picture - defaults to first picture

### ISSUE THREAD

**Issue by cyberdemic** [mirumee/saleor-storefront#900]
### What I'm trying to achieve
I'm trying to get the correct image to show up for the variant that was added.

### Steps to reproduce the problem
1. Create a product with multiple color variants.
2. Attach correct images to variants.
3. In the storefront, add the product to the cart where the color is not attached to the first picture listed (e.g. NOT the grey one)
4. Wrong picture is shown.

### What I expected to happen
I expect correct picture to show up in the following areas that right now don't:
  - Cart summary
  - My bag
  - My cart
  - Order details

### Screenshots
STEP 3
![note-grey](https://user-images.githubusercontent.com/54118049/93293011-cc6e6580-f79b-11ea-9c9b-bb5f5eb0268a.png)

![navy-medium-storefront](https://user-images.githubusercontent.com/54118049/93292886-80bbbc00-f79b-11ea-874d-4c997df2509b.png)

STEP 4
![storefront-cart](https://user-images.githubusercontent.com/54118049/93291675-94b1ee80-f798-11ea-9f79-e62395d33902.png)

### Other info
I wanted to note that the correct picture shows up in the dashboard when viewing the order that was placed. It only shows wrong on the storefront.

I hope this makes sense, I'm not very good at explaining sometimes. I can list more details if needed.

**Comment by cyberdemic** [comment]
Would this be an issue in the storefront code? I would like to try and look into this.

**Comment by cyberdemic** [comment]
Is this something that might be fixed when 3.0 comes out?

**Comment by krzysztofwolski** [comment]
Fixed in 3.0
