### ISSUE TITLE
[Performance] Move API endpoint to the origin host

### ISSUE THREAD

**Issue by timuric** [mirumee/saleor-storefront#903]
I would like to share my findings regarding network performance bottle neck created by the API point ```https://pwa.demo.saleor.rocks/graphql/``` in the Saleor demo.

Technically it is not an issue relevant to the storefront code base, however it does affect Lighthouse score that I believe many are looking into when evaluating the platform.

There are two issues with the endpoint, first is that it is different from the origin host, therefore the browser needs create new connection, and second issue is that it is served via HTTP1 which makes the first issue even bigger.

Even though there is ```<link rel=“preconnect”``` to the API endpoint, it only helps to save time on DNS lookup.

Let's take a look at the very first request to the API endpoint. As you can see on my test sample there are 350ms being wasted on creating new connection.  

![image](https://user-images.githubusercontent.com/4006792/93512518-15a1ef00-f92d-11ea-80d7-393a2d6267b0.png)

And same delay applies to images, because HTTP1 creates multiple connections, and due to [TCP slow start](https://en.wikipedia.org/wiki/TCP_congestion_control) design images are being served slower due to a fresh connection.

![image](https://user-images.githubusercontent.com/4006792/93512756-75989580-f92d-11ea-87ab-3204d3446851.png)

Unifying API end point and assets server with the origin host can give up to 500ms boost, specially on high latency network it can be even more substantial.

I believe you could solve this issue very swiftly with free cloudflare plan.

**Comment by NyanKiyoshi** [comment]
Hey! Thank you for raising this issue, it was in our backlog but we pushed in high priority. Work on fixing the compatibility issues with HTTP/2 will be started at the end of the month.
