### ISSUE TITLE
Non-shippable products: confirmation prompt?

### ISSUE THREAD

**Issue by cyberdemic** [mirumee/saleor-storefront#912]
### What I'm trying to achieve
When adding a product to the basket that is set to "Not shippable", it would be nice to prompt the customer with a message saying something like: "This item cannot be shipped. Would you still like to add to the cart?" Or something that shows up in cart summary / Review on that product that informs customer of the items not able to be shipped.

Is this something that would be on the radar to be added in the future?

**Comment by patrys** [comment]
What is your use case? I've never seen such a warning for non-shippable products (which are typically services or digital items).

**Comment by cyberdemic** [comment]
@patrys ah ok. My client has product that is both too heavy or is not allowed to be shipped, but is a local business that people can pick the product up. They would like customers to still be able to pay for such items with the option to pick it up locally. Im just trying to avoid customers adding an item that can't be shipped, paying for it and realizing it cant be shipped and need to refund, etc.

Maybe this is too "customized" to be put into the project as i didn't think about the digital product use cases. If so I will work on alternatives,  thank you.
