### ISSUE TITLE
Preselect Variant if Only One Variant

### ISSUE THREAD

**Issue by dynamized** [mirumee/saleor-storefront#918]
### What I'm trying to achieve
Have the variant preselected on the product details page if there is only one variant for the given product.  

I see that similar functionality was discussed briefly [in this issue](https://github.com/mirumee/saleor-storefront/issues/625).

The conclusion was that preselecting a variant would cause users to accidentally checkout with the wrong color/size, etc.  I agree with this thinking but would like to propose a solution that I believe would allow this to be implemented and still mitigate accidental variant selections.  

### Proposed solution
If the product has only ONE variant, preselect it for the user and enable the "Add to basket" button.
If the product has MULTIPLE variants, do not preselect it for the user and keep the "Add to basket" button disabled as it is in the current implementation.

### Why bother?
Implementing this would increase checkout conversions for shops with large product catalogs of one-of-a-kind items that only have one variant.  Decreasing the total clicks to checkout by 2 clicks is fairly significant.

I am learning TS and React and am working on implementing this myself.  However I could use some help!  If you help orient me as to how to accomplish this I would be very thankful.

Thank you.

**Comment by Anyman552** [comment]
I would like to see this feature too. In addition a variant marked as _DEFAULT_ should be preselected too. Do you have an implementation yet? I would like to help you.

**Comment by dynamized** [comment]
I don't have an implementation yet.  But I am still working on the storefront and would really appreciate some help with this feature!

**Comment by Anyman552** [comment]
I made it work. At least for my needs. Maybe not the best solution. 

Add the following to the top of the useEffect() function in _ProductVariantAttributeSelect.tsx_
``` 
   if (productVariantsAttribute.values.length === 1) {
      defaultValue = productVariantsAttribute.values[0].value!;
    }
```
Change [this ](https://github.com/mirumee/saleor-storefront/blob/66237b1ddbdec7844e83425c970a1bb027be08e0/src/%40next/components/organisms/ProductVariantPicker/ProductVariantAttributeSelect.tsx#L74) line to:

```
const selectedValuesList = selectedValue ? [selectedValue.value] : [defaultValue!];
```
