### ISSUE TITLE
The password is shown on the page source.

### ISSUE THREAD

**Issue by zlosliwa** [mirumee/saleor-storefront#921]
### What I'm trying to achieve
After typing in a password in the field I can see it on the page source.

### Steps to reproduce the problem
1. Go to the Storefront.
2. Click to login 
3. Fill `password` filed
4. Inspect the element

### Actual result 

The password is shown on the page source.

### What I expected to happen
Password should not be shown on the page source - I have compared this with other sites like Amazon, Shopify, etc. and I could not find this solution on other pages this is why I decided to report this.

### Screenshots
![image](https://user-images.githubusercontent.com/29308910/95661284-65d82f80-0b2e-11eb-93f9-17989676ae66.png)

**System information**
Operating system:  Windows 10
Browser: Chrome & Firefox

**Comment by karolkielecki** [comment]
@zlosliwa Thanks for reporting. Our team will check it out.

**Comment by hundredeir** [comment]
I don't how that makes a difference. Even if password is not showing as the value attribute. It is still there. It's on your computer. There is nothing wrong with that.
