### ISSUE TITLE
Order details are shown after login/out.

### ISSUE THREAD

**Issue by zlosliwa** [mirumee/saleor-storefront#922]
### What I'm trying to achieve
If a user will create complete checkout and go to the order details and then logs in - the user sees all the information in order.
If a logged user will create complete checkout and go to the order details and then logs out - the order details page is still shown. 

### Steps to reproduce the problem
1. Log in as a client
2. Create checkout 
3. Go to the order details 
4. Log out 
or 
1. Create checkout as a guest
2. Go to the order details 
3. Log in 

### Actual result
In both situations, the order details page is shown. 

### What I expected to happen
The main page should be shown 

### Screenshots
**Not logged user**
![image](https://user-images.githubusercontent.com/29308910/95686656-81f7d180-0bff-11eb-9b31-c807aabd8309.png)
**Login to accout on the order details page** 
![image](https://user-images.githubusercontent.com/29308910/95686675-9dfb7300-0bff-11eb-942f-17f89b2813f7.png)

**System information**
Operating system: Ubuntu 20.04 
Browser: FireFox

**Comment by karolkielecki** [comment]
@zlosliwa Could you please tell us what your version of the storefront is?

**Comment by zlosliwa** [comment]
@karolkielecki 2.10
