### ISSUE TITLE
Issue with t-shirt or carrot juice quantity.

### ISSUE THREAD

**Issue by RafalTatun** [mirumee/saleor-storefront#926]
### What I'm trying to achieve
When user will add 50 amount of T-shirt to shoping cart or anything else, user can't buy anything more. Tested with t-shirt and carrot juice.

### Steps to reproduce the problem
1. Open https://demo.saleor.io/ in Chrome/Firefox
2. Go to the t-shirt or carrot juice
3. Get 50 amount of t-shirt (S) or carrot juice
4. Next try to get 1 of t-shirt (M)
5. Problem show (Maximum quantity is -61)

### Actual result
In both situations, there is a problem with quantity (Maximum quantity is -61).

### What I expected to happen
Option to add an extra t-shirt or carrot juice to the cart.

### Screenshots
![Quantity issue](https://user-images.githubusercontent.com/32794671/96375967-8d597880-117c-11eb-8e8c-4a3203567455.PNG)
![Quantity issue1](https://user-images.githubusercontent.com/32794671/96375969-8f233c00-117c-11eb-8fa2-f7a2b00c0ebe.PNG)

**System information**
Operating system: Windows 10 Home
Browser: Firefox/Chrome

**Comment by hundredeir** [comment]
For me, In case of small T-shirt it says max quantity as 50, and medium T-shirt's max quantity as 1.

**Comment by RafalTatun** [comment]
There I have a cypress test for that.
Link: https://github.com/RafalTatun/CypressTestsSaleor

**Comment by hundredeir** [comment]
I have just checked on Firefox (mobile) for medium now it says -6.
