### ISSUE TITLE
Product not displaying selected image when selecting a variant

### ISSUE THREAD

**Issue by cyberdemic** [mirumee/saleor-storefront#927]
### What I'm trying to achieve
I want to select the product variant (e.g. color of product) and have it display that specific image.

This worked correctly in: 2.11.0-rc.6 of Dashboard/Core and 2.11.0-rc.4 of Storefront and previous versions.

Updating to: 2.11.0-rc.8 of Dashboard/Core and 2.11.0-rc.5 of Storefront caused the issue to appear.

### Steps to reproduce the problem
1. Make sure images are attached to product variants in the dashboard
2. Go to product that has variant with multiple images
3. Select variant and notice picture does not change to selected variant 

### What I expected to happen
I expect only the image of selected variant to show up (e.g. if you have 3 images, red, white, blue and you select blue color variant it should show the blue image

**System information**
Operating system: Docker
Browser: Firefox

**Comment by karolkielecki** [comment]
@cyberdemic Hey. Thanks for reporting. We'll investigate it as soon as we can.

**Comment by cyberdemic** [comment]
Thank you for the fix: https://github.com/mirumee/saleor-storefront/commit/f7e52daf66a8f34676baa99c35d9b1b2424c4814
