### ISSUE TITLE
Variable to change the "Saleor" name

### ISSUE THREAD

**Issue by macabeus** [mirumee/saleor-storefront#945]
### What I'm trying to achieve
Easer configuration and futures updates.

### Describe a proposed solution
Like explained [on readme](https://github.com/mirumee/saleor-storefront#important-files), we should update to files to changes the app name `Saleor`.
But changing the codebase isn't very well, because could be harder to update the storefront version and isn't beginner friendly IMHO.

We could add the new configuration `APP_NAME` on `src/core/config.ts`.

**Comment by Luka-Abey** [comment]
I agree, would be good to just have it as a variable in the config !
