### ISSUE TITLE
Service Worker always offline on new Chrome 86

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor-storefront#953]
### What I'm trying to achieve
My chrome got an update on mac - and since then, the webshop stays offline!! The same issue for the hosted saleor version. In the network dev tools, I see 200 Ok from GraphQL, but still offline :/ don't know, what they changed.

### Steps to reproduce the problem
1. 
2. 

### What I expected to happen
…

### Screenshots

**System information**
Operating system: 
Browser:

**Comment by karolkielecki** [comment]
@JannikZed Hey! Do you still have this error?

**Comment by JannikZed** [comment]
actually no - don't know what happened there.
