### ISSUE TITLE
Alternative storefronts

### ISSUE THREAD

**Issue by dsoprea** [mirumee/saleor-storefront#969]
Correct me if I'm wrong, but it seems like the emphasis for the Saleor platform is that it's headless/decoupled and that the storefront should be swappable, and, for this storefront project, that it's experimental at this point in time, and it's more of an example. Therefore, I'd expect there to be some kind of index or marketplace for storefronts that can simply be downloaded and applied. But, this doesn't seem to be the case even with Saleor apparently being as popular as it is. What am I missing?

**Comment by patrys** [comment]
Keep in mind most storefronts that are created are closed source and built for a particular website. We keep improving the Saleor Storefront project. We're working on porting projects like Next.js Commerce and Vue Storefront to Saleor but expecting to see a marketplace full of open-source storefronts to choose from is simply unrealistic. 😉
