### ISSUE TITLE
Warning: Encountered two children with the same key

### ISSUE THREAD

**Issue by AgentIvan** [mirumee/saleor-storefront#977]
### What I'm trying to achieve
…

### Steps to reproduce the problem
1.  Create Category
2.  Create Product with the same name

### What I expected to happen
no errors in console 

### Screenshots
![image](https://user-images.githubusercontent.com/16723960/104178356-77b9bf00-540a-11eb-9f01-0f0fa4714a76.png)

src\views\Product\Page.tsx:
```
        const populateBreadcrumbs = product => [
          {
            link: generateCategoryUrl(product.category.id, product.category.name),
            value: product.category.name,
          },
          {
            link: generateProductUrl(product.id, product.name),
            value: product.name,
          },
        ];
```
src\components\Breadcrumbs\index.tsx:
```
        {breadcrumbs.map((breadcrumb, index) => (
          <li
            key={breadcrumb.value}
            className={classNames({
              breadcrumbs__active: index === breadcrumbs.length - 1,
            })}
          >
            <Link to={breadcrumb.link}>{breadcrumb.value}</Link>
          </li>
        ))}
```
**System information**
Operating system: 
Browser:

**Comment by jwm0** [comment]
@AgentIvan thanks for submitting the issue, the PR is already waiting and should be merged today
