### ISSUE TITLE
Django Saleor NPM Start Log

### ISSUE THREAD

**Issue by goofyIsCool** [mirumee/saleor-storefront#995]
I can not access my website via browser. I'm not sure if "npm start" is working properly.
I am running my saleor server in the back on 0.0.0.0:8000. I have also attached my package.json sc down below. 

![image](https://user-images.githubusercontent.com/72651157/108636738-8a9ec500-7487-11eb-9906-6dcd4c813a9a.png)

![image](https://user-images.githubusercontent.com/72651157/108636761-ab671a80-7487-11eb-80eb-668e53c275e5.png)

Operating system: Linux Ubuntu 18.04

**Comment by pgiki** [comment]
"npm start" takes some time to run the application. You may have to wait until you see the message "event - compiled successfully" for your application to be accessible on the port.

**Comment by goofyIsCool** [comment]
Thanks, I'll wait.
