### ISSUE TITLE
Production was loaded over HTTPS, but requested an insecure image (HTTP)

### ISSUE THREAD

**Issue by pupubird** [mirumee/saleor-storefront#999]
### What I'm trying to achieve
Load the product images on production ( `npm run build` )

### Steps to reproduce the problem
1. Run the command `API_URI=https://<the domain>/graphql/ npm run build` 
2. Serve the bundle on `dist`
3. Check on the inspection

### What I expected to happen
Images are loaded over HTTPS

### Screenshots
![image](https://user-images.githubusercontent.com/35325976/109588162-47a5b700-7b43-11eb-878f-d9228c4c13f5.png)

**System information**
Operating system: S3
Browser:Chrome

**Comment by pupubird** [comment]
Is anyone experiencing the same issue?

**Comment by krzysztofwolski** [comment]
Urls to product images are provided by Core, so you should change settings of your media bucket to use https

**Comment by ktmswzw** [comment]
> ### What I'm trying to achieve
> Load the product images on production ( `npm run build` )
> 
> ### Steps to reproduce the problem
> 1. Run the command `API_URI=https://<the domain>/graphql/ npm run build`
> 2. Serve the bundle on `dist`
> 3. Check on the inspection
> 
> ### What I expected to happen
> Images are loaded over HTTPS
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/35325976/109588162-47a5b700-7b43-11eb-878f-d9228c4c13f5.png)
> 
> **System information**
> Operating system: S3
> Browser:Chrome

## dashboard
export APP_MOUNT_URI=/dashboard/
export MEDIA_URL=https://api.xxx.com/media/
export API_URI=https://api.xxx.com/graphql/
npm run build:export

## web
export APP_MOUNT_URI=/dashboard/
export API_URI=https://api.xxx.com/graphql/
npm run build:export

## saleor api
export ALLOWED_HOSTS=api.xxx.com,admin.xxx.com,www.xxx.com,
export ALLOWED_CLIENT_HOSTS=api.xnewshop.com,admin.xnewshop.com,www.xxx.com,
export INTERNAL_IPS=api.xxx.com,admin.xxx.com,www.xxx.com,
export MEDIA_URL=https://api.xxx.com/media/
manage.py runserver

@pupubird

**Comment by pupubird** [comment]
Alright! Resolved it with the new setting, thanks guys!
